Fixes upon taking in gWSL integration and de-bloombergization.
bin/cron_wrapper
* Clean up profile execution.

bin/crontest
* Enhanced information.

bin/monkeypatch
* Put CRON test for verbosity here by default, instead of scattered
  across profiles and bashrcs.

dotfiles/bash_profile
* Some settings moved to here, the highest level profile. Monkeypatch and
  verbosity cleanup.

dotfiles/bashrc
* Monkeypatch and verbosity cleanup.

dotfiles/bashrcuser
* Monkeypatch and verbosity cleanup.

dotfiles/gitconfig
* Added swtich alias.

dotfiles/profile
* Monkeypatch and verbosity cleanup.

dotfiles/xterminit
* Properly guarded gWSL tests for non-WSL environments.

functions/addpath
* Insert at index option now actually works.
* Cleaner USAGE assignment.

functions/pathfunc_usage_init
* Clarify -n index base.

functions/searchpath
* Added -o to return index number without the value.
* Cleaner USAGE assignment.

diff --git a/dotfiles/xterminit b/dotfiles/xterminit
--- a/dotfiles/xterminit
+++ b/dotfiles/xterminit
@@ -11,7 +11,7 @@
 ## - No variables with - in them. Use _ instead.
 
 if [[ -z "$DISPLAY" ]]; then
-    if gwsl-ctrl running; then
+    if iswsl && gwsl-ctrl running; then
         gwsl-ctrl set-envvars
     else
         # Maybe this is a putty - see if there's another process with DISPLAY
@@ -30,12 +30,10 @@ if ! type -P xmodmap 1>/dev/null; then
 fi
 
 ## Is X running?
-if ! tasklist.exe | grep -iq gwsl; then
-    if ! perl -e 'alarm shift @ARGV; exec @ARGV' 5 xmodmap 1>/dev/null 2>/dev/null; then
-        if ! ~/personal/bin/launchxserver --silent; then
-            echo "XServer not running, can't be launched. xterm setup skipped."
-            return 0
-        fi
+if ! perl -e 'alarm shift @ARGV; exec @ARGV' 5 xmodmap 1>/dev/null 2>/dev/null; then
+    if ! ~/personal/bin/launchxserver --silent; then
+        echo "XServer not running, can't be launched. xterm setup skipped."
+        return 0
     fi
 fi
 
