updates for xpra

diff --git a/dotfiles/xterminit b/dotfiles/xterminit
--- a/dotfiles/xterminit
+++ b/dotfiles/xterminit
@@ -11,30 +11,34 @@
 ## - No associative arrays.
 ## - No variables with - in them. Use _ instead.
 
-if [[ -z "$DISPLAY" ]]; then
-    if iswsl && gwsl-ctrl running; then
-        gwsl-ctrl set-envvars
-    else
-        # Maybe this is a putty - see if there's another process with DISPLAY
-        # defined:
-        # ps -U $USER -expandedcomamndsincludingenvvars \
-            #   | sed -E -e 's/.*DISPLAY/DISPLAY/' -e 's/ .*//' \
-            #   | sort -u | grep -v '=:0.0'
-        export DISPLAY=:0.0
+if echo "$TERM" | grep xterm; then
+    echo "$(date) - $(hostname) - TERM is $TERM - assume some sort of X server is running"
+else
+    if [[ -z "$DISPLAY" ]]; then
+        if iswsl && gwsl-ctrl running; then
+            gwsl-ctrl set-envvars
+        else
+            # Maybe this is a putty - see if there's another process with DISPLAY
+            # defined:
+            # ps -U $USER -expandedcomamndsincludingenvvars \
+                #   | sed -E -e 's/.*DISPLAY/DISPLAY/' -e 's/ .*//' \
+                #   | sort -u | grep -v '=:0.0'
+            export DISPLAY=:0.0
+        fi
     fi
-fi
 
-## Is X installed?
-if ! type -P xmodmap 1>/dev/null; then
-    echo 'No X installed. xterm setup skipped.'
-    true; return
-fi
-
-## Is X running?
-if ! perl -e 'alarm shift @ARGV; exec @ARGV' 5 xmodmap 1>/dev/null 2>/dev/null; then
-    if ! ~/personal/bin/launchxserver --silent; then
-        echo "XServer not running, can't be launched. xterm setup skipped."
+    ## Is X installed?
+    if ! type -P xmodmap 1>/dev/null; then
+        echo "$(date) - $(hostname) - X does not appear to be installed. xterm setup skipped."
         true; return
+    fi
+
+    ## Is X running?
+    if ! perl -e 'alarm shift @ARGV; exec @ARGV' 5 xmodmap 1>/dev/null 2>/dev/null; then
+        if ! ~/personal/bin/launchxserver --silent; then
+            echo "XServer not running, can't be launched. xterm setup skipped."
+            true; return
+        fi
     fi
 fi
 
