Adjustments for WSL
README-direct.md
* Corrected git-template repo name.

bin/git-clone
* Use ssh to clone to avoid credential issues.

bin/git-hook
* Skip processing the template repo itself.

bin/launchxserver
* Adjustments for changes in uname output.

bin/makesymlinks
* Need some utilities in bin before we've set up PATH.

bin/xo
hasX():
  * Just count processes; cannot seem to depend on emacslcient detaching to
    parent pid 1 on WSL.

dotfiles/dotfilesbootstrap
* Added message to track what is being defined.

dotfiles/xterminit
* Update X check to include gwsl.

diff --git a/dotfiles/xterminit b/dotfiles/xterminit
--- a/dotfiles/xterminit
+++ b/dotfiles/xterminit
@@ -26,10 +26,12 @@ if ! type -P xmodmap 1>/dev/null; then
 fi
 
 ## Is X running?
-if ! perl -e 'alarm shift @ARGV; exec @ARGV' 5 xmodmap 1>/dev/null 2>/dev/null; then
-    if ! ~/personal/bin/launchxserver --silent; then
-        echo "XServer not running, can't be launched. xterm setup skipped."
-        return 0
+if ! tasklist.exe | grep -iq gwsl; then
+    if ! perl -e 'alarm shift @ARGV; exec @ARGV' 5 xmodmap 1>/dev/null 2>/dev/null; then
+        if ! ~/personal/bin/launchxserver --silent; then
+            echo "XServer not running, can't be launched. xterm setup skipped."
+            return 0
+        fi
     fi
 fi
 
