Massive mechanical changes
README.md
* More updates on GH syncing.

bin/bash-usage
* Normalized cmd-echo calls, true/false exit/return fixes.
* ftrue and ffalse

bin/cmd-echo
* ftrue and ffalse

bin/color-echo
* ftrue and ffalse

bin/crontab-extract
crontab_file():
  * printf instead of looped echo.

bin/func-to-exec
* ftrue and ffalse

bin/git-add-remote
* Updated audit.

bin/git-bisect
* No git-version-verify on every call.
* Updated audit.
* Updated audit.

bin/git-branch
* Normalized and added --id to cmd-echo calls.
* ftrue and ffalse

bin/git-check-with-default-branch
* Updated audit.
* Updated audit.

bin/git-check-with-remote
* Added --id to cmd-echo calls. Main-ized. true/false exit/return fixes.
* ftrue and ffalse
* Updated audit.

bin/git-clone
* Updated audit.

bin/git-comment
* ftrue and ffalse
* Updated audit.

bin/git-commit
* Updated audit.

bin/git-config
* Converted to a function.

bin/git-daily-repo-check
* Updated audit.

bin/git-find
* Updated audit.

bin/git-go
* ftrue and ffalse
* Updated audit.

bin/git-go-get
* ftrue and ffalse
* Updated audit.

bin/git-go-prune
* Updated audit.

bin/git-go-set
* ftrue and ffalse
* Updated audit.

bin/git-grep
* Updated audit.

bin/git-help
* Updated audit.

bin/git-hold
* Updated audit.

bin/git-hook
* Updated audit.

bin/git-kv
* Make the pair printing really work.
* Updated audit.

bin/git-log
* Updated audit.

bin/git-log-grab-sha
* Updated audit.

bin/git-log-shas-range
* ftrue and ffalse
* Updated audit.

bin/git-ls-files
* Updated audit.

bin/git-ls-remote
* Updated audit.

bin/git-mono
* Updated audit.

bin/git-ping
* ftrue and ffalse
* Updated audit.

bin/git-post-new
* Updated audit.

bin/git-pre-commit-test
* Updated audit.

bin/git-process-source-ctrl-log
* Updated audit.

bin/git-push
* Updated audit.

bin/git-rebase
* Swap out script-pick for cmd-pick.
* Updated audit.

bin/git-repo
* Updated audit.

bin/git-retaint
* Updated audit.

bin/git-retimestamp
* Updated audit.

bin/git-stash
* Updated audit.

bin/git-status-ext
* Updated audit.

bin/git-status-with-source-ctrl-log
* ftrue and ffalse
* Updated audit.

bin/git-sync-with-remote
* Remove assumption about what the canonical source remote is for a
  branch. Main-ized. true/false exit/return fixes.
* ftrue and ffalse
* Updated audit.

bin/git-to-stdout
* Updated audit.

bin/git-untaint
* Updated audit.

bin/git-utils
* The inevitable "miscellaneous" command for bits of functionality.
* Updated audit.

bin/git-web
* Updated audit.

bin/git-what
* Updated audit.

bin/git-worktree
* ftrue and ffalse
* Removed STDOUT variable in favor of hardcoded 1. Only place it is ever
  referenced. Now we can get rid of util.env
* Updated audit.

bin/github-api
* Updated audit.

bin/github.env.init
* Updated audit.

bin/gitsync.cron
* Updated audit.

bin/logit
* ftrue and ffalse

bin/makesymlink
* ftrue and ffalse

bin/mktemp.binc
* ftrue and ffalse

_mktemp_guts():
  * Return the exit code of the mktemp call. Errors printed to stderr.

bin/on_exit.binc
* ftrue and ffalse

bin/pick
* ftrue and ffalse

bin/script-pick
* Obsolete.

bin/sedinplace
* Added --id to cmd-echo calls.
* ftrue and ffalse

bin/toxic
* ftrue and ffalse

bin/yesno
* ftrue and ffalse

bin/zen
* ftrue and ffalse

functions/dirlist
* ftrue and ffalse

functions/get-next-descriptor
* Shellchecked. true/false returned. Documented why it must be a
  function.
* ftrue and ffalse

functions/git
* Some documentation changes, true/false additions, cmd-echo replacing
  echo.
* Removed sourcing mktemp; hardcode the temp filename format instead of
  paying the cumulative sourcing penalty.
* Change the command lookup criteria to properly process functions, not
  only scripts.
* Change the verbosity algo to be a list of commands or 'all'.

functions/git-config
* Updated audit.

functions/git-get-default-remote
* Remove spurious set -x.

functions/use
* ftrue and ffalse

diff --git a/bin/bash-usage b/bin/bash-usage
--- a/bin/bash-usage
+++ b/bin/bash-usage
@@ -23,7 +23,7 @@ _guts-usage ()
         chmod +x "$tmpfile"
         "$tmpfile"
     else
-        echo "No usage text found for $tgt" >&2
+        cmd-echo --id bash-usage -w -- "No usage text found for '$tgt'."
     fi
 }
 
@@ -35,8 +35,8 @@ _script-usage ()
         local newtgt
         newtgt=$(type -P "$tgt" 2>/dev/null)
         if [[ ! -r "$newtgt" ]]; then
-            cmd-echo -w --id bash-usage -- "Cannot find $tgt on PATH to get usage text"
-            exit 1
+            cmd-echo --id bash-usage -w  -- "Cannot find '$tgt' on PATH to get usage text."
+            ffalse; return $?
         else
             tgt="$newtgt"
         fi
@@ -56,8 +56,8 @@ _func-usage()
                                  ## in which the function was defined
                                  ## (effectively a find command on FPATH).
     if [[ ! -r "$newtgt" ]]; then
-        cmd-echo -w --id bash-usage -- "Cannot find $tgt on FPATH to get usage text"
-        exit 1
+        cmd-echo --id bash-usage -w -- "Cannot find '$tgt' on FPATH to get usage text."
+        ffalse; return $?
     else
         tgt="$newtgt"
     fi
@@ -68,18 +68,21 @@ _func-usage()
 main() {
     local tgt
     tgt=$1
-    [[ -z "$tgt" ]] && cmd-echo -w --id bash-usage -- "Missing argument to read for usage text" && exit 1
-    [[ "$1" =~ ^-+h ]] && bash-usage "$0" && exit 0
+    if [[ -z "$tgt" ]]; then
+        cmd-echo --id bash-usage -w -- "Missing argument to read for usage text."
+        ffalse; return $?
+    fi
+    [[ "$1" =~ ^-+h ]] && bash-usage "$0" && { ftrue; return $?; }
 
     if [[ -r $tgt ]]; then
         _guts-usage "$tgt"
-        exit 0
+        ftrue && return $?
     fi
 
     local type
     type=$(type "$tgt" 2>&1 | head -1 | grep -v 'not found')
     if [[ -z "$type" ]]; then
-        echo "$tgt not found"
+        cmd-echo --id bash-usage -e -- "$tgt not found"
     elif [[ "$type" =~ 'is a function' ]]; then
         _func-usage "$tgt"
     else
@@ -89,8 +92,7 @@ main() {
 }
 
 main "$@"
-
-exit 0
+exit $?
 
 :<<'__PODUSAGE__'
 =head1 NAME
diff --git a/functions/git b/functions/git
--- a/functions/git
+++ b/functions/git
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-##echo "****** GIT WRAPPER ENTERED!!!!!******" >&2
 # git
 
 # A wrapper around 'git' to extend it. See the docs at file's end.
@@ -9,8 +8,8 @@ git ()
     # shellcheck disable=SC2034
     local DEBUG__this_function=${FUNCNAME[0]}
     if [[ -z "$REALGIT" ]]; then
-        echo "ERROR: git wrapper function 'git' can't find system git because envvar REALGIT is not defined. Bailing..."
-        return 1
+        cmd-echo --id 'GIT WRAPPER' --ec -- "git wrapper function 'git' can't find system git because envvar REALGIT is not defined. Bailing..."
+        ffalse; return $?
     fi
 
     if [[ $1 =~ --(real|bypass) ]]; then
@@ -30,58 +29,74 @@ git ()
             return $?
         else
             git-usage git
-            true; return $?
+            ftrue; return $?
         fi
     fi
 
     # We made 'git' a function so that it would operate in the current process
-    # space, which in turn means that any 'cd's that are executed, "stick" for
-    # the user.  However, this function is still calling scripts in subprocess
-    # space; any 'cd's in that subprocess are not going to stick even if
-    # executed from a function.  So, what we do here is we keep a list of
-    # commands whose 'cd' operations we want to have effect the current process
-    # space.  When we call any of these functions, we pass them the flag
-    # --doandcd with the name of a temp file.  Before those commands exit
-    # successfully, they get their current working directory and write it into
-    # the temp file.  When we return here after the command, we check the temp
-    # file and if it contains a change directory command, we execute it so that
-    # we end up where the command wanted us to be.
-    use mktemp
+    # space. This, in turn, means that any 'cd's that are executed by this
+    # function "stick" for the caller.  However, this function is still calling
+    # scripts in subprocess space; any 'cd's in subprocesses are not going to
+    # "stick" even if executed inside this function.  So, what we are doing
+    # here is keeping a list of commands whose 'cd' operations we want to have
+    # effect the current process space.  When we call any of these functions,
+    # we pass them the flag --doandcd with the name of a temp file.  Before
+    # those commands exit successfully, they get their current working
+    # directory and write it into the temp file.  When we return here after the
+    # command, we check the temp file and if it contains a change directory
+    # command, we execute it so that we end up where the subprocess wanted us
+    # to be.
     local doandcdfile
     local -A doandcdlist
-    doandcdlist[clone]=1
-    doandcdlist[go]=1
-    doandcdlist[worktree]=1
-    doandcdlist[wt]=1
-    doandcdlist[repo]=1
+    doandcdlist=([clone]=1 [go]=1 [worktree]=1 [wt]=1 [repo]=1)
 
     # Set up the temp file to hold the target dir if we've been asked to
-    # execute one of the 'cd'ing commands.
+    # execute one of the 'cd'ing commands. This command is so ubiquitous that
+    # we are not going to pay the cumulative time penalty of sourcing
+    # 'mktemp.binc' every time we run the function; we just use the same format
+    # for the tempfile name that we find in that library.
     local command=$1; shift
     local -a args
     if [[ -n "${doandcdlist[$command]}" ]]; then
-        doandcdfile=$(mktempfile -+  "doandcd.$command")
+        doandcdfile=$(mktemp -t "tmp.$$.git-wrapper.doandcd.${command}.XXXXXXXXX")
         args+=('--doandcd' "$doandcdfile")
     fi
     args+=("$@")
 
-    # Execute either our command wrapper or the real git command, using the
-    # type -P command to find any wrapper on PATH, just like git does. Except
-    # that we will happily execute a script that matches a real git command.
-    [[ -n "$GIT_DISPATCHER_VERBOSE" ]] && echo GIT WRAPPER sees command as "$command" and args as "${args[@]}" >&2
-    local extend_script="git-${command}"
-    if type -P "$extend_script" 1>/dev/null 2>/dev/null; then
-        [[ -n "$GIT_DISPATCHER_VERBOSE" ]] && echo GIT WRAPPER calling "$extend_script" "${args[@]}" >&2
-        "$extend_script" "${args[@]}"
+    # Execute either our command wrapper or the real git command, looking for a
+    # function or a script that matches git-$command, just like git does.
+
+    # Except that we will execute a function if we find it.
+
+    # And we will happily execute a function or script that matches a real git
+    # command.
+    local extend_command="git-${command}"
+    local is_func
+    local is_script
+    is_func=$(declare -F "$extend_command" 2>/dev/null)
+    [[ -z $is_func ]] && is_script=$(which "$extend_command" 2>/dev/null)
+    if [[ -n $is_func ]] || [[ -n $is_script ]]; then
+        if [[ ",${GIT_DISPATCHER_VERBOSE}," =~ ,${command},|all ]]; then
+            local t
+            [[ -n $is_func ]] && t='function'
+            [[ -z $t ]] && t='script'
+            cmd-echo --id 'GIT WRAPPER' --dc -- "Calling $t $extend_command ${args[*]}"
+        fi
+
+        "$extend_command" "${args[@]}"
     else
-        [[ -n "$GIT_DISPATCHER_VERBOSE" ]] && echo GIT WRAPPER calling "${REALGIT}" "${command}" "${args[@]}" >&2
+        if [[ ",${GIT_DISPATCHER_VERBOSE}," =~ ,${command},|all ]]; then
+            cmd-echo --id 'GIT WRAPPER' --dc -- "Calling ${REALGIT} ${command} ${args[*]}"
+        fi
+
         "${REALGIT}" "${command}" "${args[@]}"
     fi
+
     local status=$?
 
     # If the command succeeds and we have a valid directory changing command in
     # the temp file, change directory.
-    if ((status == 0)) \
+    if ((status == $(ftrue; echo $?))) \
            && [[ -n "$doandcdfile" ]] \
            && (( $(wc -l < "$doandcdfile") > 0 )); then
         local -a cdcmd
@@ -95,12 +110,16 @@ git ()
             "${cdcmd[@]}"
             status=$?
         else
-            cmd-echo -ec -- "Cannot '${cdcmd[*]}' - only 'cd', 'go', and 'git go' are supported"
-            status=1
+            cmd-echo --id 'GIT WRAPPER' -ec -- "Cannot '${cdcmd[*]}' - only 'cd', 'go', and 'git go' are supported"
+            ffalse; status=$?
         fi
     fi
 
-    # Whether or not the command succeeded, clean up after ourselves.
+    # Whether or not the command succeeded, clean up after ourselves. This
+    # command is so ubiquitous that we are not going to pay cumulative time
+    # penalty of sourcing 'on_exit.binc' every time we run the function; on the
+    # extremely rare occasions that we don't get here, we'll let normal temp
+    # cleanups take care of it.
     [[ -n $doandcdfile ]] && \rm -f "$doandcdfile"
 
     return $status
@@ -136,11 +155,21 @@ hand off to the existing command. Handing off is done by executing
 We do this because $REALGIT will not run YOUR git-bar (which is why we have
 THIS script at all), meaning you won't end up in an endless loop.
 
-The variables REALGIT and REALGIT_EXEC_PATH are defined in git.env
+The variables REALGIT and REALGIT_EXEC_PATH are defined in 'git.env'.
 
-Note: If, as part of your new command or extended functionality, you want to
-'cd' to someplace other than the current working directory, see the internal
+Notes:
+
+1) If, as part of your new command or extended functionality, you want to 'cd'
+to someplace other than the current working directory, see the internal
 comments of this function on how to do that.
+
+2) Define the envvar GIT_DISPATCHER_VERBOSE to see what this wrapper chooses to
+execute. Set it 'all' to catpure all commands or set it to
+
+ 'cmd1,cmd2,cmd3'
+
+to capture only those three commands. You can use any number of comma-separated
+commands.
 
 =cut
 
