Double braces everywhere

diff --git a/bin/bash-usage b/bin/bash-usage
--- a/bin/bash-usage
+++ b/bin/bash-usage
@@ -31,10 +31,10 @@ _script-usage ()
 {
     local tgt
     tgt="$1"
-    if [ ! -r "$tgt" ]; then
+    if [[ ! -r "$tgt" ]]; then
         local newtgt
         newtgt=$(type -P "$tgt" 2>/dev/null)
-        if [ ! -r "$newtgt" ]; then
+        if [[ ! -r "$newtgt" ]]; then
             cmd-echo -w --id bash-usage -- "Cannot find $tgt on PATH to get usage text"
             exit 1
         else
@@ -55,7 +55,7 @@ _func-usage()
                                  ## bash. -w is "where" and it locates the file
                                  ## in which the function was defined
                                  ## (effectively a find command on FPATH).
-    if [ ! -r "$newtgt" ]; then
+    if [[ ! -r "$newtgt" ]]; then
         cmd-echo -w --id bash-usage -- "Cannot find $tgt on FPATH to get usage text"
         exit 1
     else
@@ -68,7 +68,7 @@ _func-usage()
 main() {
     local tgt
     tgt=$1
-    [ -z "$tgt" ] && cmd-echo -w --id bash-usage -- "Missing argument to read for usage text" && exit 1
+    [[ -z "$tgt" ]] && cmd-echo -w --id bash-usage -- "Missing argument to read for usage text" && exit 1
     [[ "$1" =~ ^-+h ]] && bash-usage "$0" && exit 0
 
     if [[ -r $tgt ]]; then
@@ -78,7 +78,7 @@ main() {
 
     local type
     type=$(type "$tgt" 2>&1 | head -1 | grep -v 'not found')
-    if [ -z "$type" ]; then
+    if [[ -z "$type" ]]; then
         echo "$tgt not found"
     elif [[ "$type" =~ 'is a function' ]]; then
         _func-usage "$tgt"
diff --git a/bin/git-daily-repo-check b/bin/git-daily-repo-check
--- a/bin/git-daily-repo-check
+++ b/bin/git-daily-repo-check
@@ -4,10 +4,10 @@ echo "$(date): git-daily-repo-check" >> "$HOME/.gitaudit"
 
 # git-daily-repo-check
 
-if [ -r ~/.git-daily-repo-check.hosts ]; then
+if [[ -r ~/.git-daily-repo-check.hosts ]]; then
     declare x
     x=$(grep "$(hostname)" ~/.git-daily-repo-check.hosts)
-    if [ -z "$x" ]; then
+    if [[ -z "$x" ]]; then
         ## Host name not found in the file
         echo "Skipping git-daily-repo-check on $(hostname)"
         exit 0
@@ -15,7 +15,7 @@ if [ -r ~/.git-daily-repo-check.hosts ]; then
 fi
 
 declare repo=$1; shift;
-[ -z "$repo" ] && echo "Missing repo location arg. Exiting." && exit 1
+[[ -z "$repo" ]] && echo "Missing repo location arg. Exiting." && exit 1
 ( ## to isolate 'cd' effects
     # shellcheck disable=SC2164
     cd "$repo"
@@ -24,8 +24,8 @@ declare repo=$1; shift;
     repo_key="$(echo "$(date +%Y%m%d;echo :;git status --porcelain | sha1sum)" |  sed 's/ //g')"
     declare repo_key_cache='.git-daily-repo-check.marker'
     declare repo_key_last
-    [ -r $repo_key_cache ] && repo_key_last=$(cat $repo_key_cache 2>/dev/null)
-    if [ ! "$repo_key_last" = "$repo_key" ]; then
+    [[ -r $repo_key_cache ]] && repo_key_last=$(cat $repo_key_cache 2>/dev/null)
+    if [[ ! "$repo_key_last" = "$repo_key" ]]; then
         echo "** Check ${PWD} against default branch ***"
         git-check-with-default-branch --bail-on-dirty
         echo "** Check ${PWD} against itself ***"
diff --git a/bin/xo b/bin/xo
--- a/bin/xo
+++ b/bin/xo
@@ -47,7 +47,7 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
             declare tmp
             tmp=$(type -P "$1")
             shift
-            if [ -z "$tmp" ]; then
+            if [[ -z "$tmp" ]]; then
                 cmd-echo -wc -- "$1 not found; skipping"
             else
                 which+=("$tmp")
@@ -58,13 +58,13 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
             emacsclient_exe="$1/emacsclient"
             declare i
             for i in $emacs_exe $emacsclient_exe; do
-                [ -x "$i" ] || (cmd-echo "Cannot find '$i'. --root cannot be used." && exit 1);
+                [[ -x "$i" ]] || (cmd-echo "Cannot find '$i'. --root cannot be used." && exit 1);
             done
             shift
             ;;
         gim )
             mapfile -t git_is_mod < <(git what is mod 2>/dev/null)
-            if [ -z "${git_is_mod[0]}" ]; then
+            if [[ -z "${git_is_mod[0]}" ]]; then
                 if ! git root 2>/dev/null 1>&2; then
                     cmd-echo -- "--gim not allowed; not in a git repo"
                 else
@@ -127,9 +127,9 @@ cutrange="${cutstart}-${cutend}"
 ## Assume X or some other windowing system is available and do the needful if
 ## not.
 hasX=1
-if [ "$forceX" = '1' ]; then
+if [[ "$forceX" = '1' ]]; then
     hasX=1
-elif [ ! "$OS" = 'Cygwin' ]; then
+elif [[ ! "$OS" = 'Cygwin' ]]; then
     if ! type -P xmodmap >/dev/null; then
         hasX=0
     else
@@ -164,10 +164,10 @@ fi
 
 ## If we are being used as the git editor or EDITOR, we don't want to start up
 ## such that the underlying process thinks we're done editing before we are.
-if [ "$1" = '--visual' ]; then
+if [[ "$1" = '--visual' ]]; then
     as_visual=1
     shift
-elif [ "$1" = '--nf' ] || [ "$1" = '-nf' ]; then
+elif [[ "$1" = '--nf' ]] || [[ "$1" = '-nf' ]]; then
     new_frame=1
     shift
 fi
