update to make move to subdir happen and not bring up a list if subdir matches multiple entries in list

diff --git a/bin/cdfuncs b/bin/cdfuncs
--- a/bin/cdfuncs
+++ b/bin/cdfuncs
@@ -319,57 +319,66 @@ dirlist ()
             fi
         else
             local tgt=$1;shift
-	        is_int $tgt
-	        if (( $? == 0 ))
-	        then
-	            is_neg $tgt
-	            if (( $? == 0 ))
-	            then
-                    ## --------------------
-                    ## Negative integer arg
-                    ## --------------------
-                    ## Argument was a negative number. If you are in /a/b/c/d/e and
-                    ## you cd -2, you end up in /a/b/c.
-		            local i=$tgt
-                    local tgtdir=$(pwd)
-		            while (( i < 0 ))
-		            do
-		                tgtdir=$(dirname $tgtdir)
-		                (( i=i+1 ))
-		            done
-		            builtin cd $tgtdir
-                else
-                    ## --------------------
-                    ## Positive integer arg
-                    ## --------------------
-                    ## Argument was a positive number. If you haven't changed your
-                    ## stack and you remember your number from the select menu,
-                    ## just go there.
-	                local DIRLISTA=($DIRLIST)
-                    if ((tgt>${#DIRLISTA[@]})) || ((tgt==0))
-                    then
-                        stderrcho $tgt is not a valid choice
-                    else
-                        local d=$(echo ${DIRLISTA[(tgt-1)]} |
-                                  sed "s|$DIRLIST_PWD_INDIC||" |
-                                  sed "s|~|${HOME}|")
-                        builtin cd $d
-	                fi
-	            fi
-            elif [ -d $tgt ] || [ "$tgt" = '-' ]
+            ## Simplest case - the arg is a directory we can reach or prior
+            ## directory syntax.
+            if [ -d $tgt ] || [ "$tgt" = '-' ]
             then
                 builtin cd $tgt
             else
-                local FILTERED_DIRLIST=$(echo $DIRLIST | tr ' ' '\n' | grep $tgt )
-                if [ -n "$FILTERED_DIRLIST" ]
-                then
-                    _dirlist_select $FILTERED_DIRLIST
+                is_int $tgt
+	            if (( $? == 0 ))
+	            then
+	                is_neg $tgt
+	                if (( $? == 0 ))
+	                then
+                        ## --------------------
+                        ## Negative integer arg
+                        ## --------------------
+                        ## Argument was a negative number. If you are in /a/b/c/d/e and
+                        ## you cd -2, you end up in /a/b/c.
+		                local i=$tgt
+                        local tgtdir=$(pwd)
+		                while (( i < 0 ))
+		                do
+		                    tgtdir=$(dirname $tgtdir)
+		                    (( i=i+1 ))
+		                done
+		                builtin cd $tgtdir
+                    else
+                        ## --------------------
+                        ## Positive integer arg
+                        ## --------------------
+                        ## Argument was a positive number. If you haven't changed your
+                        ## stack and you remember your number from the select menu,
+                        ## just go there.
+	                    local DIRLISTA=($DIRLIST)
+                        if ((tgt>${#DIRLISTA[@]})) || ((tgt==0))
+                        then
+                            stderrcho $tgt is not a valid choice
+                        else
+                            local d=$(echo ${DIRLISTA[(tgt-1)]} |
+                                             sed "s|$DIRLIST_PWD_INDIC||" |
+                                             sed "s|~|${HOME}|")
+                            builtin cd $d
+	                    fi
+	                fi
                 else
-                    echo "$tgt not found"
+                    ## Arg is a partial completion. Filter the list. If your
+                    ## filter matches a reachable directory, it will be handled
+                    ## above. If that's not what you want, too bad; you'll have
+                    ## to use a plain dirlist call and hunt.
+                    local FILTERED_DIRLIST=$(echo $DIRLIST | tr ' ' '\n' | grep $tgt )
+                    if [ -n "$FILTERED_DIRLIST" ]
+                    then
+                        _dirlist_select $FILTERED_DIRLIST
+                    else
+                        echo "$tgt not found"
+                    fi
                 fi
             fi
         fi
     fi
+
     setdirlist $target
 }
 export -f dirlist
