Periodic. Lots of option processing changes.
bin/_git-go-get
o Explained --limited option.
o Raw options replaced with getopt.

bin/cmd-echo
o Raw options replaced with getopt.
o Missed an option in the conversion.

bin/color-echo
o Raw options replaced with getopt.

bin/cp
o Rework to allow multiple sources for --mirror.

bin/ec
o Shellchecked.
o Fix for multi-file handling.

bin/env-no-func
o Print env/set output without functions.

bin/func-to-exec.pl
o Update getopt swap.

bin/git
o Shellchecked.
o Updated docs on calling real command for over-extended command.

bin/git-branch
o Converted to getopt.

bin/git-check-with-remote
o getoptp replaced with getopt.
o No longer using func-name-spoof.

bin/git-clone
o Raw options replaced with simple dispatch.
o Added gitgo instructions when aborting cloning over an existing clone.

bin/git-comment
o Raw options replaced with getopt.

bin/git-commit
o Added a message option 'mjira'.

bin/git-log-shas-range
o getoptp replaced with getopt.

bin/git-mono
o Added --rp and --repopatt to handle repo pattern matching. -r and
  --repo repurposed to exact repo matches.

bin/git-push
o Print if creating or using existing PR in the popup.
o Raw options replaced with simple dispatch.

bin/git-rebase
o Wraps git rebase, adds -[i]log.

bin/git-status-ext
o Add print of any comments.

bin/git-status-with-source-ctrl-log
o Raw options replaced with getopt.

bin/git-sync-with-remote
o Update for options handling.

bin/git-worktree
git-worktree-delete():
  o getoptp replaced with getopt.

git-worktree-get-root():
  o git worktree list parsing was off.

git-worktree-ina():
  o Now checks for the presence of a .git FILE to determines if we are in a
    worktree, which is different that an a working tree, which is the
    opposite of a bare repo.

bin/github-api
o Document weird api paging issue.

bin/logit
o getoptp replaced by getopt.

bin/sedinplace
o getoptp replaced by getopt.

bin/withzenity
o Raw options replaced with getopt.

bin/xterm_Xground
o No longer using func-name-spoof.

functions/ashift
ashift():
  o Added -q for quiet in case you just want the shift and not the shifted
    value.

functions/dirlist
o getoptp replaced with getopt.

functions/git-checkout
o getoptp replaced with getopt.

functions/git-go
o Raw options replaced with getopt.
o Replace "arg 2 is a number" with -i to simplify filter handling.
  Removed unused --limited option.
o Added --comma for --list processing.

diff --git a/bin/cmd-echo b/bin/cmd-echo
--- a/bin/cmd-echo
+++ b/bin/cmd-echo
@@ -7,7 +7,6 @@
 # shellcheck disable=SC2154
 declare reset_normal="${ANSI_reset}"
 declare reset_title=''
-declare moreopts=1
 declare nonl=''
 declare continueline=0
 declare head=0
@@ -20,29 +19,32 @@ declare opt_color=0
 declare -A colors
 colors=([WARNING]=${ANSI_BG_orange}
         [ERROR]=${ANSI_BG_red})
-
-declare msg_status
-msg_status=''
+declare msg_status=''
 declare interactive=1
 [ ! -t 1 ] && interactive=0
-while [[ "$1" =~ ^- ]] && ((moreopts))
-do
-    declare original="$1"
-    shift
-    declare option
-    option=$(dashstripper "$original")
-    ## This bit deals with --foo=bar instead of --foo bar
-    declare okey=''
-    declare ovalue=''
-    if [[ "$option" =~ = ]]
-    then
-        okey=${option%%=*}
-        ovalue=${option#*=}
-        option="$okey"
-    fi
 
-    case $option in
-        head ) head=1 ;;
+# Read the options and args from command line. Note that the long and short
+# don't have to match up.
+declare OPTSARGS
+declare shortopts='inachfsojwep::'
+declare longopts='head,title,id:,help,wc,ec,color,oii'
+OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "$(basename "$0")" -- "$@") ## "${FUNCNAME[0]}" -- "$@") for functions
+declare status=$?
+((status != 0)) && exit $status ## return $status ## in functions
+
+# Reset the command line ($@).
+eval set -- "$OPTSARGS"
+
+# Reprocess the command line, extracting options and their arguments into
+# variables.
+while true
+do
+    declare option=$1
+    shift
+    [ "$option" != '--' ] && option=${option##-} && option=${option##-}
+    case "$option" in
+        head )
+            head=1 ;;
         title )
             head=1
             title=1
@@ -51,43 +53,42 @@ do
             ;;
         id )
             # shellcheck disable=SC2034 # id is referenced indirectly below:
-            ##     for i in "id" "msg_status"
-            id=${ovalue:-$1}
-            [ -z "$ovalue" ] && shift
-            ;;
-        i ) interactive=1 ;;
-        n ) nonl='-n' ;;
-        a ) append=1 ;;
-        c ) continueline=1 ;;
-        h | help ) script-usage cmd-echo && exit 0;;
+            ##                               for i in "id" "msg_status"
+            id="$1"; shift ;;
+        i )
+            interactive=1 ;;
+        n )
+            nonl='-n' ;;
+        a )
+            append=1 ;;
+        c )
+            continueline=1 ;;
+        h | help )
+            script-usage cmd-echo && exit 0;;
         f | s | o )
-            echo "-f, -s and -o are no longer used. Ignored..."
-            ;;
-        j ) join=1 ;;
+            echo "cmd-echo: -f, -s and -o are no longer used. Ignored..." ;;
+        j )
+            join=1 ;;
         wc )
             opt_color=1
             ;&
-        w ) msg_status='WARNING'
-            ;;
+        w )
+            msg_status='WARNING' ;;
         ec )
             opt_color=1
             ;&
-        e ) msg_status='ERROR'
-            ;;
+        e )
+            msg_status='ERROR' ;;
         color )
-            ;;
-        oii | \
-            only-if-interactive )
-            ((interactive==0)) && exit 0
-            ;;
+            echo "cmd-echo: --color is no longer used. Ignored..." ;;
+        oii | only-if-interactive )
+            ((interactive==0)) && exit 0 ;;
         p )
-            prefix=${ovalue:-$1}
-            [ -z "$ovalue" ] && shift
-            ;;
-        --)
-            moreopts=0 ;;
-        -* )
-            echo "cmd-echo: '$original' is an invalid option."
+            prefix=$1; shift ;;
+        -- ) break ;; ## ## VITAL!!! Exits the while loop, no more options,
+                      ## remaining $*, if any, are args
+        * )
+            echo "cmd-echo: '$option' is an invalid option."
             exit 1
             ;;
     esac
diff --git a/bin/git-check-with-remote b/bin/git-check-with-remote
--- a/bin/git-check-with-remote
+++ b/bin/git-check-with-remote
@@ -5,26 +5,37 @@
 # shellcheck disable=SC1090
 source "$BASH_INC_DIR/on_exit.binc"
 
-declare iam
-iam=$(func-name-spoof)
-
 declare opt_branch=''
 declare opt_remote='origin'
 declare opt_bail_on_dirty='0'
 declare OPTSARGS
-OPTSARGS=$(getoptp -o hb:r:c --long help,branch:,remote:,bail_on_dirty -n "$iam" -- "$@")
-status=$?
-((status != 0)) && exit $status
+declare shortopts='hb:r:c'
+declare longopts='help,branch:,remote:,bail_on_dirty'
+
+OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "$(basename "$0")" -- "$@")
+declare status=$?
+((status != 0)) && exit $status ## return $status ## in functions
+
+# Reset the command line ($@).
 eval set -- "$OPTSARGS"
+
+# Reprocess the command line, extracting options and their arguments into
+# variables.
 while true
 do
-    case "$1" in
-        --bail_on_dirty) opt_bail_on_dirty=1; shift;;
-        -r|--remote) opt_remote="$2"; shift; shift ;;
-        -b|--branch) opt_branch="$2"; shift; shift ;;
+    declare option=$1
+    shift
+    case "$option" in
+        --bail_on_dirty) opt_bail_on_dirty=1 ;;
+        -r|--remote) opt_remote="$1"; shift ;;
+        -b|--branch) opt_branch="$1"; shift ;;
         -h|--help) script-usage "$0"; exit 0 ;;
-        --) shift; break ;; ## end of opts, remaining $*, if any, are args
-        *) cmd-echo "Internal error!"; script-usage "$0"; exit 1 ;;
+        --) break ;; ## VITAL!!! Exits the while loop, no more options,
+                     ## remaining $*, if any, are args
+        *)
+            cmd-echo -e -- "$option is an invalid option. See $0 --help"
+            exit 1 ## return 1 in functions
+            ;;
     esac
 done
 
@@ -45,11 +56,11 @@ then
     # shellcheck disable=SC2154
     cat <<EOF
 
-$iam is used to check your current git repo DEVELOPMENT branch in your declare
-clone against changes in
+You are trying to check your current git repo DEVELOPMENT branch in your clone
+against changes in
 
 branch "${opt_branch}"
-  repo   "${opt_remote}" (${gitfuncs_remotes[$opt_remote]})
+  repo "${opt_remote}" (${gitfuncs_remotes[$opt_remote]})
 
 However, you do not appear to even be in a repo. I'm exiting. Try again in a
 proper repo.
@@ -62,11 +73,11 @@ if [ "$cb" == "$opt_branch" ]
 then
     cat <<EOF
 
-$iam is used to check your current git repo DEVELOPMENT branch in your declare
-clone against changes in
+You are trying to check your current git repo DEVELOPMENT branch in your clone
+against changes in
 
 branch "${opt_branch}"
-repo   "${opt_remote}" (${gitfuncs_remotes[$opt_remote]})
+  repo "${opt_remote}" (${gitfuncs_remotes[$opt_remote]})
 
 However, you appear to be on branch "${opt_branch}", the branch you want to
 sync with. I'm exiting. Get off the branch "${opt_branch}" and onto another
diff --git a/bin/git-comment b/bin/git-comment
--- a/bin/git-comment
+++ b/bin/git-comment
@@ -20,76 +20,75 @@ usage ()
 
 main ()
 {
-    local commentdate
-    commentdate="$(date "$GIT_EXT_META_DATE_FMT") - "
-
     declare -a orig_args
     orig_args=("$@")
 
     ## If there's any chance that this will be in a script that will be dotted in,
     ## remove the explicit out_cmd calls.
-    declare out_cmd="exit"
-    declare moreopts=1
     declare opt_show=0
     declare opt_highest_only=0
     declare opt_verbose=1
     declare opt_delete=0
+    declare opt_date=1
 
     declare -A keys
     keys[repo]='core.em.em-comment'
-    local branchname
+    declare branchname
     branchname="$(git branch get-current)"
     keys[branch]="branch.$branchname.em-comment"
-    local worktreename
+    declare worktreename
     worktreename="$(basename "$(pwd)")"
     keys[worktree]="worktree.$worktreename.em-comment"
 
     declare -A write_keys
-    while [[ "$1" =~ ^- ]] && ((moreopts))
+
+    # Read the options and args from command line. Note that the long and short
+    # don't have to match up.
+    declare OPTSARGS
+    declare shortopts='rbwdhvq'
+    declare longopts='repo,branch,worktree,highest,nodate,date,show,get,delete,help,verbose,quiet'
+
+    # Process the command line.
+    OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "$(basename "$0")" -- "$@")
+    declare status=$?
+    ((status != 0)) && exit $status ## return $status ## in functions
+
+    # Reset the command line ($@).
+    eval set -- "$OPTSARGS"
+
+    # Reprocess the command line, extracting options and their arguments into
+    # variables.
+    while true
     do
-        declare original="$1"
+        declare option=$1
         shift
-        declare option
-        option=$(dashstripper "$original")
-        ## This bit deals with --foo=bar instead of --foo bar
-        declare okey=''
-        declare ovalue=''
-        if [[ "$option" =~ = ]]
-        then
-            okey=${option%%=*}
-            # shellcheck disable=SC2034 # Remove this directive if we ever have
-            # an option with a value
-            ovalue=${option#*=}
-            option="$okey"
-        fi
-
-        case $option in
-
+        [ "$option" != '--' ] && option=${option##-} && option=${option##-}
+        case "$option" in
             ## Option with no arg
-            r* )
+            r | repo )
                 write_keys[repo]=1
                 ;;
-            b* )
+            b | branch )
                 write_keys[branch]=1
                 ;;
-            w* )
+            w | worktree )
                 write_keys[worktree]=1
                 ;;
-            hi* )
+            highest )
                 opt_highest_only=1
                 ;;
-            nod* )
-                commentdate=''
+            nodate )
+                opt_date=0
                 ;;
-
+            date )
+                opt_date=1
+                ;;
             show | get )
                 opt_show=1
                 ;;
-
-            d* )
+            d | delete )
                 opt_delete=1
                 ;;
-
             ## standard options
             h | help )
                 script-usage
@@ -101,20 +100,23 @@ main ()
             q | quiet )
                 opt_verbose=0
                 ;;
-            --)
-                moreopts=0
-                ;;
-            * )
-                cmd-echo -- "$original is an invalid option. See $0 --help"
-                $out_cmd 1
+            --)  break ;; ## VITAL!!! Exits the while loop, no more options,
+                          ## remaining $*, if any, are args
+            *)
+                cmd-echo -e -- "$option is an invalid option. See $0 --help"
+                return 1
                 ;;
         esac
     done
+
+    declare commentdate
+    ((opt_date)) && commentdate="$(date "$GIT_EXT_META_DATE_FMT") - "
 
     if [[ ${#write_keys[*]} = '0' ]]
     then
         if ((opt_show)) || ( (( $# == 0 )) && ((! opt_delete)) )
         then
+            ## With no args, no options, just show all keys.
             exec git-comment -r -b -w --show "${orig_args[@]}"
         else
             cmd-echo -n -- "Need at least one of --repo, --branch, --worktree to determine which comment to "
@@ -140,7 +142,7 @@ main ()
     do
         if [[ ${write_keys[$configtype]} = '1' ]]
         then
-            local configkey=${keys[$configtype]}
+            declare configkey=${keys[$configtype]}
             if ((opt_show))
             then
                 value="$(git config --get "$configkey")"
@@ -179,7 +181,6 @@ main ()
 }
 
 main "$@"
-set +x
 exit $?
 
 :<<'__PODUSAGE__'
diff --git a/bin/git-log-shas-range b/bin/git-log-shas-range
--- a/bin/git-log-shas-range
+++ b/bin/git-log-shas-range
@@ -10,22 +10,34 @@ opt_inclusive=1
 declare opt_add_names
 opt_add_names=''
 declare OPTSARGS
-OPTSARGS=$(getoptp -o f:ienh --long highlightfirst:,inclusive,exclusive,name-only,help -n "${FUNCNAME[0]}" -- "$@")
-declare status
-status=$?
+declare shortopts='f:ienh'
+declare longopts='highlightfirst:,inclusive,exclusive,name-only,help'
+
+OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "${FUNCNAME[0]}" -- "$@")
+declare status=$?
 ((status != 0)) && script-usage && exit $status
 
+# Reset the command line ($@).
 eval set -- "$OPTSARGS"
+
+# Reprocess the command line, extracting options and their arguments into
+# variables.
 while true
 do
-    case "$1" in
-        -f|--higlightfirst)  opt_inclusive=1; opt_hf="$2"; shift; shift ;;
-        -i|--inclusive) opt_inclusive=1; shift ;;
-        -e|--exclusive) opt_inclusive=0; shift ;;
-        -n|--name-only) opt_add_names='--name-only'; shift ;;
+    declare option=$1
+    shift
+    case "$option" in
+        -f|--higlightfirst)  opt_inclusive=1; opt_hf="$1"; shift ;;
+        -i|--inclusive) opt_inclusive=1 ;;
+        -e|--exclusive) opt_inclusive=0 ;;
+        -n|--name-only) opt_add_names='--name-only' ;;
         -h|--help) script-usage; exit 0 ;;
-        --) shift; break ;; ## end of opts, remaining $*, if any, are args
-        *) echo "Internal error!"; script-usage; exit 1 ;;
+        --) break ;; ## VITAL!!! Exits the while loop, no more options,
+                     ## remaining $*, if any, are args
+        *)
+            cmd-echo -e -- "$option is an invalid option. See $0 --help"
+            exit 1 ## return 1 in functions
+            ;;
     esac
 done
 
@@ -49,7 +61,7 @@ git-log-shas-range - script that does something
 
 =head1 SYNOPSIS
 
- git-log-shas-range [--option1] [ --option2 optionarg ] arg1 [arg2 ...] 
+ git-log-shas-range [--option1] [ --option2 optionarg ] arg1 [arg2 ...]
      [fee] [dfsdfs] [sfsdfsf]
 
 =head1 DESCRIPTION
@@ -95,4 +107,3 @@ Another choice for optionarg
 =cut
 
 __PODUSAGE__
-
diff --git a/functions/git-go b/functions/git-go
--- a/functions/git-go
+++ b/functions/git-go
@@ -8,32 +8,48 @@ git-go ()
     # shellcheck disable=SC1090
     source "$BASH_INC_DIR/on_exit.binc"
 
-    local PS3="Choose by number, /string to rematch, q to quit: "
-    local -a git_get_opts
-    local opt_list=0
-    local opt_wt='-w'
-    local opt_subwt_only=''
-    local opt_stat=0
-    local opt_mod=0
-    local opt_exact=''
-    local opt_size=0
-    local opt_brief=0
-    local opt_comments=0
-    local moreopts
-    local -a limited
-    local -a tgts
-    moreopts=1
-    while [[ "$1" =~ ^- ]] && ((moreopts))
+    declare PS3="Choose by number, /string to rematch, q to quit: "
+    declare -a git_get_opts
+    declare opt_list=0
+    declare opt_wt='-w'
+    declare opt_subwt_only=''
+    declare opt_stat=0
+    declare opt_mod=0
+    declare opt_exact=''
+    declare opt_size=0
+    declare opt_brief=0
+    declare opt_comments=0
+    declare opt_repo_no=0
+    declare opt_comma=0
+    declare -a limited
+    declare -a tgts
+
+    # Read the options and args from command line. Note that the long and short
+    # don't have to match up.
+    declare OPTSARGS
+    declare shortopts='elmrubhi:'
+    declare longopts='upstream,exact,et,exact-tail,eh,exact-head'
+    longopts="$longopts,wc,with-comments,wco,with-comments-only"
+    longopts="$longopts,list,lf,listfull,size,mbig,roots,update"
+    longopts="$longopts,wt,nowt,subwt,wto"
+    longopts="$longopts,stat,dirty,brief,mod,help,index:,limited:,comma"
+
+    # Process the command line.
+    OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "${FUNCNAME[0]}" -- "$@")
+    declare status=$?
+    ((status != 0)) && return $status ## return $status ## in functions
+
+    # Reset the command line ($@).
+    eval set -- "$OPTSARGS"
+
+    # Reprocess the command line, extracting options and their arguments into
+    # variables.
+    while true
     do
-        ## Strip all leading dashes here so that -foo and --foo can both
-        ## be processed as 'foo'.
-        declare original="$1"
-        declare option
-
-        option=$(dashstripper "$original")
-        shift ## That way you avoid endless loops on invalid options.
-
-        case $option in
+        declare option=$1
+        shift
+        [ "$option" != '--' ] && option=${option##-} && option=${option##-}
+        case "$option" in
             upstream) eval "$(git-parse-remote-v)"
                       # shellcheck disable=SC2154
                       if [ -z "${gitfuncs_remotes[upstream]}" ]
@@ -46,11 +62,11 @@ git-go ()
             e | exact ) opt_exact='--exact';;
             et | exact-tail ) opt_exact='--exact-tail';;
             eh | exact-head ) opt_exact='--exact-head';;
+            wc | with-comments ) opt_comments=1; opt_list=1 ;;
+            wco | with-comments-only ) opt_comments=2; opt_list=1 ;;
             l | list ) opt_list=1 ;;
-            comment-o* | with-comment-o* \
-                | comments-o* | with-comments-o*) opt_comments=2 ;;
-            comment* | with-comment*) opt_comments=1 ;;
-            listfull ) opt_list=2 ;;
+            lf | listfull ) opt_list=2 ;;
+            comma ) opt_comma=1 ;;
             size ) opt_size=1; opt_list=1 ;;
             m | mbig ) git_get_opts+=('-m') ;;
             r | roots ) git_get_opts+=('-r') ;;
@@ -58,21 +74,25 @@ git-go ()
             wt ) opt_wt='-w' ;;
             nowt ) opt_wt='' ;;
             subwt ) opt_subwt_only='-o' ;;
-            wto* ) opt_subwt_only='-o' ;;
+            wto ) opt_subwt_only='-o' ;;
             stat ) opt_stat=1; opt_list=1 ;;
             dirty ) opt_stat=2; opt_list=1 ;;
             b| brief ) opt_brief=1 ;;
             mod ) opt_mod=1;;
+            i | index ) opt_repo_no=$1; shift ;;
             limited ) limited=('--limited' "$1"); shift ;;
             h | help ) func-usage git-go; return 0 ;;
-            -- ) moreopts=0; break ;; ## end of opts, remaining $*, if any, are args
-            * ) echo "$original is an invalid option."; func-usage git-go; return 1 ;;
+            --) break ;; ## VITAL!!! Exits the while loop, no more options,
+                         ## remaining $*, if any, are args
+            *)
+                cmd-echo -e -- "$option is an invalid option. See $0 --help"
+                return 1
+                ;;
         esac
     done
-
     if ((opt_stat!=2)) && ((opt_brief))
     then
-        cmd-echo -- "Cannot specify --brief without --dirty"
+        cmd-echo -e -- "Cannot specify --brief without --dirty"
         func-usage git-go; return 1
     fi
 
@@ -80,61 +100,52 @@ git-go ()
     [ -n "$opt_subwt_only" ] && git_get_opts+=("$opt_subwt_only");
     [ -n "$opt_exact" ] && git_get_opts+=("$opt_exact")
 
-    ## Grab the first argument which has to be blank or a filter
-    if [ -n "$1" ]
-    then
-        tgts+=("$1")
-        shift;
-    fi
+    declare -a REPOS
+    declare -a origtgts
 
-    ## Grab the second argument. If it is a number, it is an index to the list
-    ## returned after applying the first filter. If not then it, and any other
-    ## arguments after it, are more filters. The reasoning is that with one
-    ## filter you might remember the derived number of your desired item, but
-    ## with multiple filters, you don't save time remembering a number if you
-    ## have to multiple filters or sit on the up arrow to recall the command.
-    local opt_repo_no=0
-    local opt_repo_sel=''
-    if [ -n "$1" ]
-    then
-        if is-int "$1"
-        then
-            opt_repo_no=$1
-            shift
-        else
-            tgts+=("$@")
-        fi
-    fi
-
-    declare tgtilast
-    tgtilast=$((${#tgts[@]}-1 ))
-    for i in $(seq 0 $tgtilast )
+    ## Grab all arguments; these are filters. We let the code drop through if
+    ## there are no arguments instead of bypassing with an explicit check for
+    ## arguments in order not to complicate the interplay with --limited.
+    for tgt in "$@"
     do
-        if [[ "${tgts[$i]}" =~ /$ ]]
-        then
-            tgts[$i]="$(dirname "${tgts[$i]}")/$(basename "${tgts[$i]}")"
-        fi
+        ## Strip trailing slashes. Not sure why we need to do this.
+        tgts+=("${tgt%%/}")
     done
-    local -a origtgts
     origtgts=("${tgts[@]}")
 
-    local -a REPOS
+    ## First call has no REPOS to feed back and may be using a --limited
+    ## option. Do it separately.
     if ((${#limited[@]}))
     then
         git_get_opts=()
     fi
     readarray -t REPOS < <(_git-go-get "${git_get_opts[@]}" "${limited[@]}" "${tgts[0]}")
+
+    ## Shift off the first array member so we can iterate over the rest.
     tgts=("${tgts[@]:1}")
-    while((${#tgts[@]}))
+
+    ## The rest need the REPOS feedback.
+    for tgt in "${tgts[@]}"
     do
-        # shellcheck disable=SC2046
-        readarray -t REPOS < <(_git-go-get --limited $(ajoin , $(tail_number_strip "${REPOS[@]}")) "${tgts[0]}")
-    tgts=("${tgts[@]:1}")
+        readarray -t tns < <(tail_number_strip "${REPOS[@]}")
+        readarray -t REPOS < <(_git-go-get --limited "$(ajoin , "${tns[@]}")" "$tgt")
+        if ((${#REPOS[@]}==0))
+        then
+            break
+        fi
     done
 
     if ((${#REPOS[@]}==0))
     then
-        echo Filter "${origtgts[@]}" does not match any repo
+        if (( ${#origtgts[@]} == 0 ))
+        then
+            cmd-echo -e -- "No repos available."
+        elif (( ${#origtgts[@]} == 1 ))
+        then
+            cmd-echo -e -- "Filter '${origtgts[*]}' does not match any repo"
+        else
+            cmd-echo -e -- "Filters '$(ajoin , "${origtgts[@]}")' do not match any repo"
+        fi
         return 1
     else
         if ((opt_mod))
@@ -151,7 +162,7 @@ git-go ()
             done
         elif ((opt_list))
         then
-            local r
+            declare r
             if ((opt_size))
             then
                 ## Re-sort the list of repos by size descending using
@@ -172,7 +183,7 @@ git-go ()
                 then
                     du -hs --exclude wt "${r}"
                 else
-                    local rexp
+                    declare rexp
                     ((opt_list==1)) && rexp="~/${r}" || rexp="${TILDAE:-$HOME}/${r}"
 #                    if ((opt_stat==0))
 #                    then
@@ -181,13 +192,13 @@ git-go ()
                     if ((opt_stat==1))
                     then
                         echo "$rexp"
-                        (cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
+                        (cd "${TILDAE:-$HOME}/$r" || (cmd-echo -e -- "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
                          git status --porcelain)
                         echo
                     elif ((opt_stat==2))
                     then
                         (
-                            cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
+                            cd "${TILDAE:-$HOME}/$r" || (cmd-echo -e -- "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
                             if (( $(git status --porcelain | wc -l) ))
                             then
                                 echo "$rexp"
@@ -201,8 +212,8 @@ git-go ()
                     elif ((opt_comments))
                     then
                         (
-                            cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
-                            local output
+                            cd "${TILDAE:-$HOME}/$r" || (cmd-echo -e -- "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
+                            declare output
                             output="$(git comment --show --hi)"
                             if ((opt_comments==1)) || \
                                    ( ((opt_comments==2)) && [[ -n $output ]] )
@@ -212,22 +223,29 @@ git-go ()
                             [[ -n $output ]] && echo "    $output" && echo
                         )
                     else
-                        echo "$rexp"
+                        echo -n "$rexp"
+                        if ((opt_comma)) && [ "$r" != "${REPOS[-1]}" ] ## and not the last rexp
+                        then
+                            echo -n ,
+                        else
+                            echo
+                        fi
+
                     fi
                 fi
             done
             return
         elif ((${#REPOS[@]}==1))
         then
-            echo "Matches only ${REPOS[0]}. Going there."
+            cmd-echo -- "Matches only ${REPOS[0]}. Going there."
             REPO=${REPOS[0]}
         else
-            local REPO
+            declare REPO
 
             if ((opt_repo_no))
             then
-                local r
-                local ri=1
+                declare r
+                declare ri=1
                 for r in "${REPOS[@]}"
                 do
                     if ((ri==opt_repo_no))
@@ -237,22 +255,13 @@ git-go ()
                     fi
                     ((ri+=1))
                 done
-            elif [ -n "$opt_repo_sel" ]
-            then
-                local -a REPOSTMP
-                local r
-                for r in "${REPOS[@]}"
-                do
-                    [[ "$r" =~ $opt_repo_sel ]] && REPOSTMP+=("$r")
-                done
-                REPOS=("${REPOSTMP[@]}")
             fi
 
             if ((${#REPOS[@]}==1))
             then
                 ## Re-check singlematch condition in case we modified REPOS
                 ## above.
-                echo "Matches only ${REPOS[0]}. Going there."
+                cmd-echo -- "Matches only ${REPOS[0]}. Going there."
                 REPO=${REPOS[0]}
             else
                 readarray -t REPOS < <(tail_number_add "${REPOS[@]}")
@@ -278,7 +287,7 @@ git-go ()
                         git-go --limited $(ajoin , $(tail_number_strip "${REPOS[@]}")) "${REPLY#/}"
                         return $?
                     else
-                        echo "'$REPLY' is an invalid choice"
+                        cmd-echo -e -- "'$REPLY' is an invalid choice"
                     fi
                 done
             fi
@@ -295,23 +304,48 @@ git-go ()
 
 return 0 ## USAGE guard when sourcing
 :<<'__USAGE__'
-Usage: git-go [--list[full] [--size] [--stat|--dirty [--brief]] [--update|-u] \
-              [--roots|-r] [--mbig|-m] \
-              [--wt|--nowt|--wtonly ] [--mod] \
-              [ [dirmatch [item]] | [dirmatch...]
+Usage: git-go [options] [ filter [filter...] ]
+
+       git-go --upstream
 
        git-go [-h|--help]
 
        Presents a list of all git repos in ${TILDAE:-$HOME}/gits for you to
        choose and then cd to.
 
-       --list
+       Undocumented, yet:
+       --exact|--exact-head|--exact-tail
+
+       -i n | --item n
+           'n' is an integer which will pick the nth item in the
+           list of repos that would be presented if you didn't specify
+           '--item'. Useful if you are cycling between a small number of repos.
+
+       --upstream Determine the upstream repo of the current repo and if we
+           have a clone of it, go there. This is primarily used to get there
+           for a 'dpkg-debchange' call.
+
+       --wc|--with-comments
+           Print the repo and any comments on the repo.
+
+       --wco|--with-comments-only
+           Print only repos with comments on the repo and any comments on the repo.
+
+       --help
+           Print this help text.
+
+       --list|-l
            Skip the choosing part and just exit, printing each repo dir with a
            literal '~'.
 
-       --listfull
+       --listfull|--lf
            Skip the choosing part and just exit, printing each repo dir with
            '~' expanded.
+
+       --comma
+           Using any of the --list options, print the entries in one
+           comma-separated string instead of each entry on its own
+           line. Silently ignored if specified without a --list* option.
 
        --size
            Skip the choosing part and just exit, printing each repo dir with
@@ -348,19 +382,17 @@ Usage: git-go [--list[full] [--size] [--stat|--dirty [--brief]] [--update|-u] \
            Override the default and do not include the worktree subdirectories
            in repos as choices.
 
-       --wto[nly]
+       --wto
            Include only the worktrees as choices.
 
        --mod
            Show status of repos that have mods outstanding.
 
-       'dirmatch' will filter the list using grep.
+       'filter' will filter the list using grep.
 
-       'item' is an integer N which will pick the Nth item in the
-           list of repos that would be presented if you didn't specify
-           an 'item'. Useful if you are cycling between a small number of repos.
-
-       You can specify 'item' only after one 'dirmatch' filter. Otherwise you can specify
-       0 or more 'dirmatch' filters.
+       You can specify 'item' only after one 'dirmatch' filter. Otherwise you
+       can specify 0 or more 'dirmatch' filters. If the first 'dirmatch' filter
+       is a number (i.e., it looks like it could be an 'item'), prefix it with
+       a '/',
 
 __USAGE__
