func to exec, convert phase

diff --git a/bin/color-echo b/bin/color-echo
--- a/bin/color-echo
+++ b/bin/color-echo
@@ -1,107 +1,119 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2154 # shuts up all the complaints about the $ANSI_ variables.
 
-# <Function Class: util>
+# color-echo
 
-color-echo ()
-{
-    declare nonl=''
-    declare fgname=''
-    declare fgcolor=''
-    declare bgname=''
-    declare bgcolor=''
-    declare blink=''
-    declare bold=''
-    declare concealed=''
-    declare reset="$ANSI_reset"
-    declare reverse=''
-    declare underscore=''
-    declare moreopts=1
+declare nonl
+nonl=''
+declare fgname
+fgname=''
+declare fgcolor
+fgcolor=''
+declare bgname
+bgname=''
+declare bgcolor
+bgcolor=''
+declare blink
+blink=''
+declare bold
+bold=''
+declare concealed
+concealed=''
+declare reset
+reset="$ANSI_reset"
+declare reverse
+reverse=''
+declare underscore
+underscore=''
+declare moreopts
+moreopts=1
 
-    while [[ "$1" =~ ^- ]] && ((moreopts))
-    do
-        declare original="$1"
-        shift
-        declare option
-        option=$(dashstripper "$original")
-        ## This bit deals with --foo=bar instead of --foo bar
-        declare okey=''
-        declare ovalue=''
-        if [[ "$option" =~ = ]]
-        then
-            okey=${option%%=*}
-            ovalue=${option#*=}
-            option="$okey"
-        fi
-
-        case $option in
-            n)
-                nonl='-n' ;;
-            nr)
-                reset='' ;;
-            fg)
-                fgname="ANSI_FG_${ovalue:-$1}"
-                [ -z "$ovalue" ] && shift
-                ;;
-            black | blue | cyan | green | magenta | red | white | yellow )
-                fgname="ANSI_FG_${option}"
-                ;;
-            bg)
-                bgname="ANSI_BG_${ovalue:-$1}"
-                [ -z "$ovalue" ] && shift
-                ;;
-            bl | blink)
-                blink="$ANSI_blink" ;;
-            bo | bold)
-                bold="$ANSI_bold" ;;
-            con | concealed | \
-                hid | hidden )
-                concealed="$ANSI_concealed" ;;
-            rev | reverse )
-                reverse="$ANSI_reverse" ;;
-            under | underscore )
-                underscore="$ANSI_underscore" ;;
-            h | help )
-                func-usage
-                return 0
-                ;;
-            --)
-                moreopts=0
-                ;;
-            * )
-                cmd-echo -- "$original is an invalid option. See $0 --help"
-                return 1
-                ;;
-        esac
-    done
-
-    ## Check the colors
-    if [ -n "$fgname" ]
+while [[ "$1" =~ ^- ]] && ((moreopts))
+do
+    declare original
+    original="$1"
+    shift
+    declare option
+    option=$(dashstripper "$original")
+    ## This bit deals with --foo=bar instead of --foo bar
+    declare okey
+    okey=''
+    declare ovalue
+    ovalue=''
+    if [[ "$option" =~ = ]]
     then
-        fgcolor="${!fgname}"
-        if [ -z "$fgcolor" ]
-        then
-            cmd-echo "'$fgname' is not a valid foreground color"
-            func-usage
-            exit 1
-        fi
-    fi
-    if [ -n "$bgname" ]
-    then
-        bgcolor="${!bgname}"
-        if [ -z "$bgcolor" ]
-        then
-            cmd-echo "'$bgname' is not a valid background color"
-            func-usage
-            exit 1
-        fi
+        okey=${option%%=*}
+        ovalue=${option#*=}
+        option="$okey"
     fi
 
-    ## print
-    echo $nonl -e "$blink$bold$concealed$reverse$underscore$fgcolor$bgcolor$*$reset"
-}
+    case $option in
+        n)
+            nonl='-n' ;;
+        nr)
+            reset='' ;;
+        fg)
+            fgname="ANSI_FG_${ovalue:-$1}"
+            [ -z "$ovalue" ] && shift
+            ;;
+        black | blue | cyan | green | magenta | red | white | yellow )
+            fgname="ANSI_FG_${option}"
+            ;;
+        bg)
+            bgname="ANSI_BG_${ovalue:-$1}"
+            [ -z "$ovalue" ] && shift
+            ;;
+        bl | blink)
+            blink="$ANSI_blink" ;;
+        bo | bold)
+            bold="$ANSI_bold" ;;
+        con | concealed | \
+            hid | hidden )
+            concealed="$ANSI_concealed" ;;
+        rev | reverse )
+            reverse="$ANSI_reverse" ;;
+        under | underscore )
+            underscore="$ANSI_underscore" ;;
+        h | help )
+            script-usage
+            exit 0
+            ;;
+        --)
+            moreopts=0
+            ;;
+        * )
+            cmd-echo -- "$original is an invalid option. See $0 --help"
+            exit 1
+            ;;
+    esac
+done
 
-return 0 ## usage guard when sourcing
+## Check the colors
+if [ -n "$fgname" ]
+then
+    fgcolor="${!fgname}"
+    if [ -z "$fgcolor" ]
+    then
+        cmd-echo "'$fgname' is not a valid foreground color"
+        script-usage
+        exit 1
+    fi
+fi
+if [ -n "$bgname" ]
+then
+    bgcolor="${!bgname}"
+    if [ -z "$bgcolor" ]
+    then
+        cmd-echo "'$bgname' is not a valid background color"
+        script-usage
+        exit 1
+    fi
+fi
+
+## print
+echo $nonl -e "$blink$bold$concealed$reverse$underscore$fgcolor$bgcolor$*$reset"
+
+exit 0 ## usage guard when sourcing
 
 :<<'__PODUSAGE__'
 =head1 NAME
@@ -110,17 +122,17 @@ color-echo - echo in color
 
 =head1 SYNOPSIS
 
-    color-echo \
-         [-n] \
-         [--nr ]\
-         [--bl[ink]] \
-         [--bo[ld]] \
-         [--con[cealed]|hid[den]] \
-         [--rev[erse]] \
-         [--under[score]] \
-         [--fg foregroundcolor] \
-         [--bg backgroundcolor] \
-         text to echo
+color-echo \
+     [-n] \
+     [--nr ]\
+     [--bl[ink]] \
+     [--bo[ld]] \
+     [--con[cealed]|hid[den]] \
+     [--rev[erse]] \
+     [--under[score]] \
+     [--fg foregroundcolor] \
+     [--bg backgroundcolor] \
+     text to echo
 
 =head1 DESCRIPTION
 
