Ip 1 70 18 131.dob1.bcpc.bloomberg.com (#175)
* bin/auditfuncs
auditfuncs_init():
  o Each audit function checks the xtrace setting (set -x) and skips
    printing audit info when tracing is on.

* added purpose blurb

* a bad idea

* bin/cdfuncs
o Fixed up safe_func_export calls.

* Periodic commit

bin/cdfuncs
DIRLIST_PWD_INDIC():
  o Had to export this to get a cron job to work. Strange...

bin/cron_wrapper
o Now takes options instead of positionals, --checkkinit will make sure
  kerberos is not expired before running command.
o Use get-next-descriptor to chose saving descriptors, not hard coded 6 &
  7.
o Add --keeplog option. Set MAILTO to the given --to, if any, so that the
  keeplog message is sent to the right place.

mailthelog():
  o Added non-zero exit as a type so that we can use non-zero exists and
    not have the word Issue come up in the subject.

bin/gitfuncs
o Now uses kvstore for environment hashes.
o Removed the branch 'close'ing code and references - never used.

_git-go-get():
  o Filter is now case insensitive.

git-fork-and-clone():
  o Now check for the threeway origin and upstream remote config entries
    and then DTRT.

bin/logit
o 'output' section renamed 'execution', added start time.
o Added --notimestamp option.

bin/utilfuncs
o Use controlfuncs_build instead of defining the edit and reload
  functions explicitly.
o Regrouped functions. Put the hash functions under the same restriction
  as the array functions.
o kvinit, kvread, kvwrite - new persistant key value functions, primarily
  to help out with passing bash arrays and hashes between processes.

add_bb():
  o Deleted. Obsolete.

get-next-descriptor():
  o Get the next free shell io descriptor number.

diff --git a/bin/cron_wrapper b/bin/cron_wrapper
--- a/bin/cron_wrapper
+++ b/bin/cron_wrapper
@@ -1,45 +1,79 @@
 #!/opt/bb/bin/bash
 ## Control when cron jobs mail output
 
-## Keeping it simple - all args are positional
+CW_bin=$(realpath $(dirname $0))
+OPTSARGS=$($CW_bin/getoptp --long mailtype:,to:,subject:,checkkinit,id:,x,keeplog -n $(basename $0) -- "$@")
+status=$?
+((status != 0)) && exit $status
 
-## mail type - If mon or tue, etc. then on-error other days, always on that day
-mail_type=$1; shift
-[ -z "$mail_type" ] && echo "Mail type required" && exit 1
-mail_type=$(echo $mail_type | tr '[A-Z]' '[a-z]')
+eval set -- "$OPTSARGS"
 
-## mail to - overrides MAILTO from crontab. "" to accept MAILTO
-mail_to=$1; shift
-[ -z "$mail_to" ] && mail_to=$MAILTO
+mailtype=''
+mailto=$MAILTO
+mailsubject=''
+checkkinit=0
+setx=0
+keeplog=0
 
-mail_subject=$1; shift
+while true
+do
+    ## Remeber to add new options to the getoptp call above, in addition to
+    ## adding them here.
+    case "$1" in
+        --x)
+            setx=1;
+            shift;;
+        --mailtype)
+            mailtype=$(echo "$2" | tr '[A-Z]' '[a-z]')
+            shift; shift;;
+        --to)
+            mailto="$2"
+            MAILTO=$mailto; export MAILTO
+            shift; shift;;
+        --keeplog)
+            keeplog=1; shift;;
+        --subject)
+            mailsubject="$2"
+            shift; shift;;
+        --checkkinit)
+            checkkinit=1
+            shift;;
+        --id ) shift; shift;; ## used so that there is something unique on the
+                              ## command line for email subjects if there's a
+                              ## hard die
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; exit 1;;
+    esac
+done
+
+[ -z "$mailtype" ] && echo "Mail type required" && exit 1
 
 dayofweek=$(date +%a | tr '[A-Z]' '[a-z]')
 args_ok=0
 while ((!args_ok))
 do
-    case $mail_type in
+    case $mailtype in
         never )
             args_ok=1
             break
             ;;
-        on-error | if-output | if-no-output | today | always )
-            [ -z "$mail_to" ] && echo "Need valid email" && exit 1
-            [ -z "$mail_subject" ] && echo "Need valid email subject" && exit 1
+        non-zero | on-error | if-output | if-no-output | today | always )
+            [ -z "$mailto" ] && echo "Need valid email" && exit 1
+            [ -z "$mailsubject" ] && echo "Need valid email subject" && exit 1
             args_ok=1
             break
             ;;
         $dayofweek )
-            mail_type=today
+            mailtype=today
             break
             ;;
         sun | mon | tue | wed | thu | fri | sat )
             ## We get here if the day in the mail type does not match today
-            mail_type=on-error
+            mailtype=on-error
             break
             ;;
         * )
-            echo "Invalid mail type $mail_type"
+            echo "Invalid mail type $mailtype"
             exit 1
             break
             ;;
@@ -62,42 +96,90 @@ done
 
 if ((!did_profile))
 then
+    echo 'ERROR - No profiles found before trying to run'
+    echo "$@"
+    echo
     cat $profilelog
-    echo "No profiles found. Whoops!"
     exit 42
 fi
 
-exec 6>&1         # Link file descriptor #6 with stdout, which saves stdout.
+if((checkkinit))
+then
+    klist -s
+    status=$?
+    if((status))
+    then
+        backoff="$(dirname $(realpath $0))/../data/cron_wrapper.kinit.$(echo $mailsubject | sed 's/ /_/g')"
+        if [ -e $backoff ]
+        then
+            was=$(cat $backoff)
+            now=$(date +%s)
+            if ((now-was<86399))
+            then
+                exit 0 ## Once a day email on a kerberos expiration
+            fi
+        fi
+        echo 'ERROR - kerberos ticket has expired before trying to run'
+        echo "$@"
+        echo
+        echo 'Expiration(s):'
+        klist | cut -d ' ' -f4,5 | sort -u | grep '/'
+        date +%s > $backoff
+        echo 'Now:'
+        date '+%m/%d/%y %H:%M:%S'
+        echo
+        echo 'This is a ONCE-A-DAY notification, regardless of cron schedule.'
+        exit $status
+    fi
+fi
+
+## We use 6 and 7 because 3 & 4 are usually used
+holdstdout=$(get-next-descriptor)
+eval "exec $holdstdout>&1"  # Link file descriptor with stdout, which saves stdout.
 exec 1>> $alllog  # Re-point stdout to the log.
 
-exec 7>&2         # Link file descriptor #7 with stdout, which saves stderr.
+holdstderr=$(get-next-descriptor)
+eval "exec $holdstderr>&2"  # Link file descriptor with stderr, which saves stderr.
 exec 2>> $alllog  # Re-point stderr to the log.
 
 ##
 ## Here is where the command gets executed
 ##
 status=0
+
+## We set up a trap here to make sure that if the command dies so hard that the
+## rest of this script does not run, we get something from the shunted output.
+trap "eval ""exec 1>&$holdstdout $holdstdout>&-""      # Restore stdout and close file descriptor.
+      eval ""exec 2>&$holdstderr $holdstderr>&-""      # Restore stderr and close file descriptor.
+      [ -f $profilelog ] && cat $profilelog
+      [ -f $alllog ]     && cat $alllog
+     " SIGTERM SIGINT SIGFPE SIGBUS
 "$@"
 status=$?
 
 # The restorations will cause any mail errors to be sent to you via the regular
 # cron error channels.
-exec 1>&6 6>&-      # Restore stdout and close file descriptor #6.
-exec 2>&7 7>&-      # Restore stderr and close file descriptor #7.
+eval "exec 1>&$holdstdout $holdstdout>&-"      # Restore stdout and close file descriptor.
+eval "exec 2>&$holdstderr $holdstderr>&-"      # Restore stderr and close file descriptor.
 
+((setx)) && set -x
 subsubject=''
-mailthelog=''
+mailthelog=0
 if ((status))
 then
-    if [ ! "$mail_type" = 'never' ]
+    if [ "$mailtype" = 'non-zero' ]
+    then
+        mailthelog=1
+        subsubject="Non-zero exit ($status)"
+    elif [ ! "$mailtype" = 'never' ]
     then
         mailthelog=1 ## We always grab the log if there is an issue.
         subsubject="Issue - Exit status: $status"
     fi
-elif [ ! "$mail_type" = 'on-error' ]
+elif [ ! "$mailtype" = 'on-error' ]
 then
     subsubject="Success"
-    if [ "$mail_type" = 'if-no-output' ]
+    if [ "$mailtype" = 'if-no-output' ]
     then
         mailthelog=$(cat $alllog | wc -l)
         if ((mailthelog==0))
@@ -105,30 +187,60 @@ then
             mailthelog=1
             subsubject='Issue - No output'
         fi
-    elif [ "$mail_type" = 'if-output' ]
+    elif [ "$mailtype" = 'if-output' ]
     then
         mailthelog=$(cat $alllog | wc -l)
-    elif [ "$mail_type" = 'today' ]
+    elif [ "$mailtype" = 'today' ]
     then
         mailthelog=1
         subsubject="Success, $(date +%A) check"
+    elif [ "$mailtype" = 'never' ] || [ "$mailtype" = 'non-zero' ]
+    then
+        mailthelog=0
+    elif [ "$mailtype" = 'always' ]
+    then
+        mailthelog=1
     else
-        ## mail_type is 'always'
+        subsubject="Success, but unknown mailtype $mailtype. Mailing the log."
         mailthelog=1
     fi
 fi
 
+exitstatus=0
+
 if ((mailthelog))
 then
-    ## If there is an error, we include the profile log.
-    mailx -s "$subsubject - $mail_subject" \
-          $mail_to \
-          <<EOM
+    if [ -n "$mailto" ]
+    then
+        mailx -s "$subsubject - $mailsubject" \
+              $mailto \
+              <<EOM
 $subsubject
 $( ((status)) && cat $profilelog;cat $alllog)
 EOM
+        exitstatus=0 ## we mailed off the error, if any
+        exit 0
+    else
+        cat <<EOM
+$subsubject
+$( ((status)) && cat $profilelog;cat $alllog)
+EOM
+        exitstatus=$status ## we need to force the mail of the log, to at least
+                           ## the cron owner.
+    fi
 fi
 
-\rm -f $alllog $profilelog
+if ((keeplog))
+then
+    ## Writing anything to stdout or stderr forces what is written to be
+    ## mailed. This will happen despite any settings to the contrary above. It
+    ## will also use the default MAILTO, unless you have specified --to, in
+    ## which case we override MAILTO with the argument of --to.
+    echo "--keeplog specified. Logs are"
+    echo "alllog - $alllog"
+    echo "profilelog - $profilelog"
+else
+    \rm -f $alllog $profilelog
+fi
 
-exit 0
+exit $exitstatus
diff --git a/bin/gitfuncs b/bin/gitfuncs
--- a/bin/gitfuncs
+++ b/bin/gitfuncs
@@ -25,17 +25,15 @@ gitfuncs_gitroot=${HOME}/gits; export gitfuncs_gitroot
 gitfuncs_githook_root=${HOME}/.git_template; export gitfuncs_githook_root
 gitfuncs_githook_dir=${HOME}/.git_template/hooks; export gitfuncs_githook_dir
 
-declare -A gitfuncs_gitsvcs
-gitfuncs_gitsvcs[github]='https://github.com/'
+kvstoreinit --exists-ok gitfuncs_gitsvcs
+kvputinit gitfuncs_gitsvcs github 'https://github.com/'
 
-## 'loc'ations's' outside of ~/gits to look for repos. We make this a hash even
-## though it's more naturally used as an array so that we do not erase any
-## assignments made in subsequent *funcs files.
-declare -A gitfuncs_gitlocs_extra
-gitfuncs_gitlocs_extra[personal]=${HOME}/personal
-gitfuncs_gitlocs_extra[emacsd]=${HOME}/.emacs.d
-gitfuncs_gitlocs_extra[emacsdtaps]=${HOME}/.emacs.d/taps/mpersico5
-gitfuncs_gitlocs_extra[examples]=${HOME}/examples
+## 'loc'ations's' outside of ~/gits to look for repos.
+kvstoreinit --exists-ok gitfuncs_gitlocs_extra
+kvputinit gitfuncs_gitlocs_extra personal   ${HOME}/personal
+kvputinit gitfuncs_gitlocs_extra emacsd     ${HOME}/.emacs.d
+kvputinit gitfuncs_gitlocs_extra emacsdtaps ${HOME}/.emacs.d/taps/mpersico5
+kvputinit gitfuncs_gitlocs_extra examples   ${HOME}/examples
 
 ## These will be checked on each login and any time gitfuncs-reload is
 ## run. However, they are only ever executed when logging into a system where
@@ -546,7 +544,7 @@ git-go-set ()
     ## We can use -maxdepth 3 to speed things up drastically because of the
     ## host/namespace/repo setup similarly for other git hosts.
     local finds
-    for d in ${gitfuncs_gitlocs_extra[@]} \
+    for d in $(kvgetvalues gitfuncs_gitlocs_extra) \
                  $repo_tops
     do
         [ -d $d ] && finds="$finds $d"
@@ -594,7 +592,7 @@ git-go-set ()
     ls ${HOME}/gits/.git-go* | grep -v $gitfuncs_git_go_file | xargs \rm -f
     if [ "$set_x" = '1' ]
     then
-        set +x
+        set +x ## set by envvar
     fi
 }
 safe_func_export git-go-set
@@ -671,7 +669,7 @@ _git-go-get ()
 
     if [ -n "$filter" ]
     then
-        cat $tmpfile | grep $filter > ${tmpfile}.001
+        cat $tmpfile | grep -i $filter > ${tmpfile}.001
         mv ${tmpfile}.001 ${tmpfile}
     fi
 
@@ -960,72 +958,6 @@ git-branch-rename ()
     git-rename-branch "$@"
 }
 safe_func_export git-branch-rename
-
-## I prefer not to delete branches. I'd rather rename them
-git-close-branch ()
-{
-    ##@@ none||none||git-close-branch||
-    gitfuncs_audit "$@"
-
-    local old_branch=$1
-    if [ -z "$old_branch" ]
-    then
-        local branchesa=($(git-branch-list --strip))
-        if [ ${#branchesa[@]} == '0' ]
-        then
-            echo "No branches found. Are you in a git repo?"
-            return
-        fi
-        local PS3="Choose by number, q to quit: "
-        local selected
-        COLUMNS=1 ## One character wide terminal, forces list to be one column.
-        select selected in ${branchesa[@]}
-        do
-            if [ -n "$selected" ]
-            then
-                old_branch=$selected
-                break
-            elif [ "$(echo $REPLY | tr '[A-Z]' '[a-z]')" = 'q' ]
-            then
-                return
-            else
-                echo "'$REPLY' is an invalid choice"
-            fi
-        done
-    fi
-
-    local new_branch=closed/$(date +%Y_%m_%d_%H_%M_%S)/$old_branch
-    git-rename-branch $old_branch $new_branch
-    status=$?
-    ((status != 0)) && return $status
-
-    ## Update with changed branches
-    git-go-set
-    return $?
-}
-safe_func_export git-close-branch
-
-git-branch-close ()
-{
-    git-close-branch "$@"
-}
-safe_func_export git-branch-close
-
-git-close-current-branch ()
-{
-    ##@@ none||none||git-close-current-branch||
-    gitfuncs_audit "$@"
-
-    git-close-branch $(git-get-current-branch)
-    return $?
-}
-safe_func_export git-close-current-branch
-
-git-branch-close-current ()
-{
-    git-close-current-branch "$@"
-}
-safe_func_export git-branch-close-current
 
 git-delete-branch ()
 {
@@ -2071,38 +2003,53 @@ git-fork-and-clone ()
 
     if [ -n "$master_exists" ]
     then
-        func-echo --head  "WARNING: UNTESTED. NO COMMANDS ONLY ECHOS!!!"
-        func-echo 'Dumping the origin master in favor of the upstream master.'
-        func-echo 'but check the configuration before trying the commands.'
-        func-echo 'The config may already be correct due to using "glow".'
-        func-echo 'It should look like:'
-        func-echo '[remote "upstream"]'
-        func-echo "        url = ${protocol}:${namespace}/${repo}"
-        func-echo '        fetch = +refs/heads/*:refs/remotes/upstream/*'
-        func-echo '        fetch = +refs/notes/*:refs/notes/*'
-        func-echo '[remote "origin"]'
-        func-echo "        url = ${protocol}:${USER}/${repo}"
-        func-echo '        fetch = +refs/heads/*:refs/remotes/origin/*'
-        func-echo '[remote]'
-        func-echo '        pushdefault = origin'
+        declare -A threeway_workflow
+        threeway_workflow[remote.upstream.url]="${protocol}:${namespace}/${repo}"
+        threeway_workflow[remote.upstream.fetch]='+refs/heads/*:refs/remotes/upstream/*'
+        threeway_workflow[remote.upstream.fetch]='+refs/notes/*:refs/notes/*'
+        threeway_workflow[remote.origin.url]="${protocol}:${USER}/${repo}"
+        threeway_workflow[remote.origin.fetch]='+refs/heads/*:refs/remotes/origin/*'
+        local key
+        local good=0
+        for key in ${!threeway_workflow[@]}
+        do
+            [ $(git config --get $key) = "${threeway_workflow[$key]}" ] && ((good+=1))
+        done
+        if ((good==5))
+        then
+            func-echo "It appears that the repo has been created using"
+            func-echo "threeway fork and clone workflow:"
+            for key in ${!threeway_workflow[@]}
+            do
+                echo "$key=${threeway_workflow[$key]}"
+            done
+        elif ((good==0))
+        then
+            func-echo --head  "WARNING: UNTESTED. NO COMMANDS ONLY ECHOS!!!"
+            func-echo 'Dumping the origin master in favor of the upstream master.'
 
-        func-echo git checkout -b temp
-        func-echo status=$?; [ "$status" != '0' ] && return $status
+            func-echo git checkout -b temp
+            func-echo status=$?; [ "$status" != '0' ] && return $status
 
-        func-echo git branch -d master
-        func-echo status=$?; [ "$status" != '0' ] && return $status
+            func-echo git branch -d master
+            func-echo status=$?; [ "$status" != '0' ] && return $status
 
-        func-echo git branch -r -d origin/master
-        func-echo status=$?; [ "$status" != '0' ] && return $status
+            func-echo git branch -r -d origin/master
+            func-echo status=$?; [ "$status" != '0' ] && return $status
 
-        func-echo git checkout --track upstream/master
-        func-echo status=$?; [ "$status" != '0' ] && return $status
+            func-echo git checkout --track upstream/master
+            func-echo status=$?; [ "$status" != '0' ] && return $status
 
-        func-echo git checkout master
-        func-echo status=$?; [ "$status" != '0' ] && return $status
+            func-echo git checkout master
+            func-echo status=$?; [ "$status" != '0' ] && return $status
 
-        func-echo git branch -d temp
-        func-echo status=$?; [ "$status" != '0' ] && return $status
+            func-echo git branch -d temp
+            func-echo status=$?; [ "$status" != '0' ] && return $status
+        else
+            func-echo --head  "WARNING: Checked for threeway workflow"
+            func-echo "but found only $good out of 5 entries."
+            func-echo "Check the remote origin and upstream config entries."
+        fi
     fi
 
     echo "Setting up for worktrees..."
@@ -2160,7 +2107,7 @@ git-clone ()
             -t|--timestamp) opt_t=1; shift ;;
             -h|--help) $usage_func; return $OK ;;
             --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) echo "Internal error!"; $usage_func ${FUNCNAME}; return $NOT_OK ;;
+            *) func-echo "Internal error!"; $usage_func ${FUNCNAME}; return $NOT_OK ;;
         esac
     done
 
@@ -2182,26 +2129,27 @@ git-clone ()
     local local_protocol=$(basename $cwpath)
     if [ "$local_protocol" != "$protocol" ]
     then
-        echo "You must be in a local directory path ending in"
-        echo "   $protocol"
-        echo "You are in $cwpath"
+        func-echo "You must be in a local directory path ending in"
+        func-echo "   $protocol"
+        func-echo "You are in $cwpath"
         local shouldbein="$gitfuncs_gitroot/$protocol"
         if [ ! -d $shouldbein ]
         then
-            echo "Cannot find '$shouldbein'."
-            echo "Correct and re-execute."
+            func-echo "Cannot find '$shouldbein'."
+            func-echo "Correct and re-execute."
             return $NOT_OK
         else
             local resp
             if ((opt_y))
             then
+                func-echo "Going to $shouldbein"
                 resp='y'
             else
                 resp=$(func-yesno "cd to $shouldbein")
             fi
             if [ "$resp" = 'n' ]
             then
-                echo "Correct and re-execute."
+                func-echo "Correct and re-execute."
                 return $NOT_OK
             else
                 _git_cd_to $shouldbein
@@ -2209,9 +2157,10 @@ git-clone ()
         fi
     fi
 
-    if [ -z "${gitfuncs_gitsvcs[$protocol]}" ]
+    local protocol_url=$(kvget gitfuncs_gitsvcs $protocol)
+    if [ -z "$protocol_url" ]
     then
-        echo "$protocol is unknown. Valid protocols are:${!gitfuncs_gitsvcs[@]}"
+        func-echo "$protocol is unknown. Valid protocols are:$(kvgetvalues gitfuncs_gitsvcs)"
         return $NOT_OK
     fi
 
@@ -2229,16 +2178,15 @@ git-clone ()
         rm -rf $tgt
     fi
 
-    local cmd="git clone ${gitfuncs_gitsvcs[$protocol]}$namespace/$repo $namespace/$repo"
-    echo $cmd ...
+    local cmd="git clone ${protocol_url}$namespace/$repo $namespace/$repo"
+    func-echo $cmd ...
     $cmd
     status=$?; [ "$status" != '0' ] && return $status
-
     if ((opt_t))
     then
-        func-echo "Setting timestamps..."
-        (cd $namespace/$repo; git-retimestamp)
-        func-echo Done
+        func-echo 'Setting timestamps...'
+        (builtin cd $namespace/$repo; git-retimestamp)
+        func-echo 'Done'
     fi
     ## dirlist, not builtin cd, to take advantage this cd enhancement
     dirlist $namespace/$repo
@@ -2302,9 +2250,10 @@ git-delete-repo ()
     local repo=$1;shift
     local returnpath=$(realpath $(pwd))
 
-    if [ -z "${gitfuncs_gitsvcs[$protocol]}" ]
+    local protocol_url=$(kvget gitfuncs_gitsvcs $protocol)
+    if [ -z "$protocol_url" ]
     then
-        echo "$protocol is unknown. Valid protocols are:${!gitfuncs_gitsvcs[@]}"
+        echo "$protocol is unknown. Valid protocols are:$(kvgetvalues gitfuncs_gitsvcs)"
         return $NOT_OK
     fi
 
@@ -2975,11 +2924,11 @@ git-delete-worktree ()
     then
         resp='d'
     else
-        resp=$(func-pick "Keep, close or delete associated branch $current_branch" 'k/c/d' '' )
+        resp=$(func-pick "Keep, delete associated branch $current_branch" 'k/d' '' )
     fi
     if [ "$resp" = 'k' ]
     then
-        func-echo "If you change your mind: git-[close|delete]-branch $current_branch"
+        func-echo "If you change your mind: git-delete-branch $current_branch"
     else
         ## Have to be in a git repo to do this.
         while [ "$(basename $(pwd))" != 'wt' ]
@@ -2990,8 +2939,6 @@ git-delete-worktree ()
         if [ "$resp" = 'd' ]
         then
             git-delete-branch $opt_yes_string $current_branch
-        else
-            git-close-branch $current_branch
         fi
     fi
 
@@ -3528,9 +3475,10 @@ git-merge-pull-request ()
     local spoofing=$?
 
     local protocol=$1;shift
-    if [ -z "${gitfuncs_gitsvcs[$protocol]}" ]
+    local protocol_url=$(kvget gitfuncs_gitsvcs $protocol)
+    if [ -z "$protocol_url" ]
     then
-        func-echo "$protocol is unknown. Valid protocols are:${!gitfuncs_gitsvcs[@]}"
+        echo "$protocol is unknown. Valid protocols are:$(kvgetvalues gitfuncs_gitsvcs)"
         return $NOT_OK
     fi
 
@@ -3623,7 +3571,6 @@ git-merge-pull-request ()
             return $NOT_OK
         fi
     fi
-
     ((opt_verbose)) && func-echo --head "Clone $protocol:${tgt[$inamespace]}/${tgt[$irepo]}..."
     ${protocol}-clone ${tgt[$inamespace]} ${tgt[$irepo]}
     local status=$?
@@ -4155,7 +4102,6 @@ git-retimestamp ()
                 echo "gitfiles[$i] => ${gitfiles[$i]}" >> /tmp/get-retimestamp.log
                 unset gitfiles[$i]
                 [ -n "${gitfiles[$i]}" ] && echo "WOAH DIDNT DELETE gitfiles[$i] - '${gitfiles[$i]}'"
-                set +x
                 local filedate=$(stat -c %y $i | sed 's/\.[0-9]+//')
                 if [ ! "$filedate" = "$gitdate" ]
                 then
diff --git a/bin/utilfuncs b/bin/utilfuncs
--- a/bin/utilfuncs
+++ b/bin/utilfuncs
@@ -89,61 +89,24 @@ editor_opt () {
     return $shifts
 }
 
+## FPATH in bash. Hooray!
+
+. $PERSONALBIN/autoload
+
 # End early defs
 ##################################################################################
 
 UTILFUNCS_FILE=${BASH_SOURCE[0]}
-
 ## Load auditfuncs here so we can audit the utils
-
 . $(dirname $UTILFUNCS_FILE)/auditfuncs
-
-
 auditfuncs_init $UTILFUNCS_FILE
 safe_func_export utilfuncs_audit
-
-utilfuncs_edit ()
-{
-    utilfuncs_audit "$@"
-    local editor; editor=$(editor_opt xo "$@"); shift $?
-    $editor $UTILFUNCS_FILE
-}
-safe_func_export utilfuncs_edit
-utilfuncs-edit ()
-{
-    utilfuncs_edit "$@"
-}
-safe_func_export utilfuncs-edit
-
-utilfuncs_reload ()
-{
-    utilfuncs_audit "$@"
-    . $UTILFUNCS_FILE
-}
-safe_func_export utilfuncs_reload
-utilfuncs-reload ()
-{
-    utilfuncs_reload "$@"
-}
-safe_func_export utilfuncs-reload
-utilfuncs-load ()
-{
-    utilfuncs_reload "$@"
-}
-safe_func_export utilfuncs-load
+. $(dirname $UTILFUNCS_FILE)/controlfuncs_build $UTILFUNCS_FILE
 
 utilfuncs-help () {
     help_strings $UTILFUNCS_FILE "$@"
 }
-
-add_bb ()
-{
-    ##@@ none||none||add_bb||
-    utilfuncs_audit "$@"
-
-    addpath -x -f /bb/bin
-}
-safe_func_export add_bb
+safe_func_export utilfuncs-help
 
 ## 0-as-success is the correct way to return from commands and functions in
 ## UNIX so that the typical 0-success-from-UNIX-commands paradigm "just works"
@@ -194,6 +157,9 @@ export OK
 NOT_OK=$FALSE
 export NOT_OK
 
+##############
+## Numerics ##
+##############
 is_int ()
 {
     ##@@ none||none||is_int||Is an integer. Return 0 if true.
@@ -228,6 +194,16 @@ is_pos ()
     return $(true)
 }
 safe_func_export is_pos
+
+###################
+## Interactivity ##
+###################
+is-interactive ()
+{
+    tty > /dev/null
+    return $?
+}
+safe_func_export is-interactive
 
 pause ()
 {
@@ -307,160 +283,9 @@ yesno ()
 }
 safe_func_export yesno
 
-dowhich ()
-{
-    ##@@ none||none||dowhich||Find the executable and then run it with any args.
-    utilfuncs_audit "$@"
-
-    declare file=$1;shift
-    declare args="$@"
-
-    declare foundit=$(which $file)
-    if [ -z "$foundit" ]
-    then
-        echo "$file not found on PATH"
-        return $(false)
-    else
-        echo -n "Do $foundit $@"
-        yesno "" 'n' $foundit "$@"
-        return $?
-    fi
-}
-safe_func_export dowhich
-
-tarcopy ()
-{
-    ##@@ none||none||tarcopy||Use the tar trick to copy  arg1/* to arg2/* or arg2/arg1/*, with some intelligence.
-    utilfuncs_audit "$@"
-
-    local srcdir=$1
-    local tgtdir=$2
-    if [ ! -e $srcdir ]
-    then
-        echo "$srcdir not found"
-        return $(false)
-    fi
-    if [ ! -d $srcdir ]
-    then
-        echo "Source '$srcdir' must be a directory"
-        return $(false)
-    fi
-    if [ $(basename $srcdir) = $(basename $tgtdir) ]
-    then
-        echo "You're trying to copy $srcdir to $tgtdir."
-        echo "You probably want to use $(dirname $tgtdir)"
-        echo "as the target instead."
-        return $(false)
-    fi
-    if [ ! -e $tgtdir ]
-    then
-        echo "$tgtdir not found. Creating..."
-        mkdir $tgtdir || return $(false)
-    fi
-    if [ ! -d $tgtdir ]
-    then
-        echo "Target '$tgtdir' must be a directory"
-        return $(false)
-    fi
-    tgtdir=$(realpath $tgtdir)
-    startdir=$(pwd)
-    if [ "$srcdir" != '.' ]
-    then
-        echo "WARNING: You are about to copy $srcdir into $tgtdir"
-        echo "instead of copying the CONTENTS of $srcdir into $tgtdir"
-        read -p "Do you want to copy the (d)irectory or its (c)ontents? " resp
-        if [ "$resp" = 'd' ]
-        then
-            echo 'Ok...'
-        elif [ "$resp" = 'c' ]
-        then
-            echo "Yeah, that's what I figured"
-            echo "*** builtin cd $srcdir"
-            builtin cd $srcdir
-            srcdir='.'
-        else
-            echo "d or c, how hard could that have been???"
-            return $(false)
-        fi
-    fi
-    echo "*** tar cf - $srcdir | ( builtin cd $tgtdir; tar xvfp -)"
-    tar cf - $srcdir | ( builtin cd $tgtdir; tar xvfp -)
-    if [ $(pwd) != "$startdir" ]
-    then
-        echo "*** builtin cd $startdir"
-        builtin cd $startdir
-    fi
-    return $(true)
-}
-safe_func_export tarcopy
-tarcp ()
-{
-    tarcopy
-}
-safe_func_export tarcp
-
-list ()
-{
-    ##@@ none||none||list||Print each argument on its own line.
-    utilfuncs_audit "$@"
-
-    for i in "$@"
-    do
-        echo $i
-    done
-    return $(true)
-}
-safe_func_export list
-
-cattail ()
-{
-    ##@@ none||none||cattail||cat the whole file then continue tail -f
-    utilfuncs_audit "$@"
-
-    tail -n +1 -f "$@"
-    return $?
-}
-safe_func_export cattail
-
-tail_number_add ()
-{
-    ##@@ none||none||tail_number_add||Add a '(' and an index number to each argument.
-    utilfuncs_audit "$@"
-
-    local count=$#
-    local pad=${#count}
-    local i=0
-    local out
-    for a in "$@"
-    do
-        ((i+=1))
-        local e=$(printf '%s(%d' "$a" $i)
-        out="$out $e"
-    done
-    echo "$out"
-    return $?
-}
-safe_func_export tail_number_add
-
-tail_number_strip ()
-{
-    ##@@ none||none||tail_number_strip||From each argument (in theory the product of tail_number_add), strip from the '(' to the end.
-    utilfuncs_audit "$@"
-
-    local out
-    local a
-    for a in "$@"
-    do
-        out="$out ${a%(*}"
-    done
-    echo "$out"
-    return $?
-}
-safe_func_export tail_number_strip
-
-##
-## Bash array functions
-##
+##########################
+## Bash array functions ##
+##########################
 
 ## References:
 ## http://www.tech-recipes.com/rx/911/queue-and-stack-using-array/
@@ -497,10 +322,9 @@ bash_current_version_compare 4.3
 comp=$?
 if ((comp==255))
 then
-    echo "Cannot define array functions that use declare -n in bash $BASH_VERSION. Must be >= 4.3"
+    echo "Cannot define array and hash functions that use declare -n in bash $BASH_VERSION. Must be >= 4.3"
 else
-
-## Don't indent or else imenu won't find the functions.
+## Don't indent off of the else, or else imenu won't find the functions.
 ajoin()
 {
     ##@@ none||none||ajoin||Print one string that joins arg2, arg3, etc, separated by arg1
@@ -748,8 +572,11 @@ aunshift ()
     return $?
 }
 safe_func_export aunshift
-fi ##     echo "Cannot define array functions that use declare -n in bash $BASH_VERSION. Must be >= 4.3"
 
+########################################
+## Bash hash (assoc. array) functions ##
+########################################
+## References:
 hvalues ()
 {
     ##@@ none||none||hvalues||Print all the values of the hash named in arg1 to stdout, separated by a space. If the -list option is specified, then print each one on a separate line.
@@ -811,7 +638,11 @@ heach ()
     return $?
 }
 safe_func_export heach
+fi ##     echo "Cannot define array functions that use declare -n in bash $BASH_VERSION. Must be >= 4.3"
 
+########################
+## Function functions ##
+########################
 func-name-spoof ()
 {
     utilfuncs_audit "$@"
@@ -926,12 +757,358 @@ func-yesno ()
 }
 safe_func_export func-yesno
 
-is-interactive ()
+#####################
+## Key value store ##
+#####################
+kvstoreinit ()
 {
-    tty > /dev/null
+    local exists_ok=0
+    local unique=0
+    local reset=0
+    while [[ "$1" =~ ^- ]] && ((endofopts==0))
+    do
+        case "$1" in
+            --exists-ok ) exists_ok=1; shift ;;
+            --unique    ) unique=1; shift ;;
+            --reset     ) reset=1; shift ;;
+            --     ) endofopts=1; shift;;
+            -*     ) echo "$1 is an invalid option."; return 1;;
+        esac
+    done
+
+    if [ ! -d ~/.kvdbs ]
+    then
+        echo Initializing kv storage at ~/.kvdbs
+        mkdir ~/.kvdbs
+    fi
+
+    local db=$1;
+
+    if [ ! "$(basename $db)" = "$db" ]
+    then
+        echo "ERROR - kv store name cannot include directories"
+        return 1
+    fi
+
+    local dbfile=~/.kvdbs/$db
+
+    if [ -e $dbfile ]
+    then
+        if ((reset))
+        then
+            \rm $dbfile
+        elif ((exists_ok))
+        then
+            return 0
+        else
+            echo "ERROR - kv store name $db exists"
+            return 1
+        fi
+    fi
+
+    if ((unique))
+    then
+        ## 'unique' has the use case where multiple processes would need their
+        ## own copies of the database. Instead, we generate a UUID and give it
+        ## back to the caller to pass back into subsequent calls. This is not
+        ## yet implemented in subsequent calls.
+        local u=$(uuid)
+        echo $u
+        sqlite3 $dbfile "create table keyval (uuid text, key text, value text,
+                             primary key (uuid, key)"
+        local status=$?
+        return
+    else
+        sqlite3 $dbfile "create table keyval (key text primary key, value text)"
+        return $?
+    fi
+}
+safe_func_export kvstoreinit
+
+kvget ()
+{
+    _kvgetany "value" "$@"
     return $?
 }
-safe_func_export is-interactive
+safe_func_export kvget
+
+kvgetvalues ()
+{
+    _kvgetany "value" "$@"
+    return $?
+}
+safe_func_export kvgetvalues
+
+kvgetkeys ()
+{
+    _kvgetany "key" "$@"
+    return $?
+}
+safe_func_export kvgetkeys
+
+kvgetboth ()
+{
+    _kvgetany "key,value" "$@"
+    return $?
+}
+safe_func_export kvgetboth
+
+_kvgetany ()
+{
+    local columns=$1; shift
+
+    local endofopts=0
+    local sort=''
+    local where=''
+    local separator=''
+    while [[ "$1" =~ ^- ]] && ((endofopts==0))
+    do
+        case "$1" in
+            --sort ) sort='order by 1'; shift ;;
+            --rev* ) sort='order by 1 desc'; shift ;;
+            --sep* ) separator="--separator $2"; shift; shift ;;
+            --     ) endofopts=1; shift;;
+            -*     ) echo "$1 is an invalid option."; return 1;;
+        esac
+    done
+
+    local db=$1; shift
+
+    local dbfile=~/.kvdbs/$db
+
+    if [ ! -e $dbfile ]
+    then
+        echo "ERROR - kv store name $db does not exist"
+        return 1
+    fi
+
+    local key="$1"; shift
+    local where=''
+
+    [ -n "$key" ] && where="where key like '$key'" ## These databases should be
+                                                   ## small enough that using
+                                                   ## like in all cases will be
+                                                   ## fast enough. Maybe the
+                                                   ## SQL engine will convert a
+                                                   ## like with no wildcards to
+                                                   ## an equal anyway.
+
+    sqlite3 --noheader $separator $dbfile "select $columns from keyval $where $sort"
+
+    return $?
+}
+safe_func_export _kvgetany
+
+kvput ()
+{
+    ## Insert if DNE, update if it does.
+    local db=$1; shift
+    local dbfile=~/.kvdbs/$db
+
+    if [ ! -e $dbfile ]
+    then
+        echo "ERROR - kv store name $db does not exist"
+        return 1
+    fi
+
+    local key="$1"; shift
+
+    sqlite3 --noheader $dbfile \
+            "update keyval
+             set key = '$key', value = '$@'
+             where key = '$key';
+
+             insert into keyval (key, value)
+             select '$key', '$@'
+             where (Select Changes() = 0)"
+    return $?
+}
+safe_func_export kvput
+
+kvputinit ()
+{
+    ## Put if DNE, ok if exists and same, bark if exists and different.
+    local db=$1; shift
+    local dbfile=~/.kvdbs/$db
+
+    if [ ! -e $dbfile ]
+    then
+        echo "ERROR - kv store name $db does not exist"
+        return 1
+    fi
+
+    local key="$1"; shift
+
+    local value=$(sqlite3 --noheader $dbfile "select value from keyval where key = '$key'");
+    if [ "$value" = "$@" ]
+    then
+        return 0
+    elif [ -z "$value" ]
+    then
+        sqlite3 --noheader $dbfile "insert into keyval values ('$key', '$@')"
+        return $?
+    else
+        echo "ERROR - kvputinit. Key = '$key'. Init value '$@' does not match existing value '$value'"
+        return 1
+    fi
+}
+safe_func_export kvputinit
+
+###################
+## Miscellaneous ##
+###################
+dowhich ()
+{
+    ##@@ none||none||dowhich||Find the executable and then run it with any args.
+    utilfuncs_audit "$@"
+
+    declare file=$1;shift
+    declare args="$@"
+
+    declare foundit=$(which $file)
+    if [ -z "$foundit" ]
+    then
+        echo "$file not found on PATH"
+        return $(false)
+    else
+        echo -n "Do $foundit $@"
+        yesno "" 'n' $foundit "$@"
+        return $?
+    fi
+}
+safe_func_export dowhich
+
+tarcopy ()
+{
+    ##@@ none||none||tarcopy||Use the tar trick to copy  arg1/* to arg2/* or arg2/arg1/*, with some intelligence.
+    utilfuncs_audit "$@"
+
+    local srcdir=$1
+    local tgtdir=$2
+    if [ ! -e $srcdir ]
+    then
+        echo "$srcdir not found"
+        return $(false)
+    fi
+    if [ ! -d $srcdir ]
+    then
+        echo "Source '$srcdir' must be a directory"
+        return $(false)
+    fi
+    if [ $(basename $srcdir) = $(basename $tgtdir) ]
+    then
+        echo "You're trying to copy $srcdir to $tgtdir."
+        echo "You probably want to use $(dirname $tgtdir)"
+        echo "as the target instead."
+        return $(false)
+    fi
+    if [ ! -e $tgtdir ]
+    then
+        echo "$tgtdir not found. Creating..."
+        mkdir $tgtdir || return $(false)
+    fi
+    if [ ! -d $tgtdir ]
+    then
+        echo "Target '$tgtdir' must be a directory"
+        return $(false)
+    fi
+    tgtdir=$(realpath $tgtdir)
+    startdir=$(pwd)
+    if [ "$srcdir" != '.' ]
+    then
+        echo "WARNING: You are about to copy $srcdir into $tgtdir"
+        echo "instead of copying the CONTENTS of $srcdir into $tgtdir"
+        read -p "Do you want to copy the (d)irectory or its (c)ontents? " resp
+        if [ "$resp" = 'd' ]
+        then
+            echo 'Ok...'
+        elif [ "$resp" = 'c' ]
+        then
+            echo "Yeah, that's what I figured"
+            echo "*** builtin cd $srcdir"
+            builtin cd $srcdir
+            srcdir='.'
+        else
+            echo "d or c, how hard could that have been???"
+            return $(false)
+        fi
+    fi
+    echo "*** tar cf - $srcdir | ( builtin cd $tgtdir; tar xvfp -)"
+    tar cf - $srcdir | ( builtin cd $tgtdir; tar xvfp -)
+    if [ $(pwd) != "$startdir" ]
+    then
+        echo "*** builtin cd $startdir"
+        builtin cd $startdir
+    fi
+    return $(true)
+}
+safe_func_export tarcopy
+tarcp ()
+{
+    tarcopy
+}
+safe_func_export tarcp
+
+list ()
+{
+    ##@@ none||none||list||Print each argument on its own line.
+    utilfuncs_audit "$@"
+
+    ## Don't use echo "$@" | tr ' ' '\n'; it will not respect spaces inside of
+    ## an argument.
+    for i in "$@"
+    do
+        echo $i
+    done
+    return $(true)
+}
+safe_func_export list
+
+cattail ()
+{
+    ##@@ none||none||cattail||cat the whole file then continue tail -f
+    utilfuncs_audit "$@"
+
+    tail -n +1 -f "$@"
+    return $?
+}
+safe_func_export cattail
+
+tail_number_add ()
+{
+    ##@@ none||none||tail_number_add||Add a '(' and an index number to each argument.
+    utilfuncs_audit "$@"
+
+    local count=$#
+    local pad=${#count}
+    local i=0
+    local out
+    for a in "$@"
+    do
+        ((i+=1))
+        local e=$(printf '%s(%d' "$a" $i)
+        out="$out $e"
+    done
+    echo "$out"
+    return $?
+}
+safe_func_export tail_number_add
+
+tail_number_strip ()
+{
+    ##@@ none||none||tail_number_strip||From each argument (in theory the product of tail_number_add), strip from the '(' to the end.
+    utilfuncs_audit "$@"
+
+    local out
+    local a
+    for a in "$@"
+    do
+        out="$out ${a%(*}"
+    done
+    echo "$out"
+    return $?
+}
+safe_func_export tail_number_strip
 
 wcstrip ()
 {
@@ -968,3 +1145,47 @@ grep-not-in ()
     grep -L "$@"
 }
 safe_func_export grep-not-in
+
+uuid ()
+{
+    perl -e 'open my $FH, "/dev/urandom"
+      or die "Cannot generate UUID\n";
+    sysread( $FH, my $r, 16 );
+    close $FH;
+
+    # treat $r as 8 16bit quantities using vec, format as a v4 uuid by
+    # grouping appropriately and setting the appropriate variant and version
+    # bits
+
+    printf "%04x%04x-%04x-%04x-%04x-%04x%04x%04x",
+      vec( $r, 0, 16 ), vec( $r, 1, 16 ),
+      vec( $r, 2, 16 ),
+      ( ( vec( $r, 3, 16 ) & 0x0FFF ) | 0x4000 ),
+      ( ( vec( $r, 4, 16 ) & 0x3FFF ) | 0x8000 ),
+      vec( $r, 5, 16 ), vec( $r, 6, 16 ), vec( $r, 7, 16 );'
+}
+safe_func_export uuid
+
+get-next-descriptor ()
+{
+    ##@@ none||none||get-next-descriptor||print the next free shell io descriptor number.
+    utilfuncs_audit "$@"
+    local found=none
+    local fd
+    local rco
+    local rci
+    for fd in {0..255}
+    do
+        rco="$(true 2>/dev/null >&${fd}; echo $?)";
+        rci="$(true 2>/dev/null <&${fd}; echo $?)";
+        [[ "${rco}${rci}" = "11" ]] && found=${fd} && break
+    done
+    if [ -z "$found" ]
+    then
+        return 1
+    else
+        echo $found
+        return 0
+    fi
+}
+safe_func_export get-next-descriptor
