cmd-echo shenannigans
bin/cmd-echo
o fix up a missed func/script conversion.

bin/from-ext
o Converted to cmd-echo.

bin/func-to-exec
o Converted to cmd-echo.

bin/func-to-exec.pl
o Add func-usage conversion.

bin/git-branch
o Converted to cmd-echo.

bin/git-check-with-remote
o Converted to cmd-echo.

bin/git-clone
o Converted to cmd-echo.

bin/git-commit-with-changelog
o Converted to cmd-echo.

bin/git-diff-two-repos-on-disk
o Converted to cmd-echo.

bin/git-find
o Converted to cmd-echo.

bin/git-ping
o Converted to cmd-echo.

bin/git-post-new
o Converted to cmd-echo.

bin/git-process-changelog
o Converted to cmd-echo.

bin/git-rebase-log
o Converted to cmd-echo.

bin/git-status-with-changelog
o Converted to cmd-echo.

bin/git-sync-with-remote
o Converted to cmd-echo.

bin/git-worktree
o Converted to cmd-echo.

bin/script-echo
o Converted to cmd-echo.

bin/script-pick
o Converted to cmd-echo.

bin/script-yesno
o Converted to cmd-echo.

bin/todo
o Converted to cmd-echo.

bin/xo
o Converted to cmd-echo.

bin/xterm-Xsize
o Converted to cmd-echo.

data/autoload-unshim.dat
o Removed func and cmd-echo. Obsolete and converted to script,
  respectively.

functions/func-pick
o Converted to cmd-echo.

functions/func-usage
o Converted to cmd-echo.

functions/func-yesno
o Converted to cmd-echo.

functions/git-delete-repo
o Converted to cmd-echo.

functions/git-go
o Fixed match-by-index.

functions/git-hold
o Converted to cmd-echo.

functions/git-hold-diff
o Converted to cmd-echo.

functions/git-hold-remove
o Converted to cmd-echo.

functions/git-hold-restore
o Converted to cmd-echo.

functions/git-merge-find
o Converted to cmd-echo.

functions/git-merge-pull-request
o Converted to cmd-echo.

functions/git-pull
o Converted to cmd-echo.

functions/git-to-stdout
o Converted to cmd-echo.

functions/git-worktree-diff-to-root
o Converted to cmd-echo.

functions/script-usage
o Converted to cmd-echo.

diff --git a/bin/from-ext b/bin/from-ext
--- a/bin/from-ext
+++ b/bin/from-ext
@@ -22,7 +22,7 @@ do
             opt_sparse=1
             ;;
         help )
-            script-echo "No help yet - read the code:"
+            cmd-echo "No help yet - read the code:"
             cat "$0"
             exit 0
             ;;
@@ -31,7 +31,7 @@ do
             moreopts=0
             ;;
         * )
-            script-echo -- "$original is an invalid option. See $0 --help"; exit 1;;
+            cmd-echo -- "$original is an invalid option. See $0 --help"; exit 1;;
     esac
 done
 
@@ -42,9 +42,9 @@ if ((opt_dirty==0))
 then
     if (($(git status --porcelain 2>&1 | grep -c -v "$sharfile")))
     then
-        script-echo "Will not unpack shar. Repo not clean. Clean it up."
-        script-echo -c "Use --dirty if you've already unpacked,"
-        script-echo -c "the shar, but you need to rerun for some reason."
+        cmd-echo "Will not unpack shar. Repo not clean. Clean it up."
+        cmd-echo -c "Use --dirty if you've already unpacked,"
+        cmd-echo -c "the shar, but you need to rerun for some reason."
         git status
         exit 1
     fi
@@ -64,15 +64,15 @@ unshar -c "$sharfile"
 ## ones we need to git rm.
 if ((opt_sparse==1))
 then
-    script-echo "Not git rm'ing 'old' files because --sparse was indicated."
+    cmd-echo "Not git rm'ing 'old' files because --sparse was indicated."
 else
     if [ -r git-rms ]
     then
         rms=$(cat git-rms)
-        script-echo "Using 'git-rms' to remove files."
+        cmd-echo "Using 'git-rms' to remove files."
         yesno "git rm $rms" n git rm "$rms"
     else
-        script-echo "Comparing files to $(ls -la $oldermarker) to remove files."
+        cmd-echo "Comparing files to $(ls -la $oldermarker) to remove files."
         for i in $(git ls-files)
         do
             if [ "$i" -ot "$oldermarker" ]
@@ -95,7 +95,7 @@ comp_to_this_sha=$(git log -1 | grep '^commit' | sed 's/commit //')
 
 ## ...to make a useful commit message.
 commitmessage=/tmp/from-ext.$$.commitmessage
-script-echo "External sync. Run 'git diff $comp_to_this_sha' for details." > $commitmessage
+cmd-echo "External sync. Run 'git diff $comp_to_this_sha' for details." > $commitmessage
 
 ## Go for it. -a gets the modified files we didn't bother to run git -add against.
 ## The message is in -F.
diff --git a/bin/func-to-exec b/bin/func-to-exec
--- a/bin/func-to-exec
+++ b/bin/func-to-exec
@@ -5,14 +5,14 @@
 if [[ "$(pwd)" =~ functions ]] || \
        [[ "$(pwd)" =~ bin ]]
 then
-    script-echo 'Cannot be in functions or bin subdir for conversion.' \
+    cmd-echo 'Cannot be in functions or bin subdir for conversion.' \
                 'cd .. and re-exec.'
     exit 1
 fi
 
 if [ -z "$1" ]
 then
-    script-echo "usage: $0 func [func...]" \
+    cmd-echo "usage: $0 func [func...]" \
                 "       You can use or not use the 'function/'" \
                 "       prefix;we will adjust."
     exit 1;
@@ -40,14 +40,14 @@ do
     src_path="functions/$funcname"
     if [ ! -r "$src_path" ]
     then
-        script-echo -- "$src_path not found"
+        cmd-echo -- "$src_path not found"
         ((bad+=1))
     else
         justified=$(grep 'Function Justification' "$src_path" | \
                         grep -i -v none)
         if [ -n "$justified" ]
         then
-            script-echo "Not converting $src_path: $(grep 'Function Justification' "$src_path")"
+            cmd-echo "Not converting $src_path: $(grep 'Function Justification' "$src_path")"
             ((bad+=1))
         else
             funcnames+=("$funcname")
@@ -57,18 +57,18 @@ do
         fi
     fi
 done
-((${#src_paths[@]}==0)) && script-echo "No sources found to convert. Bailing." && exit 1
-((bad)) && script-echo "Some sources bad. Bailing" && exit 1
+((${#src_paths[@]}==0)) && cmd-echo "No sources found to convert. Bailing." && exit 1
+((bad)) && cmd-echo "Some sources bad. Bailing" && exit 1
 
 ## Copy function files to bin
-script-echo "Copying function files..."
+cmd-echo "Copying function files..."
 for funcname in "${funcnames[@]}"
 do
     cp "${src_paths[$funcname]}" "${tgt_paths[$funcname]}"
 done
 
 ## Do the conversions
-script-echo "Converting to scripts..."
+cmd-echo "Converting to scripts..."
 if ! func-to-exec.pl "${tgt_paths[@]}" ## Each conversion of bin/foo will be in bin/foo.new
 then
     exit $?
@@ -83,7 +83,7 @@ declare tgt_path
 declare resp
 for funcname in "${funcnames[@]}"
 do
-    script-echo --head --title "$funcname"
+    cmd-echo --head --title "$funcname"
 
     tmp_path="${tmp_paths[$funcname]}"
     src_path="${src_paths[$funcname]}"
@@ -121,7 +121,7 @@ done
 ## Unwind rejects
 for funcname in "${revert_list[@]}"
 do
-    script-echo "Reverting $funcname..."
+    cmd-echo "Reverting $funcname..."
     tgt_path="${tgt_paths[$funcname]}"
     tmp_path="${tmp_paths[$funcname]}"
     \rm -f "$tgt_path" "$tmp_path"
@@ -132,7 +132,7 @@ done
 
 if ((!${#commit_list[@]}))
 then
-    script-echo 'Nothing to commit.'
+    cmd-echo 'Nothing to commit.'
     exit 0
 fi
 
@@ -140,15 +140,15 @@ fi
 \rm -f "${tgt_paths[@]}"
 
 ## Do the git move
-script-echo "git mv ${src_paths[*]} bin"
+cmd-echo "git mv ${src_paths[*]} bin"
 git mv "${src_paths[@]}" bin
 
 ## Commit the move
-script-echo "git commit ${src_paths[*]} ${tgt_paths[*]} -m 'func to exec, move phase'"
+cmd-echo "git commit ${src_paths[*]} ${tgt_paths[*]} -m 'func to exec, move phase'"
 GPCHA='--skip shellcheck' git commit "${src_paths[@]}" "${tgt_paths[@]}" -m 'func to exec, move phase'
 
 ## Overlay the moves with the converted temps
-script-echo "Overlay with converted files..."
+cmd-echo "Overlay with converted files..."
 declare -a unset_contents
 for funcname in "${commit_list[@]}"
 do
@@ -160,8 +160,8 @@ do
 done
 
 ## Commit the conversions
-script-echo "git commit ${tgt_paths[*]} -m 'func to exec, convert phase'"
+cmd-echo "git commit ${tgt_paths[*]} -m 'func to exec, convert phase'"
 git commit "${tgt_paths[@]}" -m 'func to exec, convert phase'
 
 ## Reminder
-script-echo 'Remember to' "unset -f ${unset_contents[*]}"
+cmd-echo 'Remember to' "unset -f ${unset_contents[*]}"
diff --git a/bin/git-check-with-remote b/bin/git-check-with-remote
--- a/bin/git-check-with-remote
+++ b/bin/git-check-with-remote
@@ -24,13 +24,13 @@ do
         -b|--branch) opt_branch="$2"; shift; shift ;;
         -h|--help) script-usage "$0"; exit 0 ;;
         --) shift; break ;; ## end of opts, remaining $*, if any, are args
-        *) script-echo "Internal error!"; script-usage "$0"; exit 1 ;;
+        *) cmd-echo "Internal error!"; script-usage "$0"; exit 1 ;;
     esac
 done
 
 if [ -z "$opt_branch" ]
 then
-    script-echo -- "--branch required"
+    cmd-echo -- "--branch required"
     script-usage "$0"
     exit 1
 fi
@@ -93,7 +93,7 @@ check.
 EOF
     if ((opt_bail_on_dirty))
     then
-        script-echo Exiting.
+        cmd-echo Exiting.
         exit 1
     else
         declare resp
@@ -144,10 +144,10 @@ then
     if [ "$(cat "$difflog" | wc -l)" = '10' ] \
            && [ ! "$(grep -E "Merge pull request.*$(git-branch get-current)" "$difflog")" = '' ]
     then
-        script-echo "Only diff to ${opt_remote} is merge pull request."
+        cmd-echo "Only diff to ${opt_remote} is merge pull request."
     else
-        script-echo -head "*** git repo: $(pwd)"
-        script-echo -c "*** Current branch $(git branch get-current) and ${opt_remote}/${opt_branch} are not synced:"
+        cmd-echo -head "*** git repo: $(pwd)"
+        cmd-echo -c "*** Current branch $(git branch get-current) and ${opt_remote}/${opt_branch} are not synced:"
         cat "$difflog"
     fi
 fi
