Eliminate TILDAE

diff --git a/bin/git-go b/bin/git-go
--- a/bin/git-go
+++ b/bin/git-go
@@ -34,7 +34,7 @@ _line-enhance ()
             printf '%s (%d\n' "$a" "$i"
         done
     else
-        declare gitfuncs_git_went_file="${TILDAE:-$HOME}/gits/.git-went"
+        declare gitfuncs_git_went_file="${HOME}/gits/.git-went"
         declare repo secs time line
         declare -a lines
         for a in "$@"; do
@@ -65,7 +65,7 @@ _set-and-go ()
 
     if [[ -n "$repo" ]]; then
 	    declare th
-	    th="$(realpath "${TILDAE:-$HOME}")"
+	    th="$(realpath "${HOME}")"
         declare full_repo="${th}/"${repo##"${th}/"}
         if [[ ! -d "$full_repo" ]]; then
             cmd-echo --id git-go --ec -- "'$repo' does not exist. It will be removed from consideration."
@@ -257,7 +257,7 @@ else
         for r in "${REPOS[@]}"; do
             (
                 # The false; exit; will exit from the subshell, skipping the git status call
-                cd "${TILDAE:-$HOME}/$r" || { echo "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+                cd "${HOME}/$r" || { echo "Cannot cd ${HOME}/$r"; false; exit; }
                 if (( $(git status --porcelain | wc  -l) )); then
                     echo
                     cmd-echo --id git-go -- "$r"
@@ -273,7 +273,7 @@ else
             repos_size=$(mktempfile)
             rm_on_exit "$repos_size"
             for r in "${REPOS[@]}"; do
-                du -s --exclude wt "${TILDAE:-$HOME}/${r}"
+                du -s --exclude wt "${HOME}/${r}"
             done > "$repos_size"
             readarray -t REPOS < <(sort -nr "$repos_size" | sed -e 's/^[0-9]\+\s\+//')
         fi
@@ -284,17 +284,17 @@ else
                 du -hs --exclude wt "${r}"
             else
                 declare rexp
-                ((opt_list==1)) && rexp="~/${r}" || rexp="${TILDAE:-$HOME}/${r}"
+                ((opt_list==1)) && rexp="~/${r}" || rexp="${HOME}/${r}"
                 if ((opt_stat==1)); then
                     echo "$rexp"
                     (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+                        cd "${HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${HOME}/$r"; false; exit; }
                         git status --porcelain
                     )
                     echo
                 elif ((opt_stat==2)); then
                     (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+                        cd "${HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${HOME}/$r"; false; exit; }
                         if (( $(git status --porcelain | wc -l) )); then
                             echo "$rexp"
                             if ((opt_brief==0)); then
@@ -305,7 +305,7 @@ else
                     )
                 elif ((opt_comments)); then
                     (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+                        cd "${HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${HOME}/$r"; false; exit; }
                         declare output
                         output="$(git comment --show --hi)"
                         if ((opt_comments==1)) || \
@@ -316,7 +316,7 @@ else
                     )
                 elif ((opt_show_pr)); then
                      (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+                        cd "${HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${HOME}/$r"; false; exit; }
                         echo "$rexp"
                         echo -n "    "
                         git repo pr-get
@@ -406,7 +406,7 @@ Usage: git go [options] [ [^]filter [ [^]filter...] ]
 
    git go [-h|--help]
 
-   Presents a list of all git repos in ${TILDAE:-$HOME}/gits for you to
+   Presents a list of all git repos in ${HOME}/gits for you to
    choose and then cd to.
 
    Undocumented, yet:
diff --git a/bin/git-go-get b/bin/git-go-get
--- a/bin/git-go-get
+++ b/bin/git-go-get
@@ -76,7 +76,7 @@ if [[ -n "$limited" ]]; then
         echo "$i" >> "$tmpfile"
     done
 else
-    gitfuncs_git_go_file="${TILDAE:-$HOME}/gits/.git-go.$(date +%Y%m%d)"
+    gitfuncs_git_go_file="${HOME}/gits/.git-go.$(date +%Y%m%d)"
     if [[ ! -e "$gitfuncs_git_go_file" ]] || ((update)); then
         git-go-set
     fi
@@ -117,7 +117,7 @@ if ((with_pr)); then
     for r in "${repos[@]}"; do
         (
             # The false; exit; will exit from the subshell, skipping the rest
-            cd "${TILDAE:-$HOME}/$r" || { echo "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+            cd "${HOME}/$r" || { echo "Cannot cd ${HOME}/$r"; false; exit; }
             if ((with_pr==1)) && git repo pr-get 1>/dev/null 2>&1 ; then
                 echo "$r"
             elif ((with_pr==2)) && ! git repo pr-get 1>/dev/null 2>&1 ; then
