Periodic
bin/cp-reverse
- Replace passing the command to do on 'Y' into yes-no with &&ing the
  command.

bin/git-go
- Changed builtin cd || statements to {} not (), so that the return
  statements return from the correct level of shell code.
- Added 'prune' as an option.

bin/git-process-source-ctrl-log
- Extend debug flag to debug called Perl script.

bin/git-repo
- Changed cd || statements to {} not (), so that the return statements
  return from the code at that point. Using () returns from the
  subprocess and doesn't abort the current execution.

git-repo-delete():
  - Allow --curr for current.

git-repo-is_pristine():
  - Do not print the root repo for the worktrees.

git-repo-restore():
  - Added progress messages.

bin/git-status-with-source-ctrl-log
- Pass any -x setting down to git-process-source-ctrl-log.

bin/git-worktree
- Added error coloring to some output.
- Changed builtin cd || statements to {} not (), so that the return
  statements return from the correct level of shell code.

bin/logit
- Some refactoring, anticipating being able to relocate 'tee'ed windows.
- Added relocating the xterm tee window to near the executing window.
- Add elapsed time to the log.

bin/on_exit.binc
- Update comments to reference mktemp.binc. Can't put the mktemp funcs in
  here and rig them to call rm-on-exit because exiting the mktemp
  function counts as an exit and the temps get removed before you even
  get back from the mktemp calls. After some experimentation, mktemp.binc
  was created to hold the mktemp* funcs and documented here.

bin/relative
- Replace passing the command to do on 'Y' into yes-no with &&ing the
  command. Shellchecked.

bin/toxic
- Don't clean twice in a row w/o confirmation.

bin/xo
- Start up with geometry calculation, middle of the root.

bin/xterm-cli
- Consolidation of xterm manip scripts.

xterm-cli-info():
  - Added info command, defaulting to current window.

bin/xterm-id
- Obsolete - replaced by xterm-cli.

bin/xterm-location
- Obsolete - replaced by xterm-cli.

bin/xterm-size
- Obsolete - replaced by xterm-cli.

bin/xtermfuncs
- Shellcheck.

bin/yesno
- Fixed --noprint option processing.
- Removed the execution of command on positive response. The caller can
  arrange that with a && statement.

dotfiles/gitconfig
- drc == dorealclean

dotfiles/inputrc
- Enhancements from the interwebs.

dotfiles/xterminit
- Remove function loads. Not needed in chimera startup, replaced with
  xterm-cli commands.

functions/settitle
- Obsolete - replaced by xterm-cli.

functions/ticker
- Obsolete - replaced by xterm-cli.

functions/tickercfg
- Obsolete - replaced by xterm-cli.

functions/tickerkill
- Obsolete - replaced by xterm-cli.

diff --git a/bin/git-go b/bin/git-go
--- a/bin/git-go
+++ b/bin/git-go
@@ -97,6 +97,8 @@ do
         doandcd ) doandcdfile=$1; shift;;
         set ) cmd-echo -- Working...
               git-go-set; exit 0;;
+        prune ) cmd-echo -- Working...
+              git-go-prune; exit 0;;
         h | help ) bash-usage "$0"; exit 0 ;;
         --) break ;; ## VITAL!!! Exits the while loop, no more options,
                      ## remaining $*, if any, are args
@@ -172,13 +174,16 @@ else
     then
         for r in "${REPOS[@]}"
         do
-            (cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1)
-             if (( $(git status --porcelain | wc  -l) ))
-             then
-                 echo
-                 cmd-echo -- "$r"
-                 git status
-             fi)
+            (
+                # The exit 1; will exit from the subshell, skipping the git status call
+                cd "${TILDAE:-$HOME}/$r" || { echo "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
+                if (( $(git status --porcelain | wc  -l) ))
+                then
+                    echo
+                    cmd-echo -- "$r"
+                    git status
+                fi
+            )
         done
     elif ((opt_list))
     then
@@ -208,13 +213,15 @@ else
                 if ((opt_stat==1))
                 then
                     echo "$rexp"
-                    (cd "${TILDAE:-$HOME}/$r" || (cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1);
-                     git status --porcelain)
+                    (
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
+                        git status --porcelain
+                    )
                     echo
                 elif ((opt_stat==2))
                 then
                     (
-                        cd "${TILDAE:-$HOME}/$r" || (cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1);
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
                         if (( $(git status --porcelain | wc -l) ))
                         then
                             echo "$rexp"
@@ -228,7 +235,7 @@ else
                 elif ((opt_comments))
                 then
                     (
-                        cd "${TILDAE:-$HOME}/$r" || (cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1);
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
                         declare output
                         output="$(git comment --show --hi)"
                         if ((opt_comments==1)) || \
@@ -416,6 +423,11 @@ Usage: git-go [options] [ filter [filter...] ]
    --set
        Don't go anywhere but reset the list of repos. Use this after file
        system surgery.
+
+   --prune
+       Visit each repo that would ordinarily end up in the selection list and
+       try to remove it. The repo must have no open PRs and no uncommitted
+       objects.
 
    'filter' will filter the list using grep.
 
diff --git a/bin/git-repo b/bin/git-repo
--- a/bin/git-repo
+++ b/bin/git-repo
@@ -21,10 +21,10 @@ git-repo-is ()
         verbose=1
         shift
     fi
-    [[ "$1" ]] && [[ $1 != . ]] && (cd "$1" || return 1)
+    [[ "$1" ]] && [[ $1 != . ]] && { cd "$1" || return 1; }
     git rev-parse --show-toplevel 2>/dev/null 1>&2
     status=$?
-    [[ "$1" ]] && [[ $1 != . ]] && (cd - || return 1)
+    [[ "$1" ]] && [[ $1 != . ]] && { cd - || return 1; }
     (( verbose )) && ( (( status )) && echo false || echo true )
     return $status
 }
@@ -55,7 +55,10 @@ git-repo-is_pristine ()
         if ! git worktree ina && (( $(git worktree list | wc -l) != 1 ))
         then
             echo Found worktrees:
-            git worktree list
+            git worktree list | tail -n +2 # Do not print the root repo for the
+                                           # worktrees, which is always the
+                                           # first entry of the wt list
+                                           # command.
         fi
     fi
     return 1
@@ -126,9 +129,9 @@ git-repo-is_fork_of ()
 
 git-repo-name ()
 {
-    [[ "$1" ]] && [[ $1 != . ]] && (cd "$1" || return 1)
+    [[ "$1" ]] && [[ $1 != . ]] && { cd "$1" || return 1; }
     name=$(git remote -v 2>/dev/null | grep origin | sed 's|.*/||' | sed 's/ .*//' | sort -u)
-    [[ "$1" ]] && [[ $1 != . ]] && (cd - || return 1)
+    [[ "$1" ]] && [[ $1 != . ]] && { cd - || return 1; }
     [ -z "$name" ] && return 1
     echo "$name"
     return 0
@@ -333,7 +336,7 @@ git-repo-delete ()
     declare dirmode=''
     [[ -z $1 ]] && bash-usage "$0" && return 1
     if [[ $1 = '--pwdmode' ]] \
-           || [[ $1 == '--current' ]] \
+           || [[ $1 =~ ^--curr ]] \
            || [[ $1 == '-c' ]] \
            || [[ $1 == '.' ]]
     then
@@ -364,17 +367,17 @@ git-repo-delete ()
     if [ -n "$dirmode" ]
     then
         ## We were given the directory containing the repo
-        builtin cd "$dirmode" || ( cmd-echo "Cannot cd $dirmode" && return 1 )
+        builtin cd "$dirmode" || { cmd-echo "Cannot cd $dirmode" && return 1; }
         declare root_or_err
         root_or_err="$(git root 2>&1)"
         declare status=$?
         if ((status))
         then
             cmd-echo -- "$root_or_err"
-            builtin cd "$returnpath" || ( cmd-echo "Cannot cd $returnpath" && return 1)
+            builtin cd "$returnpath" || { cmd-echo "Cannot cd $returnpath" && return 1; }
             return $status
         else
-            builtin cd "$root_or_err" || ( cmd-echo "Cannot cd $root_or_err" && return 1)
+            builtin cd "$root_or_err" || { cmd-echo "Cannot cd $root_or_err" && return 1; }
         fi
     elif ((!current))
     then
@@ -426,7 +429,7 @@ git-repo-delete ()
             return 1
         fi
 
-        builtin cd .. || ( cmd-echo "Cannot cd .." && return 1)
+        builtin cd .. || { cmd-echo "Cannot cd .." && return 1; }
         \rm -rf "$repo"
         status=$?
         ((status != 0)) && return 1; ## If the rm fails, we should see error
@@ -451,9 +454,9 @@ git-repo-delete ()
     ## Go there.
     if [ ! "$returnpath" = '/' ]
     then
-        builtin cd "$returnpath" || ( cmd-echo "Cannot cd $returnpath" && return 1)
+        builtin cd "$returnpath" || { cmd-echo "Cannot cd $returnpath" && return 1; }
     else
-        builtin cd ~ || ( cmd-echo "Cannot cd ~" && return 1)
+        builtin cd ~ || { cmd-echo "Cannot cd ~" && return 1; }
     fi
 
     ## Feed "there" back to the git function to make it stick.
@@ -683,14 +686,33 @@ git-repo-reset ()
     git-repo-restore "$@"
 }
 
+git-repo-revert ()
+{
+    git-repo-restore "$@"
+}
+
 git-repo-restore ()
 {
+    cmd-echo "Cleaning..."
     git dorealclean
+
+    cmd-echo "Unstaging..."
     declare -a files
     readarray -t files < <(git is committable)
     git reset HEAD -- "${files[@]}"
+
+    cmd-echo "Uncheckouting..."
     readarray -t files < <(git is modified)
     git checkout -- "${files[@]}"
+
+    cmd-echo "Status..."
+    git status
+
+}
+
+git-repo-tags ()
+{
+     git tag --list --sort=v:refname
 }
 
 main()
@@ -752,8 +774,9 @@ git-repo - act on or interrogate the current repo
  git-repo ina
  git-repo name
  git-repo pr-get
- git-repo reset/restore
+ git-repo reset/revert/restore
  git-repo sync
+ git-repo tags
 
  git-repo purge/prune [repo-dir [repo-dir]... ]
 
@@ -830,7 +853,7 @@ Print the name of the remote repo.
 
 Deal with pull requests related to the current repo. --get will look for an open pull request for this branch against remotes 'upstream' and then 'origin'. --silent will supress printing the PR reference so that you can just used the return value; 0 if there is an open pull request, 1 if not.
 
-=item restore
+=item revert/reset/restore
 
 Performs a realclean, resets all uncommitted changes.
 
@@ -850,6 +873,12 @@ pristine'. no) then it prompts to accept deleting the repo.
 **NOTE:** This probably belongs in git mono or a git repos command that would
   replace git mono. The git mono default of 'exec all of this for each repo'
   could be the --exec option of git repos.
+
+=item tags
+
+Show all the tags in ascending version order. Alias for
+
+  git tag --list --sort=v:refname
 
 =back
 
diff --git a/bin/git-worktree b/bin/git-worktree
--- a/bin/git-worktree
+++ b/bin/git-worktree
@@ -30,12 +30,12 @@ _git_worktree_check_set_pwd ()
     then
         if [ -d ./wt ]
         then
-            builtin cd ./wt || ( cmd-echo -- "Cannot cd ./wt" && return 1)
+            builtin cd ./wt || { cmd-echo -- "Cannot cd ./wt" && return 1; }
         elif [ -d ../../wt ] && ((opt_current_ok))
         then
-            builtin cd .. || ( cmd-echo -- "Cannot cd .. (wt)" && return 1)
+            builtin cd .. || { cmd-echo -- "Cannot cd .. (wt)" && return 1; }
         else
-            cmd-echo -- "Current directory is ${PWD}." \
+            cmd-echo --ec -- "Current directory is ${PWD}." \
                       'No wt subdir.' \
                       'Will not manipulate worktrees outside of wt dir. Aborting.'
             return 1
@@ -517,7 +517,7 @@ $(ls -la)"
     local wtpath
     wtpath="$wtroot/$wtname"
 
-    builtin cd "$wtpath" || ( cmd-echo -- "Cannot cd $wtpath" && return 1)
+    builtin cd "$wtpath" || { cmd-echo -- "Cannot cd $wtpath" && return 1; }
 
     ## Make sure we are in a proper worktree.
     if ! git-worktree-ina
@@ -534,7 +534,7 @@ $(ls -la)"
         then
             git status
             echo
-            cmd-echo -- "Will not delete unclean worktree. Clean worktree or re-run command with --force."
+            cmd-echo --ec -- "Will not delete unclean worktree. Clean worktree or re-run command with --force."
             return 1
         fi
     fi
@@ -564,7 +564,7 @@ $(ls -la)"
     ## Whack it. Start with the current dir, which is the worktree.
     local delit
     delit=$(basename "${PWD}")
-    builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
+    builtin cd .. || { cmd-echo -- "Cannot cd .." && return 1; }
     if ! rm -rf "$delit"
     then
         cmd-echo -- "Bad rm of ./$delit (from ${PWD}). Aborting."
@@ -579,8 +579,8 @@ $(ls -la)"
         then
             #it's empty
             delit=$(basename "${PWD}")
-            builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
-            \rm -rf "$delit" || cmd-echo -- "Bad rm of ./$delit (from ${PWD}). Aborting." && return 1;
+            builtin cd .. || { cmd-echo -- "Cannot cd .." && return 1; }
+            \rm -rf "$delit" || { cmd-echo -- "Bad rm of ./$delit (from ${PWD}). Aborting." && return 1; }
         fi
     done
 
@@ -607,9 +607,9 @@ $(ls -la)"
         ## Have to be in the git repo that the basis for the worktree.
         while [ "$(basename "${PWD}")" != 'wt' ]
         do
-            builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
+            builtin cd .. || { cmd-echo -- "Cannot cd .." && return 1; }
         done
-        builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
+        builtin cd .. || { cmd-echo -- "Cannot cd .." && return 1; }
         if [ "$resp" = 'y' ]
         then
             git-branch delete --no-go-set $opt_yes_string "$current_branch"
@@ -714,13 +714,12 @@ $(ls -la)"
     local new_wtname="$1" ; shift
     if [ -d "$new_wtname" ]
     then
-        cmd-echo -- "Will not overwrite existing worktree $new_wtname
+        cmd-echo --ec -- "Will not overwrite existing worktree $new_wtname
 $(ls -la)"
         return 1
     fi
     local new_wtpath="$wtroot/$new_wtname"
-
-    builtin cd "$old_wtpath" || ( cmd-echo -- "Cannot cd $old_wtpath" && return 1)
+    builtin cd "$old_wtpath" || { cmd-echo -- "Cannot cd $old_wtpath" && return 1; }
     local cb
     cb="$(git branch --show-current)"
     if [ "$cb" = "$old_wtname" ]
@@ -756,7 +755,7 @@ $(ls -la)"
 
     cmd-echo -- "Moving the local files..."
     ## Move us
-    builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
+    builtin cd .. || { cmd-echo -- "Cannot cd .." && return 1; }
     mv "$old_wtpath" "$new_wtpath" || return 1
 
     ## Register the rename
@@ -957,7 +956,7 @@ $(ls -la)"
     local wtpath
     wtpath="$wtroot/$wtname"
 
-    builtin cd "$wtpath" || ( cmd-echo -- "Cannot cd $wtpath" && return 1)
+    builtin cd "$wtpath" || { cmd-echo -- "Cannot cd $wtpath" && return 1; }
 
     # shellcheck disable=SC2119
     if ! git-worktree-ina
