func to exec, convert phase

diff --git a/bin/git-branch-list b/bin/git-branch-list
--- a/bin/git-branch-list
+++ b/bin/git-branch-list
@@ -1,41 +1,37 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-branch-list
 
-git-branch-list ()
-{
-    ##@@ 0001||group||git-branch-list||
+##@@ 0001||group||git-branch-list||
 
-    local strip=0
-    local remote=''
-    local OPTSARGS=$(getoptp -o ra --long strip,nostrip,remote,all -n $FUNCNAME -- "$@")
-    status=$?
-    ((status != 0)) && func-echo "Exiting." && return $status
-    eval set -- "$OPTSARGS"
-    while true
-    do
-        case "$1" in
-            -a | --all) remote='-a'; shift;;
-            -r | --remote) remote='-r'; shift;;
-            --strip) strip=1; shift;;
-            --nostrip) strip=0; shift;;
-            --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) echo "Internal error!"; return $NOT_OK ;;
-        esac
-    done
+declare strip=0
+declare remote=''
+declare OPTSARGS=$(getoptp -o ra --long strip,nostrip,remote,all -n $FUNCNAME -- "$@")
+status=$?
+((status != 0)) && func-echo "Exiting." && exit $status
+eval set -- "$OPTSARGS"
+while true
+do
+    case "$1" in
+        -a | --all) remote='-a'; shift;;
+        -r | --remote) remote='-r'; shift;;
+        --strip) strip=1; shift;;
+        --nostrip) strip=0; shift;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; exit $NOT_OK ;;
+    esac
+done
 
-    ## Update the local branches with remote. Shunt away the output - not
-    ## needed, interferes with functions that call git-branch-list and read the
-    ## output.
-    git remote update > /dev/null
+## Update the declare branches with remote. Shunt away the output - not
+## needed, interferes with functions that call git-branch-list and read the
+## output.
+git remote update > /dev/null
 
-    local opts="--list $remote"
-    if ((strip))
-    then
-        git branch --no-color $opts | sed 's/^[ *] //' | sed 's/ .*//'
-    else
-        git branch $opts
-    fi
+declare opts="--list $remote"
+if ((strip))
+then
+    git branch --no-color $opts | sed 's/^[ *] //' | sed 's/ .*//'
+else
+    git branch $opts
+fi
 
-}
