Updated exit handling

diff --git a/bin/git-pre-commit-hook b/bin/git-pre-commit-hook
--- a/bin/git-pre-commit-hook
+++ b/bin/git-pre-commit-hook
@@ -10,11 +10,11 @@
 ## Don't do my checks if I say not to.
 if [[ "$GIT_COMMIT_NO_VERIFY" = '1' ]]; then
     echo "****** GIT_COMMIT_NO_VERIFY='1'. Skipping hook. ******" >&2
-    exit 0
+    true; exit
 fi
 
 ## Don't do my checks if Perl testing involves git commands.
-[ "$HARNESS_ACTIVE" = '1' ] && exit 0
+[ "$HARNESS_ACTIVE" = '1' ] && { true; exit; }
 
 ##
 ## Globals and inits
@@ -28,7 +28,7 @@ G_tfile=$(mktemp)
 ## ...and we set up a trap for cleanup.
 trap finish EXIT SIGINT
 
-declare G_exitval=0 ## Assume correctness.
+true; declare G_exitval=$? ## Assume correctness.
 
 declare G_gitroot
 G_gitroot=$(git rev-parse --show-toplevel)
@@ -72,7 +72,7 @@ check ()
         echo
         pre_commit_error_echo "$errmsg"
         cat "$G_tfile"
-        G_exitval=1
+        false; G_exitval=$?
         if [[ -n $postmsg ]]; then
             echo
             echo "$postmsg"
@@ -184,13 +184,13 @@ do_gcs_check ()
         echo
         pre_commit_error_echo "${gcs_messages[0]}"
         pre_commit_error_echo -c "${gcs_files[0]}"
-        G_exitval=1
+        false; G_exitval=$?
     fi
     if [[ -n ${gcs_files[1]} ]]; then
         echo
         pre_commit_error_echo "${gcs_messages[1]}"
         pre_commit_error_echo -c "${gcs_files[1]}"
-        G_exitval=1
+        false; G_exitval=$?
     fi
     if [[ -n ${gcs_files[2]} ]]; then
         echo
@@ -243,7 +243,7 @@ that you can skip with:
 
 Skips: $GIT_HOOK_SKIP_TAGS
 EOF
-                exit 0;
+                true; exit 0
                 ;;
             s|skip)
                 if [[ "$GIT_HOOK_SKIP_TAGS" == *" $1 "* ]]; then
@@ -267,11 +267,11 @@ EOF
                     pre_commit_ok_echo "--help not allowed in GIT_PRE_COMMIT_HOOK_ARGS. Ignoring."
                 else
                     pod2text "$0" | ${PAGER:cat}
-                    exit 0
+                    true; exit
                 fi
                 ;;
             --) shift; break ;; ## end of opts, remaining $*, if any, are args.
-            *) echo "Internal error!"; pod2text "$0" | ${PAGER:cat}; exit 1 ;;
+            *) echo "Internal error!"; pod2text "$0" | ${PAGER:cat}; false; exit ;;
         esac
     done
 
@@ -651,11 +651,10 @@ for (@ARGV){
     ##
     ## Done.
     ##
-
-    if ((G_exitval==0)); then
+    true; if ((G_exitval==$?)); then
         if((opt_nocommit)); then
             pre_commit_ok_echo 'No errors, but --nocommit specified. Commit will be aborted.'
-            G_exitval=1
+            false; G_exitval=$?
         else
             pre_commit_ok_echo 'Commit will proceed.'
         fi
diff --git a/bin/sedinplace b/bin/sedinplace
--- a/bin/sedinplace
+++ b/bin/sedinplace
@@ -38,9 +38,7 @@ declare shortopts='kcbvn:'
 declare longopts='keepscript,confirm,backup,verbose,new:'
 
 # Process the command line.
-OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "$(basename "$0")" -- "$@")
-declare status=$?
-((status != 0)) && exit $status
+OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "$(basename "$0")" -- "$@") || exit
 
 # Reset the command line ($@).
 eval set -- "$OPTSARGS"
@@ -75,7 +73,7 @@ while true; do
                      ## remaining $*, if any, are args
         *)
             cmd-echo --id sedinplace -ec -- "$option is an invalid option. See $0 --help"
-            exit 1
+            false; exit
             ;;
     esac
 done
@@ -108,11 +106,9 @@ if [[ $opt_verbose = 1 ]]; then
 fi
 
 sedopts="$sedopt_inplace"
-sed $sedopts -f "$sedcmdfile" "${files[@]}"
-status=$?
-if [[ $status != 0 ]]; then
-    exitstatus=$status
-    cmd-echo --id sedinplace -- "Sed editor. Status $status." \
+if ! sed $sedopts -f "$sedcmdfile" "${files[@]}"; then
+    exitstatus=$?
+    cmd-echo --id sedinplace -- "Sed editor. Status $exitstatus." \
              "The directory where the files live must be writable" \
              "for sed's temporaries and the final product."
 fi
@@ -127,8 +123,8 @@ for f in "${files[@]}"; do
             fi
 		    \rm "${f}.sip"
         elif ((opt_new)); then
-            \mv "${f}" "${f}.${opt_new}";status=$?;((status)) && cmd-echo --id sedinplace -- "Rename ${f} ${f}.${opt_new} error. Exiting." && exit 1
-            \mv "${f}.sip" "${f}";status=$?;((status)) && cmd-echo --id sedinplace -- "Rename ${f}.sip ${f} error. Exiting." && exit 1
+            \mv "${f}" "${f}.${opt_new}";status=$?;((status)) && cmd-echo --id sedinplace -- "Rename ${f} ${f}.${opt_new} error. Exiting." && { false; exit; }
+            \mv "${f}.sip" "${f}";status=$?;((status)) && cmd-echo --id sedinplace -- "Rename ${f}.sip ${f} error. Exiting." &&  { false; exit; }
             ((opt_verbose)) && cmd-echo --id sedinplace -- "${f}.${opt_new}"
         elif ((opt_confirm)); then
             cmd-echo --id sedinplace
diff --git a/bin/tarcopy b/bin/tarcopy
--- a/bin/tarcopy
+++ b/bin/tarcopy
@@ -26,17 +26,17 @@ while [[ "$1" =~ ^- ]] && ((moreopts)); do
             ;;
         help )
             bash-usage "$0"
-            exit 0
+            true; exit
             ;;
         * )
-            echo "$original is an invalid option. See $0 --help"; exit 1;;
+            echo "$original is an invalid option. See $0 --help"; false; exit ;;
     esac
 done
 
 if (($#<2)); then
     echo "Not enough arguments."
     bash-usage "$0"
-    exit 1
+    false; exit
 fi
 
 declare tgtdir
@@ -44,10 +44,10 @@ tgtdir="${*: -1}"
 if [[ ! -d "$tgtdir" ]]; then
     if ((make_tgt)); then
         echo "Target '$tgtdir' does not exist. Will be created, as requested."
-        mkdir -p "$tgtdir" || exit $?
+        mkdir -p "$tgtdir" || exit
     else
         echo "Target '$tgtdir' must be an existing directory, or use --make-tgt to request its creation."
-        exit 1
+        false; exit
     fi
 else
     if ((make_tgt)); then
@@ -58,7 +58,7 @@ fi
 ## -B - reblock
 ## -C - instead of (cd "tgtdir"; tar...)
 tar cf - "${@:1:$# - 1}" | tar -C "$tgtdir" "${ext_tar_opts[@]}" -B -xf -
-exit $?
+exit
 
 :<<'__PODUSAGE__'
 =head1 NAME
