Periodic
bin/git-branch
* Format to ';then'.
* Change our git config item prefix from 'extmeta' to
  $GIT_EXT_META_PREFIX for consistency.

bin/git-clone
* Format to ';then'.
* Change our git config item prefix from 'extmeta' to
  $GIT_EXT_META_PREFIX for consistency.

main():
  * added --fork-of.

bin/git-comment
* Format to ';then'.
* Change our git config item prefix from 'em' to $GIT_EXT_META_PREFIX for
  consistency.
* Default datestamp to off.

bin/git-commit
* Format to ';then'.
* Added more aliases for --sclonly and --nosclonly.

bin/git-go-set
* Redirect cmd-echo warning to stderr so as not to interfere with the
  command output.
* Filter out files in repo path locations.

bin/git-push
* Format to ';then'.
* Change our git config item prefix from 'extmeta' to
  $GIT_EXT_META_PREFIX for consistency.

bin/git-repo
* Format to ';then'.
* Change our git config item prefix from 'extmeta' to
  $GIT_EXT_META_PREFIX for consistency.

git-repo-default-branch():
  * Updated to handle non-clones.

git-repo-is_fork():
  * Removed forkof and fork_of variants in favor of checking $1 equaling
    'of', just like 'is_worktree'.

git-repo-pr-get():
  * Without a PR, don't do the remote lookup more than once a day. Or else
    fix it do so that when you create a PR, you write it and don't wait for
    the nectx info go-around to fillit.

bin/git-status-ext
* Format to ';then'.
* Added more aliases for --sclonly and --nosclonly.

bin/git-status-with-source-ctrl-log
* Format to ';then'.
* Added more aliases for --sclonly and --nosclonly.

bin/git-worktree
* Format to ';then'.
* Change our git config item prefix from 'extmeta' to
  $GIT_EXT_META_PREFIX for consistency.

git-worktree-create():
  * Change the --message flag to --comment so as not to confuse it with
    commit comments and fix the call so it actually works.

bin/uuid
* Convert from a shell that only makes a perl -e call to a perl script.

functions/dirlist
* Format to ';then'.

dirlist():
  * Restored "no arg means 'cd $home'" functionality. Old functionality of
    bringing up the menu is now accessed with an option of -m.

functions/go
* Alias go- for 'go ' is replaced with 'gom' for 'go -m' which gives the
  menu, because now 'go ' does 'go $HOME'.

diff --git a/bin/git-go-set b/bin/git-go-set
--- a/bin/git-go-set
+++ b/bin/git-go-set
@@ -2,8 +2,7 @@
 
 # git-go-set
 
-if [[ $1 =~ -h ]]
-then
+if [[ $1 =~ -h ]]; then
     bash-usage "$0"
     exit 0
 fi
@@ -13,12 +12,14 @@ fi
 # produce a specific sort order.
 declare -a repo_paths
 mapfile -t repo_paths < <(git config --value-only --expand --get-regexp ext.git-repo-paths.path)
-
 for repo_path in "${repo_paths[@]}"
 do
-    if [[ ! -d $repo_path ]]
-    then
-        cmd-echo --wc -- "$repo_path not found. Consider removing its root from the 'ext.git-repo-paths.path' entry in git config."
+    if [[ -f $repo_path ]]; then
+        ## ignore random files
+        continue
+    fi
+    if [[ ! -d $repo_path ]]; then
+        cmd-echo --wc -- "$repo_path not found. Consider removal from the 'ext.git-repo-paths.path' entry in git config." >&2
         continue
     fi
     # Search the expanded paths for repos and work trees by finding '.git'
@@ -31,8 +32,7 @@ do
                 <(find "${repo_path}/wt" -maxdepth 2 -name .git | sort -u | sed 's/\/.git$//g')
 done
 
-if [[ $1 != -p ]]
-then
+if [[ $1 != -p ]]; then
     # Write the list.
     declare gitfuncs_git_go_file
     gitfuncs_git_go_file="${TILDAE:-$HOME}/gits/.git-go.$(date +%Y%m%d)"
