func to exec, convert phase

diff --git a/bin/git-daily-repo-check b/bin/git-daily-repo-check
--- a/bin/git-daily-repo-check
+++ b/bin/git-daily-repo-check
@@ -1,24 +1,21 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-daily-repo-check
 
-git-daily-repo-check () {
-    local repo=$1; shift;
-    [ -z "$repo" ] && echo "Missing repo location arg. Exiting." && return 1
-    ( ## to isolate 'cd' effects
-        cd $repo
-        local repo_key="$(echo $(date +%Y%m%d;echo :;git st --porcelain | sha1sum) |  sed 's/ //g')"
-        local repo_key_cache='.git-daily-repo-check.marker'
-        local repo_key_last
-        [ -r $repo_key_cache ] && repo_key_last=$(cat $repo_key_cache 2>/dev/null)
-        if [ ! "$repo_key_last" = "$repo_key" ]
-        then
-            echo "** Check $(pwd) against master ***"
-            git-check-with-master --bail_on_dirty
-            echo "** Check $(pwd) against itself ***"
-            git status
-            echo $repo_key > $repo_key_cache
-        fi
-    )
-}
+declare repo=$1; shift;
+[ -z "$repo" ] && echo "Missing repo location arg. Exiting." && exit 1
+( ## to isolate 'cd' effects
+    cd $repo
+    declare repo_key="$(echo $(date +%Y%m%d;echo :;git st --porcelain | sha1sum) |  sed 's/ //g')"
+    declare repo_key_cache='.git-daily-repo-check.marker'
+    declare repo_key_last
+    [ -r $repo_key_cache ] && repo_key_last=$(cat $repo_key_cache 2>/dev/null)
+    if [ ! "$repo_key_last" = "$repo_key" ]
+    then
+        echo "** Check $(pwd) against master ***"
+        git-check-with-master --bail_on_dirty
+        echo "** Check $(pwd) against itself ***"
+        git status
+        echo $repo_key > $repo_key_cache
+    fi
+)
