bin/cron-wrapper bin/git.mopenv bin/gitsync.cron bin/rsync.mopenv functions/gitremote-forknclone * TILDAE removal.
bin/monkeypatch
dotfiles/bash_profile
dotfiles/bashrc
dotfiles/bashrcuser
dotfiles/dotfiles.manifest
dotfiles/profile
* Profile/bashrc consolidation.

bin/git-commit
* Message and call corrections.

bin/git-mono
* Added the --dir option for wt diretories.

bin/git-pre-commit-hook
* Wrong-perl-version messages are on stderr, so add stderr to the file
  used to scan for errors.
* Enhanced shellcheck output with file name list.

bin/git-push
* Shellcheck.
* Always run real git push first.

bin/git-worktree
  * Eliminate a workism.

diff --git a/bin/git-mono b/bin/git-mono
--- a/bin/git-mono
+++ b/bin/git-mono
@@ -37,6 +37,10 @@ set_repos ()
                 repos_unique[$matched]=1
             done
         done
+    elif [[ "$option" == 'dir' ]]; then
+        for key in $(find "$repo" -maxdepth 1 -type d | grep -v -E "^$repo$"); do
+            repos_unique[$key]=1
+        done
     else
         for repo in "${repos_tmp[@]}"; do
             repos_unique[$repo]=1
@@ -50,7 +54,6 @@ set_repos ()
 
 main ()
 {
-    local moreopts=1
     local quiet=0
     local silent=0
     local opt_repo
@@ -59,27 +62,21 @@ main ()
     local repo
     local opt_rcge=-1
     local opt_wt=''
-    fmt=''
-    while [[ "$1" =~ ^- ]] && ((moreopts)); do
-        local original="$1"
-        shift
-        local option
-        option=$(dashstripper "$original")
-        ## This bit deals with --foo=bar instead of --foo bar
-        local okey=''
-        local ovalue=''
-        ## but only deal with it if we really have an option. Otherwise you
-        ## misinterpret items like this git clone option: --config
-        ## "remote.origin.fetch=+refs/pull/*/head:refs/remotes/origin/pr/*'
-        if [[ $option =~ ^- ]]; then
-            if [[ "$option" =~ = ]]; then
-                okey=${option%%=*}
-                ovalue=${option#*=}
-                option="$okey"
-            fi
-        fi
 
-        case $option in
+    local OPTSARGS
+    local shortopts='ur:phqsx'
+    local longopts='update,nowt,wto,all,rp:,repo:,repo-patt:,pause,help,quiet,silent,rcge:,dir:'
+
+    if ! OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "${FUNCNAME[0]}" -- "$@"); then
+        git-usage "$0"
+        false; return
+    fi
+
+    eval set -- "$OPTSARGS"
+    while true; do
+        option=$(dashstripper "$1")
+        shift
+        case "$option" in
             u | update )
                 opt_update=1
                 ;;
@@ -91,9 +88,12 @@ main ()
                 ovalue=':all'
                 ;& # unconditional drop-through
             r | rp | repo | repo-patt )
-                opt_repo=${ovalue:-$1}
-                [[ -z "$ovalue" ]] && shift
+                opt_repo=$1; shift
                 set_repos "$opt_repo" "$option" "$opt_wt"
+                ;;
+            dir )
+                repos_dir=$1; shift
+                set_repos "$repos_dir" "$option" "$opt_wt"
                 ;;
             p | pause )
                 opt_pause=1
@@ -116,17 +116,15 @@ main ()
             rcge )
                 quiet=0
                 silent=0
-                opt_rcge=${ovalue:-$1}
-                [[ -z "$ovalue" ]] && shift
+                opt_rcge=$1; shift
                 ;;
             x ) set -x # OK if you are grepping
                 do_on_exit set +x # OK if you are grepping
                 ;;
-            --)
-                moreopts=0
-                ;;
-            * )
-                cmd-echo --id git-mono -- "$original is an invalid option. See $0 --help"
+            --) break ;; ## VITAL!!! Exits the while loop, no more options,
+                         ## remaining $*, if any, are args
+            *)
+                cmd-echo --id git-branch -ec -- "$option is an invalid option. See 'git-branch --help'."
                 false; exit
                 ;;
         esac
@@ -214,7 +212,7 @@ main ()
             fi
             local line
             while read -r line; do
-                echo "$(eval echo ${fmt})${line}"
+                echo "$(eval echo "${fmt}")${line}"
             done < "$t"
         fi
         ((opt_pause)) && cmd-pause "Return to continue..."
@@ -268,6 +266,11 @@ specified, we will execute over all repos found via 'git go --listfull'.
 =item --all
 
 Same as -r :all
+
+=item --dir
+
+The argument is a directory in which the subdirectories are repos. Good for
+'wt' directories.
 
 =item --quiet
 
