func to exec, convert phase

diff --git a/bin/git-find b/bin/git-find
--- a/bin/git-find
+++ b/bin/git-find
@@ -1,52 +1,52 @@
 # -*- sh -*-
+# shellcheck shell=bash
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-find
 
-git-find ()
-{
-    ##@@ 0001||group||git-find||A convenience function around: git ls-files $(git rev-parse --show-toplevel) | grep -E fileExpression'
+##@@ 0001||group||git-find||A convenience function around: git ls-files $(git rev-parse --show-toplevel) | grep -E fileExpression'
 
-    local usage_func="${FUNCNAME}-usage"
+declare opt_untracked_only
+opt_untracked_only=0
+declare opt_all
+opt_all=0
+OPTSARGS=$(getoptp -o auh --long all,untracked-only,help -n "$(basename "$0")" -- "$@")
+declare status
+status=$?
+((status != 0)) && script-usage && exit $status
 
-    local opt_untracked_only=0
-    local opt_all=0
-    OPTSARGS=$(getoptp -o auh --long all,untracked-only,help -n $FUNCNAME -- "$@")
-    local status=$?
-    ((status != 0)) && $usage_func && return $status
+eval set -- "$OPTSARGS"
+while true
+do
+    case "$1" in
+        --untracked_only|-u) opt_untracked_only=1; shift ;;
+        --all|-a) opt_all=1; shift ;;
+        -h|--help) script-usage; exit "$OK" ;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; script-usage; exit "$NOT_OK" ;;
+    esac
+done
 
-    eval set -- "$OPTSARGS"
-    while true
-    do
-        case "$1" in
-            --untracked_only|-u) opt_untracked_only=1; shift ;;
-            --all|-a) opt_all=1; shift ;;
-            -h|--help) $usage_func; return $OK ;;
-            --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) echo "Internal error!"; $usage_func; return $NOT_OK ;;
-        esac
-    done
+if [ "$opt_untracked_only" = 1 ] && [ "$opt_all" = 1 ]
+then
+    echo "--untracked_only and --all are mutually exclusive"
+    script-usage
+    exit 1
+fi
 
-    if [ "$opt_untracked_only" = 1 ] && [ "$opt_all" = 1 ]
-    then
-        echo "--untracked_only and --all are mutually exclusive"
-        $usage_func
-        exit 1
-    fi
+declare ls_files_opts
+ls_files_opts="-c"
+if [ "$opt_untracked_only" = 1 ]
+then
+    ls_files_opts="-o"
+elif [ "$opt_all" = 1 ]
+then
+    ls_files_opts="-c -o"
+fi
 
-    local ls_files_opts="-c"
-    if [ "$opt_untracked_only" = 1 ]
-    then
-        ls_files_opts="-o"
-    elif [ "$opt_all" = 1 ]
-    then
-        ls_files_opts="-c -o"
-    fi
-
-    local to_find='*'
-    [ -n "$@" ] && to_find="$@"
-    for f in "$@"
-    do
-        git ls-files $ls_files_opts $(git rev-parse --show-toplevel) | grep -E "$f" | sort
-    done
-}
+declare -a to_find
+mapfile -t to_find < <(ls)
+[ -n "$1" ] && to_find=("$@")
+for f in "${to_find[@]}"
+do
+    git ls-files "$ls_files_opts" "$(git rev-parse --show-toplevel)" | grep -E "$f" | sort
+done
