Periodic
bin/autoload
_autoload_edit():
  o Fixup arg construction with a bash array.

bin/cat_history
o Updated script-echo init call.

bin/comment-stream
o Updated script-echo init call.

bin/from-ext
o Updated script-echo init call.

bin/func-to-exec
o Updated script-echo init call.

bin/func-to-exec.pl
o Changed script-echo init to use the generic $0 reference instead of the
  actual script name.

bin/git-branch
o func-echo -i "${FUNCNAME[0]}"

bin/git-check-with-remote
o Updated script-echo init call.

bin/git-clone
o Updated script-echo init call.

bin/git-commit-with-changelog
o Updated script-echo init call.

bin/git-diff-two-repos-on-disk
o Updated script-echo init call.

bin/git-find
o Added script-echo init call.

bin/git-ping
o Added script-echo init call.

bin/git-post-new
o Updated script-echo init call.

bin/git-process-changelog
o Updated script-echo init call.

bin/git-rebase-log
o Added script-echo init call.

bin/git-status-ext
o Added script-echo -i.

bin/git-status-with-changelog
o Updated script-echo init call.

bin/git-sync-with-master
o Updated script-echo init call.

bin/git-sync-with-remote
o Updated script-echo init call.

bin/git-to-stdout-last-existed
o Updated script-echo init call.

bin/git-worktree
o Fixed pod.
o Converted to func-echo from script-echo.

bin/hist.alias
count-history():
  o Added function that counts history commands.

bin/logit
o Shellcheck induced args bug fixed.
o -tpef added.

bin/perl.env
o Shellcheck. Disable ptkdb font stuff for mac xserver.

bin/script-echo
o Route the debug output to stderr.
o More fixups for the '-- at the start of the message' issue.
o Remove verbose. Remove the --opt=arg processing, just allow --opt arg.
  Carp when CMD_ECHO_AS is empty.
o Only call cmd-echo if there are args to print; there shouldn't be any
  if -i is used.
o Fixed option pass-along.
o Added -o for overrride of the name to print.

bin/script-yesno
o Pull the script-echo init call - not needed, interferes with output.

bin/todo
o todo md/html thingy.
o With no args, default now is to edit.

bin/xo
o Updated script-echo init call.

functions/cmd-echo
cmd-echo():
  o Added -o override option.

functions/func-echo
o Route the debug output to stderr.
o Sync up with script-echo as per arg/opt handling.
o Added -o for overrride of the name to print.

func-echo():
  o Fixed option pass-along.

functions/func-usage
o func-echo call gets override to this function no matter what's calling
  it

functions/git-delete-repo
o func-echo -i "${FUNCNAME[0]}"

functions/git-go
o Correct to allow wto as shortcut.
o Add -size for list of repos sorted by size large to small.
o Changed --stat to just run stat --porcelain. Added --dirty to print
  only where stat --porcelain is not empty.
o func-echo -i "${FUNCNAME[0]}"

functions/git-hold
o func-echo -i "${FUNCNAME[0]}"

functions/git-hold-diff
o func-echo -i "${FUNCNAME[0]}"

functions/git-hold-remove
o func-echo -i "${FUNCNAME[0]}"

functions/git-hold-restore
o func-echo -i "${FUNCNAME[0]}"

functions/git-merge-find
o Removed all the set +x statements. Fixed the getopts call.

functions/git-merge-pull-request
o func-echo -i "${FUNCNAME[0]}"

functions/git-pull
o func-echo -i "${FUNCNAME[0]}"

functions/git-to-stdout
o func-echo -i "${FUNCNAME[0]}"

functions/git-worktree-diff-to-root
o func-echo -i "${FUNCNAME[0]}"

functions/script-usage
o func-echo call gets override to this function no matter what's calling
  it.

diff --git a/bin/git-branch b/bin/git-branch
--- a/bin/git-branch
+++ b/bin/git-branch
@@ -10,6 +10,7 @@
 ## last and called last.
 git-branch-delete ()
 {
+    func-echo -i "${FUNCNAME[0]}"
     declare no_remote
     no_remote=0
     declare opt_yes
@@ -30,7 +31,7 @@ git-branch-delete ()
             --no-go-set) do_go_set=0; shift ;;
             -h|--help) script-usage; return 0 ;;
             --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) script-echo "Internal error!"; script-usage; return 1 ;;
+            *) func-echo "Internal error!"; script-usage; return 1 ;;
         esac
     done
 
@@ -44,7 +45,7 @@ git-branch-delete ()
         readarray -t branchesa < <(git-branch-list --strip)
         if [ ${#branchesa[@]} == '0' ]
         then
-            script-echo "No branches found. Are you in a git repo?"
+            func-echo "No branches found. Are you in a git repo?"
             return 1
         fi
         declare PS3
@@ -57,7 +58,7 @@ git-branch-delete ()
             then
                 if [ "$selected" == "$current_branch" ]
                 then
-                    script-echo -- "$selected is current. Cannot delete current."
+                    func-echo -- "$selected is current. Cannot delete current."
                 else
                     branch=$selected
                     break
@@ -66,7 +67,7 @@ git-branch-delete ()
             then
                 return 0
             else
-                script-echo "'$REPLY' is an invalid choice"
+                func-echo "'$REPLY' is an invalid choice"
             fi
         done
     fi
@@ -76,7 +77,7 @@ git-branch-delete ()
         ## $branch was either $1 or we did not ctrl-c out of the select.
         if [ "$branch" = "$current_branch" ]
         then
-            script-echo "Nope, you can't delete the current branch."
+            func-echo "Nope, you can't delete the current branch."
             return 1
         fi
 
@@ -85,10 +86,10 @@ git-branch-delete ()
         brdelstat=$?
         if ((brdelstat))
         then
-            script-echo "ERROR: git branch -d $branch failed. Returning $brdelstat."
+            func-echo "ERROR: git branch -d $branch failed. Returning $brdelstat."
             return $brdelstat
         fi
-        script-echo "Branch deleted locally."
+        func-echo "Branch deleted locally."
 
         if [ "$no_remote" = '1' ]
         then
@@ -118,10 +119,10 @@ git-branch-delete ()
                     brdelstat=$?
                     if ((brdelstat))
                     then
-                        script-echo "ERROR: git push --delete $remote $branch failed. Returning $brdelstat."
+                        func-echo "ERROR: git push --delete $remote $branch failed. Returning $brdelstat."
                         return $brdelstat
                     fi
-                    script-echo "Branch deleted remotely."
+                    func-echo "Branch deleted remotely."
                 fi
             fi
         done
@@ -134,9 +135,10 @@ git-branch-delete ()
 
 git-branch-rename ()
 {
+    func-echo -i "${FUNCNAME[0]}"
     if (($#!=2))
     then
-        script-echo "Need current and new branch names"
+        func-echo "Need current and new branch names"
         script-usage
         return 1
     fi
@@ -166,6 +168,7 @@ git-branch-rename ()
 
 git-branch-info ()
 {
+    func-echo -i "${FUNCNAME[0]}"
     local branch
     branch=$(git rev-parse --abbrev-ref HEAD)
     local timestamp=''
@@ -224,6 +227,7 @@ git-branch-info ()
 
 git-branch-get-current ()
 {
+    func-echo -i "${FUNCNAME[0]}"
     ( if [ -n "$1" ]
       then
           ## dirlist, not builtin cd, to take advantage this cd enhancement
@@ -236,6 +240,7 @@ git-branch-get-current ()
 
 git-branch-orphan()
 {
+    func-echo -i "${FUNCNAME[0]}"
     ##Create an empty branch, for tools you want to keep, but not publish
     declare remote=origin
     declare branch=$1; shift
@@ -261,47 +266,50 @@ git-branch-orphan()
 
 git-branch-track-remote ()
 {
-     declare remote=$1
-     declare branch=$2
-     declare local_branch=$3
-     if [ -z "$remote" ] || [ -z "$branch" ]
-     then
-         echo "Usage: git-track-remote-branch remote branch [localbranch]"
-         echo "       Missing one or both arguments (remote, branch)"
-         return 1
-     fi
-     [ -z "$local_branch" ] && local_branch=$branch
+    func-echo -i "${FUNCNAME[0]}"
+    declare remote=$1
+    declare branch=$2
+    declare local_branch=$3
+    if [ -z "$remote" ] || [ -z "$branch" ]
+    then
+        echo "Usage: git-track-remote-branch remote branch [localbranch]"
+        echo "       Missing one or both arguments (remote, branch)"
+        return 1
+    fi
+    [ -z "$local_branch" ] && local_branch=$branch
 
-     declare local_branch_exists
-     local-branch_exists="$(git branch --list "$local_branch")"
-     if [ -z "$local_branch_exists" ]
-     then
-         ## Does not exists, create and track
-         git checkout -b "$local_branch" --track "$remote/$branch"
-     else
-         declare already_tracking_remote
-         already_tracking_remote="$(git config branch."$local_branch".remote)"
-         if [ -z "$already_tracking_remote" ]
-         then
-             ## Exists, not tracking, track
-             git branch --set-upstream-to "$remote/$branch" "$local_branch"
-         else
-             declare already_tracking_branch
-             already_tracking_branch=$(git config branch."$local_branch".merge | sed 's|refs/heads/||')
-             echo "Branch $local_branch is already tracking $already_tracking_branch in $already_tracking_remote"
-             return 1
-         fi
-     fi
-     return $?
+    declare local_branch_exists
+    local-branch_exists="$(git branch --list "$local_branch")"
+    if [ -z "$local_branch_exists" ]
+    then
+        ## Does not exists, create and track
+        git checkout -b "$local_branch" --track "$remote/$branch"
+    else
+        declare already_tracking_remote
+        already_tracking_remote="$(git config branch."$local_branch".remote)"
+        if [ -z "$already_tracking_remote" ]
+        then
+            ## Exists, not tracking, track
+            git branch --set-upstream-to "$remote/$branch" "$local_branch"
+        else
+            declare already_tracking_branch
+            already_tracking_branch=$(git config branch."$local_branch".merge | sed 's|refs/heads/||')
+            echo "Branch $local_branch is already tracking $already_tracking_branch in $already_tracking_remote"
+            return 1
+        fi
+    fi
+    return $?
 }
 
 git-branch-fetch-remote ()
 {
+    func-echo -i "${FUNCNAME[0]}"
     git-branch-track-remote "$@"
 }
 
 git-branch-list ()
 {
+    func-echo -i "${FUNCNAME[0]}"
     local strip=0
     local remote=''
     local OPTSARGS
@@ -374,7 +382,15 @@ git-branch - git extention of git branch
 
 =head1 SYNOPSIS
 
+ git branch delete oldBranch
  git branch rename currentBranch newbranch
+ git branch info
+ git branch get current
+ git branch orphan
+ git branch track remote
+ git branch fetch remote
+ git branch list
+
 
 =head1 DESCRIPTION
 
diff --git a/functions/git-go b/functions/git-go
--- a/functions/git-go
+++ b/functions/git-go
@@ -5,14 +5,20 @@
 
 git-go ()
 {
+    # shellcheck disable=SC1090
+    source "$BASH_INC_DIR/on_exit.binc"
+
+    func-echo -i "${FUNCNAME[0]}"
+
     local PS3="Choose by number, /string to rematch, q to quit: "
     local -a git_get_opts
     local opt_list=0
     local opt_wt='-w'
     local opt_subwt_only=''
-    local opt_gse=0
+    local opt_stat=0
     local opt_mod=0
     local opt_exact=''
+    local opt_size=0
     local moreopts
     moreopts=1
     while [[ "$1" =~ ^- ]] && ((moreopts))
@@ -31,14 +37,16 @@ git-go ()
             eh | exact-head ) opt_exact='--exact-head';;
             l | list ) opt_list=1 ;;
             listfull ) opt_list=2 ;;
+            size ) opt_size=1; opt_list=1 ;;
             m | mbig ) git_get_opts+=('-m') ;;
             r | roots ) git_get_opts+=('-r') ;;
             u | update ) git_get_opts+=('-u') ;;
             wt ) opt_wt='-w' ;;
             nowt ) opt_wt='' ;;
             subwt ) opt_subwt_only='-o' ;;
-            wtonly ) opt_subwt_only='-o' ;;
-            stat ) opt_gse=1; opt_list=1 ;;
+            wto* ) opt_subwt_only='-o' ;;
+            stat ) opt_stat=1; opt_list=1 ;;
+            dirty ) opt_stat=2; opt_list=1 ;;
             mod ) opt_mod=1;;
             h | help ) func-usage git-go; return 0 ;;
             -- ) moreopts=0; break ;; ## end of opts, remaining $*, if any, are args
@@ -100,29 +108,39 @@ git-go ()
         elif ((opt_list))
         then
             local r
-            local gse
-            local sched
-            local rr
+            if ((opt_size))
+            then
+                ## Re-sort the list of repos by size descending using
+                ## byte-level counts.
+                repos_size=$(mktemp --suffix=.git-go.size)
+                rm_on_exit "$repos_size"
+                for r in "${REPOS[@]}"
+                do
+                    du -s --exclude wt "${TILDAE:-$HOME}/${r}"
+                done > "$repos_size"
+                readarray -t REPOS < <(sort -nr "$repos_size" | sed -E 's/^[0-9]+\s+//')
+            fi
+
             for r in "${REPOS[@]}"
             do
                 # shellcheck disable=SC2088
-                ((opt_list==1)) && rr="~/${r}"
-                ((opt_list==2)) && rr="${TILDAE:-$HOME}/${r}"
-                if ((!opt_gse))
+                if((opt_size))
                 then
-                    echo "$rr"
+                    du -hs --exclude wt "${r}"
                 else
-                    gse=$(cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
-                          git branch info local-status)
-                    sched=$(cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
-                            git branch info delete-worktree)
-                    [ -n "$sched" ] && sched=$(date --date "@${sched}")
-                    if [ -n "$gse" ] || [ -n "$sched" ]
+                    local rexp
+                    ((opt_list==1)) && rexp="~/${r}" || rexp="${TILDAE:-$HOME}/${r}"
+                    if ((opt_stat==1))
                     then
-                        echo "$rr:"
-                        [ -n "$gse" ]   && echo "    $gse"
-                        [ -n "$sched" ] && echo "    Scheduled for removal on or after $sched"
+                        echo "$rexp"
+                        (cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
+                         git status --porcelain)
                         echo
+                    fi
+                    if ((opt_stat==2))
+                    then
+                        (cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
+                         (( $(git status --porcelain | wc -l) )) && (echo "$rexp" && git status --porcelain && echo))
                     fi
                 fi
             done
@@ -197,7 +215,8 @@ git-go ()
 
 return 0 ## USAGE guard when sourcing
 :<<'__USAGE__'
-Usage: git-go [--list[full] [--stat]] [--update|-u] [--roots|-r] [--mbig|-m] \
+Usage: git-go [--list[full] [--size] [--stat|--dirty] [--update|-u] \
+              [--roots|-r] [--mbig|-m] \
               [--wt|--nowt|--wtonly ] [--mod] [dirmatch] [item]
 
        git-go [-h|--help]
@@ -206,16 +225,26 @@ Usage: git-go [--list[full] [--stat]] [--update|-u] [--roots|-r] [--mbig|-m] \
        choose and then cd to.
 
        --list
-           Skip the choosing part and just exit, printing each repo dir with a
-           litteral '~'.
+           Skip the choosing part and just exit, printing each repo            '~' expanded.
+dir with a
+           literal '~'.
 
        --listfull
            Skip the choosing part and just exit, printing each repo dir with
            '~' expanded.
 
+       --size
+           Skip the choosing part and just exit, printing each repo dir with
+           '~' expanded, and its size, sorted by descending size order. Worktree
+           sizes are not included in the size of their parent repos.
+
        --stat
-           Invoke as if --list was specified but only for repos with extended
-           status information.
+           Invoke as if --list was specified and for each repo, call 'git
+           status --porcelain'.
+
+       --dirty
+           Invoke as if --stat was specified, but only print repos and status
+           where there is a non-blank status.
 
        --update
            Rescan to pick up new and deleted repos and worktrees.
