Fixes for git commands to work below git root.
bin/git-commit-with-changelog-guts
o No longer requires files relative to git-root.

bin/git-process-changelog
o Better accounting for git rm'ed files in rm'ed directories. No longer
  requires files relative to git-root.

bin/git-status-ext
o Remove dead option in call to git-status-with-changelog.

bin/git-status-parse
store_filename():
  o Swap out abs_path for a local text manipulating function so that git
    deleted files work properly.

bin/git-status-with-changelog
o Work without cd'ing around. Replace git-status-parse call with git what
  is modified.

bin/parse-changelog
o Make it work without cd'ing to git root.

push_to_output():
  o Colorize the no changelog message.

diff --git a/bin/git-process-changelog b/bin/git-process-changelog
--- a/bin/git-process-changelog
+++ b/bin/git-process-changelog
@@ -5,17 +5,6 @@
 # shellcheck disable=SC1090
 source "$BASH_INC_DIR/on_exit.binc"
 
-## This function works best in the git root, which is where the
-## $GITFUNCS_CHANGELOG_NAME is anyway
-declare pwd
-pwd=$(pwd)
-declare gr
-gr=$(git root)
-if [ ! "$pwd" = "$gr" ]
-then
-    _git-cd-to "$gr" || exit $?
-fi
-
 declare action='read'
 declare opt_v='' ## passed to commit
 declare status=0
@@ -89,12 +78,31 @@ then
     cmd-echo "No files specified."
     exit 1
 fi
+
+declare git_root
+git_root=$(git root)
+
 declare -a filelist
-for i in "$@"
+declare file
+for file in "$@"
 do
-    ## -s is 'do not expand sysmlinks' so that we can treat the symlink as a
-    ## -first-class object. Thank you, git!
-    filelist+=("$(realpath -s "$i")")
+    ## The files fed to git-process-changelog are in 'rooted' form (relative to the repo root)
+    declare absolute_file
+    absolute_file="$(pwd)/$file"
+    if [ -r "$absolute_file" ]
+    then
+        filelist+=("$absolute_file")
+    else
+        ## $file is either a git rm'ed file or a typo.
+        if [ "$(git what is deleted --rooted | grep -E "^$file$")" = "$file" ]
+        then
+            ## Then the file is indeed git rm'ed.
+            filelist+=("$git_root/$file")
+        else
+            cmd-echo "File $file not found. Aborting"
+            exit 1
+        fi
+    fi
 done
 
 ## Find the changelog
