Updated return handling

diff --git a/bin/git-clone b/bin/git-clone
--- a/bin/git-clone
+++ b/bin/git-clone
@@ -13,7 +13,7 @@ cmd_echo_id='git-clone'
 
 _git_clone_record_created_date ()
 {
-    git config --replace-all "${GIT_EXT_META_PREFIX}".git-clone.created "$(date "$GIT_EXT_META_DATE_FMT")" || return $?
+    git config --replace-all "${GIT_EXT_META_PREFIX}".git-clone.created "$(date "$GIT_EXT_META_DATE_FMT")" || return
 }
 
 _git_clone_record_named_branches ()
@@ -31,7 +31,7 @@ _git-clone-set-triangle()
         githost_url=$(git kv --get "svcs.$githostkeycheck")
         if [[ -z "$githost_url" ]]; then
             echo "No url found for githost '$1'";
-            return 1
+            false; return
         fi
     fi
     local upstream_namespace=$1;shift
@@ -53,7 +53,7 @@ _git-clone-set-triangle()
 
     local key
     for key in "${!triangle_workflow[@]}"; do
-        git config --replace-all "$key" "${triangle_workflow[$key]}" || return $?
+        git config --replace-all "$key" "${triangle_workflow[$key]}" || return
     done
 
     ##
@@ -61,19 +61,18 @@ _git-clone-set-triangle()
     ##
     key='remote.origin.fetch'
 
-    git config --replace-all $key "+refs/heads/*:refs/remotes/origin/*" || return $?
-    git config --add         $key "+refs/pull/*/head:refs/pull/origin/*" || return $?
+    git config --replace-all $key "+refs/heads/*:refs/remotes/origin/*" || return
+    git config --add         $key "+refs/pull/*/head:refs/pull/origin/*" || return
     ## ^ allows git checkout -b 3 pull/origin/3
 
     key='remote.upstream.fetch'
-    git config --replace-all $key "+refs/heads/*:refs/remotes/upstream/*" || return $?
-    git config --add         $key "+refs/pull/*/head:refs/pull/upstream/*" || return $?
-    git config --add         $key "+refs/notes/*:refs/notes/*" || return $?
+    git config --replace-all $key "+refs/heads/*:refs/remotes/upstream/*" || return
+    git config --add         $key "+refs/pull/*/head:refs/pull/upstream/*" || return
+    git config --add         $key "+refs/notes/*:refs/notes/*" || return
     ## ^ allows git checkout -b 3 pull/upstream/3
 
     ## Our own metadata
-    git config --replace-all "${GIT_EXT_META_PREFIX}".git-clone.triangle-remote "${upstream_namespace}" || return $?
-    return 0
+    git config --replace-all "${GIT_EXT_META_PREFIX}".git-clone.triangle-remote "${upstream_namespace}" || return
 }
 
 main ()
@@ -147,7 +146,7 @@ main ()
                 if [[ "$tmp_otn" =~ ^- ]]; then
                     ## we got the next option, not an arg to this one
                     cmd-echo -id "$cmd_echo_id" --ec -- "Fork org ($tmp_otn) cannot start with a '-'."
-                    return 1
+                    false; return
                 fi
                 opt_triangle_namespace=${tmp_otn%/*}
                 if [[ ! "$tmp_otn" = "$opt_triangle_namespace" ]]; then
@@ -168,14 +167,14 @@ main ()
                 if [[ "$opt_worktree_name" =~ ^- ]]; then
                     ## we got the next option, not an arg to this one
                     cmd-echo -id "$cmd_echo_id" --ec -- "Worktree name ($opt_worktree_name) cannot start with a '-'."
-                    return 1
+                    false; return
                 fi
                 if [[ "$option" =~ f ]]; then
                     opt_worktree_fetch='--fetch'
                 fi
                 ;;
             --help | -h )
-                git-usage "$0"; return 0 ;;
+                git-usage "$0"; true; return ;;
             --debug | -x )
                 dispatch_to_real_git=0; set -x; do-on-exit set +x;;
             * )
@@ -192,7 +191,7 @@ main ()
         ## There are no options specified that make us think we want to run our
         ## clone code; go run system git clone.
         "$REALGIT" clone "${pass_on[@]}"
-        return $?
+        return
     fi
 
     ## WARNING: At this point, 'pass_on' should contain only the repo to clone
@@ -205,13 +204,13 @@ main ()
         opt_make_triangle=0
     fi
 
-    [[ -z "${pass_on[0]}" ]] && git-usage "$0" "Missing arguments" && return 1
+    [[ -z "${pass_on[0]}" ]] && git-usage "$0" "Missing arguments" && { false; return; }
     if [[ -z "${githost}" ]]; then
         local -a tmpa
         asplit "${pass_on[0]}" -s : -a tmpa
         if [[ "${tmpa[0]}" = "${pass_on[0]}" ]]; then
             cmd-echo -id "$cmd_echo_id" --ec -- "githost not specified and no 'githost:' found in '${pass_on[0]}'"
-            return 1
+            false; return
         fi
         githost="${tmpa[0]}"
         namespace="${tmpa[1]}"
@@ -226,7 +225,7 @@ main ()
     githost_url="$(git kv --get "svcs.${githost}")"
     if [[ -z "$githost_url" ]]; then
         cmd-echo -id "$cmd_echo_id" --ec -- "$githost is unknown. Valid githosts are:$(git kv --key-only --section svcs)"
-        return 1
+        false; return
     fi
     if [[ "$namespace" == */* ]]; then
         local -a tmpa
@@ -239,7 +238,7 @@ main ()
 
     if [[ -z $namespace ]] || [[ -z $repo ]]; then
         cmd-echo -id "$cmd_echo_id" --ec -- "Missing one or both of namespace and repo args."
-        return 1
+        false; return
     fi
 
     local tgtdir
@@ -263,7 +262,7 @@ main ()
         shouldbein="$(git config --get --expand ext.git-repo-root.root)/$githost"
         if [[ ! -d "$shouldbein" ]]; then
             cmd-echo -ec -- "Cannot find '$shouldbein'." "Correct and re-execute."
-            return 1
+            false; return
         else
             cmd-echo -- "Going to $shouldbein"
             builtin cd "$shouldbein" || exit
@@ -280,8 +279,8 @@ main ()
         cmd-echo -- "github-api --server $githost --data-mode --wait fork $opt_triangle_namespace $repo..."
         forked_repo=$(github-api --server "$githost" --data-mode --wait fork "$opt_triangle_namespace" "$repo")
         local dq="$?"
-        if [[ $dq != '0' ]]; then
-            return $?
+        if [[ $dq != $(true; echo $?) ]]; then
+            return $dq
         fi
         if [[ $forked_repo != "$repo" ]]; then
             if ((tgt_override==0)); then
@@ -311,7 +310,7 @@ main ()
             else
                 echo
             fi
-            return 0
+            true; return
         else
             rm -rf "$tgt"
         fi
@@ -320,7 +319,7 @@ main ()
     ## Do the clone
     cmd-echo -- "$REALGIT clone ${pass_on[*]} ${githost_url}$namespace/${forked_repo:-$repo} $tgt ..."
     if ! $REALGIT clone "${pass_on[@]}" "${githost_url}$namespace/${forked_repo:-$repo}" "$tgt"; then
-        return $?
+        return
     fi
 
     ## Our own metadata
@@ -336,7 +335,7 @@ main ()
             if builtin cd "$tgt"; then
                 git-retimestamp
             else
-                cmd-echo -id "$cmd_echo_id" --ec -- "Cannot cd $tgt" && return 1
+                cmd-echo -id "$cmd_echo_id" --ec -- "Cannot cd $tgt" && { false; return; }
             fi
         )
         cmd-echo -- 'Done'
@@ -358,17 +357,17 @@ main ()
     dirlist "$tgt"
     if [[ -n "$opt_triangle_namespace" ]]; then
         cmd-echo -- "Setting up triangle workflow with ${githost_url}${opt_triangle_namespace}/${repo}..."
-        _git-clone-set-triangle "${githost_url}" "$opt_triangle_namespace" "$namespace" "$repo" "${forked_repo:-$repo}"|| return $?
+        _git-clone-set-triangle "${githost_url}" "$opt_triangle_namespace" "$namespace" "$repo" "${forked_repo:-$repo}" || return
         if ! git pull ; then
             cmd-echo --ec -- 'If the error refers to a missing ref whose name contains "master",' \
                      "then your fork's default branch is not the same as the upstream." \
                      "Fix or delete the fork and retry."
-            return $? # To refresh from the upstream
+            false; return # To refresh from the upstream
         fi
     else
         local key='remote.origin.fetch'
-        git config --replace-all $key "+refs/heads/*:refs/remotes/origin/*" || return $?
-        git config --add         $key "+refs/pull/*/head:refs/pull/origin/*" || return $?
+        git config --replace-all $key "+refs/heads/*:refs/remotes/origin/*" || return
+        git config --add         $key "+refs/pull/*/head:refs/pull/origin/*" || return
         ## ^ allows git checkout -b 3 pull/origin/3
     fi
     git remote -v
diff --git a/bin/git-repo b/bin/git-repo
--- a/bin/git-repo
+++ b/bin/git-repo
@@ -60,13 +60,13 @@ git-repo-current-branch ()
 {
     local warn=1
     if [[ $1 == '--no-warn' ]]; then
-         warn=0
-         shift
+        warn=0
+        shift
     fi
 
     if [[ -n $1 ]]; then
         cmd-echo --id git-repo --ec -- "Cannot set current branch yet"
-        false;return $?
+        false; return
     else
         local cb
         cb=$($REALGIT branch --show-current)
@@ -75,7 +75,7 @@ git-repo-current-branch ()
             cb=$($REALGIT branch --color=never --contains HEAD | grep '(no branch, rebasing' | sed 's/.* \(.*\))/\1/')
             if [[ -z $cb ]]; then
                 ((warn)) && cmd-echo --id git-repo --ec -- "Cannot get current branch"
-                false;return $?
+                false; return
             fi
         fi
         echo "$cb"
@@ -114,7 +114,6 @@ git-repo-default-branch ()
         cmd-echo --id git-repo --ec -- "Cannot find default branch for ${PWD}"
         false
     fi
-    return $?
 }
 
 git-repo-show-default-branch ()
@@ -157,8 +156,8 @@ git-repo-delete ()
         \cd "$dirmode" || { cmd-echo --id git-repo "Cannot cd $dirmode"; false; return; }
         local root_or_err
         root_or_err="$(git root 2>&1)"
-        local status=$?; true
-        if ((status!=$?)); then
+        local status=$?
+        if ((status!=$(true; echo $?))); then
             cmd-echo --id git-repo -- "$root_or_err"
             \cd "$returnpath" || { cmd-echo --id git-repo "Cannot cd $returnpath"; false; return; }
             return $status
@@ -177,16 +176,14 @@ git-repo-delete ()
         githost_url=$(git kv --get "svcs.$githost")
         if [[ -z "$githost_url" ]]; then
             cmd-echo --id git-repo -- "$githost is unknown. Valid githosts are:$(git kv --key-only --section serverid)"
-            return 1
+            false; return
         fi
 
-        added
         ## Go to what we want to whack, to make sure it's there.
-        git go "$githost/$namespace/$repo"
-        status=$?
-        ((status != 0)) && { false; return; } ## If the git go fails, we should
-                                              ## see error messages, no need to
-                                              ## do anything else.
+        git go "$githost/$namespace/$repo" || return ## If the git go fails, we
+        ## should see error
+        ## messages, no need to do
+        ## anything else.
     else # we were told to delete the directory/repo we are currently in
         if [[ -z $GIT_DISPATCHER ]]; then
             git-dispatch-warning "git-repo delete --current"
@@ -218,11 +215,8 @@ git-repo-delete ()
         fi
 
         \cd .. || { cmd-echo --id git-repo "Cannot cd .."; false; return; }
-        \rm -rf "$repo"
-        status=$?
-        ((status != 0)) && { false; return; } ## If the rm fails, we should see
-                                              ## error messages, no need to add
-                                              ## more.
+        \rm -rf "$repo" || return ## If the rm fails, we should see error
+        ## messages, no need to add more.
 
         cmd-echo --id git-repo "Done. Not touching remote repo. Resetting git list..."
         ## Remove the just-deleted repo from the list of local git repos.
@@ -338,7 +332,7 @@ git-repo-diff ()
     local -A rightfiles
     for which in left right; do
         perl -e 'chdir $ARGV[0];
-             print qx(git ls-files)' "${repo[$which]}" > "${list[$which]}"
+                          print qx(git ls-files)' "${repo[$which]}" > "${list[$which]}"
         if [[ -n "$exclude" ]]; then
             grep -v "$exclude" "${list[$which]}" > "${list[$which]}.filt"
             mv "${list[$which]}.filt" "${list[$which]}"
@@ -418,7 +412,7 @@ git-repo-diff ()
             false; return
         else
             $EDITOR "${editable[@]}"
-            return $?
+            return
         fi
     fi
 
@@ -433,10 +427,10 @@ git-repo-is ()
         verbose=1
         shift
     fi
-    [[ "$1" ]] && [[ $1 != . ]] && { \cd "$1" || { false; return; } }
+    [[ "$1" ]] && [[ $1 != . ]] && { \cd "$1" || return; }
     git rev-parse --show-toplevel 2>/dev/null 1>&2
     declare status=$?
-    [[ "$1" ]] && [[ $1 != . ]] && { \cd -    || { false; return; } }
+    [[ "$1" ]] && [[ $1 != . ]] && { \cd -    || return; }
     (( verbose )) && ( (( status )) && echo false || echo true )
     return $status
 }
@@ -464,9 +458,9 @@ git-repo-is_pristine ()
         if ! git worktree ina && (( $(git worktree list | wc -l) != 1 )); then
             echo Found worktrees:
             git worktree list | tail -n +2 # Do not print the root repo for the
-                                           # worktrees, which is always the
-                                           # first entry of the wt list
-                                           # command.
+            # worktrees, which is always the
+            # first entry of the wt list
+            # command.
         fi
     fi
     false
@@ -498,7 +492,7 @@ git-repo-is_fork ()
     (
         # shellcheck disable=SC2164 #https://github.com/koalaman/shellcheck/wiki/SC2164
         \cd "${1:-.}" # so that the git remote works on the current dir as well
-                     # as a specified repo dir
+        # as a specified repo dir
         local origin
         local fork_of=''
         origin=$(git remote get-url origin)
@@ -506,11 +500,11 @@ git-repo-is_fork ()
             local server=${origin%%:*}
             local repo_path=${origin##*:}
             fork_of=$(perl -e'
-   use JSON::PP::Boolean;
-our $VAR1;
-eval "@ARGV";
-$VAR1->{parent} && print $VAR1->{parent}{full_name};
-' "$( github-api --silent --server "$server" --perl-data url repos/"$repo_path")")
+                              use JSON::PP::Boolean;
+                                  our $VAR1;
+                                      eval "@ARGV";
+                                           $VAR1->{parent} && print $VAR1->{parent}{full_name};
+                                                           ' "$( github-api --silent --server "$server" --perl-data url repos/"$repo_path")")
         fi
         ((print)) && [[ -n "$fork_of" ]] && echo "$fork_of"
         [[ -n "$fork_of" ]] ## return value
@@ -632,15 +626,14 @@ git-repo-name ()
     else
         false
     fi
-    return
 }
 
 # shellcheck disable=SC2120 #https://github.com/koalaman/shellcheck/wiki/SC2120
 git-repo-org ()
 {
-    [[ "$1" ]] && [[ $1 != . ]] && { \cd "$1" || { false; return; } }
+    [[ "$1" ]] && [[ $1 != . ]] && { \cd "$1" || return; }
     name=$(git remote -v 2>/dev/null | grep origin |  sed -e 's/.*://' -e 's/\/.*//' | sort -u)
-    [[ "$1" ]] && [[ $1 != . ]] && { \cd - || { false; return; } }
+    [[ "$1" ]] && [[ $1 != . ]] && { \cd - || return; }
     [[ -z "$name" ]] && { false; return; }
     echo "$name"
     true
@@ -698,7 +691,7 @@ git-repo-pr-get ()
             remote )
                 remotes=("$1"); shift;;
             --) break ;; ## VITAL!!! Exits the while loop, no more options,
-                         ## remaining $*, if any, are args
+            ## remaining $*, if any, are args
             *)
                 cmd-echo --id git-repo -ec -- "$option is an invalid option. See $0 --help"
                 false; return
@@ -746,7 +739,7 @@ git-repo-pr-get ()
 
     if ((opt_refresh==0)); then
         _git-repo-pr-retrieve pr_cache_url pr_cache_state pr_cache_date pr_cache_as_of pr_cache_version
-    # else we don't get any data, which causes cached to be set to no
+        # else we don't get any data, which causes cached to be set to no
     fi
 
     local cached
@@ -1016,7 +1009,7 @@ git-repo-purge()
             fi
             git-repo-pr-get --open \
                 && ok_to_purge=0 ## func returns success if it finds a open PR,
-                                 ## in which case we can't purge it.
+            ## in which case we can't purge it.
             ! git-repo-is_pristine -v && ok_to_purge=0
             if ((ok_to_purge)); then
                 resp=$(cmd-yesno --id git-repo -dc "Repo is pristine. Delete it" n)
@@ -1058,7 +1051,7 @@ git-repo-restore ()
 
 git-repo-tags ()
 {
-     git tag --list --sort=v:refname
+    git tag --list --sort=v:refname
 }
 
 # shellcheck disable=SC2120 #https://github.com/koalaman/shellcheck/wiki/SC2120
@@ -1088,7 +1081,7 @@ git-repo-named-branches ()
 
     if [[ -z $1 ]]; then
         git-repo-using-named-branches "$verbose"
-        return $?
+        return
     fi
 
     if [[ ! $1 =~ ^(true|false)$ ]]; then
@@ -1142,11 +1135,10 @@ main()
         case $action in
             * )
                 cmd-echo --id git-repo --ec --id git-repo -- "unknown git repo action '$action'"
-                return 1
+                false; return
                 ;;
         esac
     fi
-    return $?
 }
 
 main "$@"
diff --git a/bin/kvstore b/bin/kvstore
--- a/bin/kvstore
+++ b/bin/kvstore
@@ -66,9 +66,9 @@ kvstore_usage () {
 _kvstore_ns_check () {
   if [[ "$1" =~ \.lock$ ]]; then
     echo "namespace cannot end in .lock, reserved for lock githost"
-    return 1
+    false; return
   else
-    return 0
+    true; return
   fi
 }
 
@@ -86,6 +86,7 @@ _kvstore_path () {
 _kvstore_lock_then () {
   local lockfile="$1"
   local cmd="$2"
+  local status
   shift
   shift
   if type flock &>/dev/null; then
@@ -108,7 +109,7 @@ _kvstore_lock_then () {
         sleep 5
         if ! mkdir "$lockfile"; then
             echo "kvstore: Cannot grab lock (mkdir $lockfile)"
-            return 1
+            false; return
         fi
     fi
     "$cmd" "$@"
@@ -229,12 +230,12 @@ kvstore_lsfiles () {
 _kvstore_get_either () {
   local cutarg=$1; shift
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   local path
   path=$(_kvstore_path "$ns")
   if [[ ! -f "$path" ]]; then
     echo "Error: path not found: $path" >&2
-    return 2
+    false; return
   fi
   cut "$cutarg" < "$path"
 }
@@ -249,35 +250,35 @@ kvstore_vals () {
 
 kvstore_get () {
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   local key="$2"
-  [[ -z "$key" ]] && echo "Missing param: key" >&2 && return 1
+  [[ -z "$key" ]] && echo "Missing param: key" >&2 && { false; return; }
   local file
   file=$(_kvstore_path "$ns")
   if [[ ! -f "$file" ]]; then
     echo "Error: namespace file not found: $ns" >&2
-    return 2
+    false; return
   fi
   found=0
   _kvstore_each_file_kv "$file" _kvstore_echo_v_if_k_match "$key"
   if (( found == 0 )); then
     echo "Error: key not found in namespace $ns: $key" >&2
-    return 1
+    false; return
   fi
 }
 
 kvstore_set () {
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   local key="$2"
-  [[ -z "$key" ]] && echo "Missing param: key" >&2 && return 1
+  [[ -z "$key" ]] && echo "Missing param: key" >&2 && { false; return; }
   local val="$3"
-  [[ -z "$val" ]] && echo "Missing param: value" >&2 && return 1
+  [[ -z "$val" ]] && echo "Missing param: value" >&2 && { false; return; }
   local path
   path=$(_kvstore_path "$ns")
   touch "$path"
   _kvstore_lock_then "${path}.lock" _kvstore_nonatomic_set "$path" "$key" "$val"
-  return $?
+  return
 }
 
 kvstore_mv () {
@@ -307,21 +308,21 @@ kvstore_mv () {
   done
 
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2  && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   local key_from="$2"
-  [[ -z "$key_from" ]] && echo "Missing param: key_from" >&2  && return 1
+  [[ -z "$key_from" ]] && echo "Missing param: key_from" >&2 && { false; return; }
   local key_to="$3"
-  [[ -z "$key_to" ]] && echo "Missing param: key_to" >&2 && return 1
+  [[ -z "$key_to" ]] && echo "Missing param: key_to" >&2 && { false; return; }
 
   local val
   val=$(kvstore_get "$ns" "$key_from")
   if ! kvstore_get "$ns" "$key_from" >/dev/null; then
-    return 2
+    false; return
   fi
   if kvstore_get "$ns" "$key_to" &>/dev/null; then
     if ((!force)); then
       echo "Error: destination key already exists: $key_to" >&2
-      return 3
+      false; return
     fi
   else
     ## If the key isn't there, unset force if it was set, so we can skip the
@@ -336,11 +337,11 @@ kvstore_mv () {
 
 kvstore_rm () {
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2  && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   local key="$2"
-  [[ -z "$key" ]] && echo "Missing param: key to remove" >&2  && return 1
+  [[ -z "$key" ]] && echo "Missing param: key to remove" >&2 && { false; return; }
   if ! kvstore_get "$ns" "$key" >/dev/null; then
-    return 2
+    false; return
   fi
   local path
   path=$(_kvstore_path "$ns")
@@ -391,12 +392,12 @@ complete -F _${ns}_kvstore_complete $cmd"
 
 kvstore_drop () {
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   path=$(_kvstore_path "$ns")
   command rm "${path}" ## 'command' avoids any aliases or shell functions
                        ## defined by the user.
   local status=$?
-  if((status==0)); then
+  if((status==$(true; echo $?))); then
     \rm -rf "${path}.lock"
   fi
   return $status
@@ -431,7 +432,7 @@ kvstore_dump () {
   done
 
   local ns="$1"
-  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && return 1
+  [[ -z "$ns" ]] && echo "Missing param: namespace" >&2 && { false; return; }
   ((verbose)) && echo "$(basename "$ns"):"
   path=$(_kvstore_path "$ns")
   if ((raw)); then
@@ -440,7 +441,7 @@ kvstore_dump () {
       sed -e 's/^/"/' -e's/\t/"=>"/' -e 's/$/"/' "${path}"
   fi
 
-  return $?
+  return
 }
 
 kvstore_grep () {
@@ -454,19 +455,19 @@ kvstore () {
   if [[ -z "$cmd" ]]; then
     echo "Error: Command not specified" >&2
     echo "kvstore -h to see usage" >&2
-    return 1
+    false; return
   fi
   shift
 
   case "$cmd" in
     -h|--help)
       kvstore_usage
-      return 0
+      true; return
       ;;
     -v|--version)
       echo 3.0.2
       ## Make sure to keep in sync with the version in the usage statement above.
-      return 0
+      true; return
       ;;
     load)
       if [[ "$(basename -- "$0")" =~ kvstore ]]; then
@@ -477,67 +478,67 @@ kvstore () {
         echo
         echo "         . $0 load"
         echo
-        return 1
+        false; return
       else
-        return 0             ## Do nothing if sourcing into environment.
+        true; return             ## Do nothing if sourcing into environment.
       fi
       ;;
     ls | list)
       kvstore_ls "$@"
-      return $?
+      return
       ;;
     lsinfo)
       kvstore_lsinfo "$@"
-      return $?
+      return
       ;;
     lsfiles)
       kvstore_lsfiles "$@"
-      return $?
+      return
       ;;
     keys)
       kvstore_keys "$@"      ## namespace
-      return $?
+      return
       ;;
     vals)
       kvstore_vals "$@"      ## namespace
-      return $?
+      return
       ;;
     get)
       kvstore_get "$@"       ## namespace key
-      return $?
+      return
       ;;
     set)
       kvstore_set "$@"       ## namespace key value
-      return $?
+      return
       ;;
     rm)
       kvstore_rm "$@"        ## namespace key
-      return $?
+      return
       ;;
     mv)
       kvstore_mv "$@"        ## [-f] namespace from_key to_key
-      return $?
+      return
       ;;
     shellinit)
       kvstore_shellinit "$@" ## namespace
-      return 0
+      true; return
       ;;
     drop)
       kvstore_drop "$@"      ## namespace
-      return $?
+      return
       ;;
     dump)
       kvstore_dump "$@"      ## [-v] [-r] namespace
-      return $?
+      return
       ;;
     grep)
       kvstore_grep "$@"      ## grep args
-      return $?
+      return
       ;;
     *)
       echo "Error: Unrecognized command: $cmd" >&2
       echo "kvstore -h to see usage" >&2
-      return 1
+      false; return
       ;;
   esac
 }
