* on-exit => on_exit * Shellchecked v0.10.0
bin/RXCmd
* Added option to run in foreground.

bin/bash-history-purge
* Fullpath for cron usage.

bin/git-check-with-remote
  * Fix shellcheck complaint about unreachable code.

bin/git-commit
* Added --oops for small, dumb commits.

bin/git-diff
* Added --no-git as a filter.
* Fixed exit status.

bin/git-go
* implement --show-pr

bin/git-go-get
* implement with and no pr flags

bin/git-go-set
* Weed out any repo paths that are softlinks.

bin/git-log
* Added '--stop-at commitid' option.
* Implement -n"th" instead using -n and trying to peel off the last one.
  Allow -n and -nth to Do The Right Thing with --reverse.

bin/git-log-grab-sha
* Clarify numeric option operation.

bin/git-pre-commit-hook
* Check for local and generic perl tidy setups.

bin/git-process-source-ctrl-log
* Accounted for empty debug option to perl code.

bin/git-rebase
_git_rebase_via_ilog():
  * Adjustedd which commits show up.

git-repo-current-branch():
  * Added GIT_EXT_SHOW_CANONICAL support.

bin/git-status-with-source-ctrl-log
* Fixed up perl debug setting.

bin/git-worktree
git-worktree-delete():
  * Improve current worktree name detection.
  * Change from is clean to is spotless so we don't loose untracked files
    we might have forgotten to add.

bin/git.mopenv
* git aliases that cannot be in git's own config.

bin/misc.alias
* xrdbm alias dropped in favor of xrdbm script

bin/newx
* Added option to run in foreground.
* Shellchecked v0.10.0

bin/on-exit-scoped.binc
* SC2004 (style): $/${} is unnecessary on arithmetic variables.

bin/on_exit.binc
* SC2004 (style): $/${} is unnecessary on arithmetic variables.

bin/same
* Revamped (new?) code.

bin/select-from-file
* --verbose now identifies the data file.

bin/viui
* If called as xoui, will use emacs.

bin/xo
* Now accepts piped in output, places it in a buffer.

bin/xrdb-ext
* Add loadtime and load source.

bin/xterm-cli
* Fixed function name variable.

_xterm-cli-xground():
  * Corrected xterm determination.

xterm-cli-id():
  * Typo.

dotfiles/bash_profile
* Monkeypatch test should be readable, not executable.

dotfiles/bashrc
* Monkeypatch test should be readable, not executable.

dotfiles/bashrcuser
* Monkeypatch test should be readable, not executable.

dotfiles/gitconfig_personal
* Added oldest_ancestor alias, not sure why.

dotfiles/profile
* Monkeypatch test should be readable, not executable.

dotfiles/xterminit
* Use generic employer reference.

functions/delpath
* Fix usage calls.

functions/git
* Added canonical flag to spit out REALGIT commands.

git():
  * Added 'oops', 'fush' and 'oof' aliases.
  * Added local alias show command.

functions/uniqpath
uniqpath():
  * Elimiate consecutive subpath separators.

functions/venv
* Removed the -d to provide a dir, defaulting to $PWD/.venv . Add pip
  processing to retain a record of what was installed.

diff --git a/bin/git-go b/bin/git-go
--- a/bin/git-go
+++ b/bin/git-go
@@ -104,6 +104,8 @@ declare opt_time
 opt_time='--notime'
 declare opt_root
 opt_root='0'
+declare opt_show_pr
+opt_show_pr=0
 declare -a limited
 declare -a tgts
 declare doandcdfile
@@ -119,7 +121,7 @@ longopts="$longopts,wc,with-comments,wco,with-comments-only"
 longopts="$longopts,list,lf,listfull,size,update"
 longopts="$longopts,wt,nowt,wto"
 longopts="$longopts,stat,dirty,brief,mod,help,index:,limited:,comma"
-longopts="$longopts,doandcd:,wpr,with-pr,npr,no-pr,set,top:,time,notime"
+longopts="$longopts,doandcd:,wpr,with-pr,npr,no-pr,show-pr,spr,set,top:,time,notime"
 longopts="$longopts,root,prune,page"
 
 # Process the command line.
@@ -151,6 +153,7 @@ while true; do
         wco | with-comments-only ) opt_comments=2; opt_list=1 ;;
         wpr | with-pr ) git_get_opts+=('--with-pr');;
         npr | no-pr ) git_get_opts+=('--no-pr');;
+        spr | show-pr ) opt_show_pr=1; opt_list=1 ;;
         l | list ) opt_list=1 ;;
         lf | listfull ) opt_list=2 ;;
         comma ) opt_comma=1 ;;
@@ -266,7 +269,7 @@ else
             ## Re-sort the list of repos by size descending using
             ## byte-level counts.
             repos_size=$(mktempfile)
-            rm-on-exit "$repos_size"
+            rm_on_exit "$repos_size"
             for r in "${REPOS[@]}"; do
                 du -s --exclude wt "${TILDAE:-$HOME}/${r}"
             done > "$repos_size"
@@ -309,6 +312,14 @@ else
                         fi
                         [[ -n "$output" ]] && echo "    $output" && echo
                     )
+                elif ((opt_show_pr)); then
+                     (
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo --id git-go -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+                        echo "$rexp"
+                        echo -n "    "
+                        git repo pr-get
+                        echo
+                     )
                 else
                     echo -n "$rexp"
                     if ((opt_comma)) && [[ "$r" != "${REPOS[-1]}" ]]; then ## and not the last rexp
diff --git a/bin/git-go-get b/bin/git-go-get
--- a/bin/git-go-get
+++ b/bin/git-go-get
@@ -14,7 +14,6 @@ declare filter
 declare exact
 declare limited
 declare with_pr
-
 # Read the options and args from command line. Note that the long and short
 # don't have to match up.
 declare OPTSARGS
@@ -65,8 +64,8 @@ filter="$1"
 
 declare tmpfile
 tmpfile=$(mktempfile)
-rm-on-exit "$tmpfile"
-rm-on-exit "${tmpfile}.001"
+rm_on_exit "$tmpfile"
+rm_on_exit "${tmpfile}.001"
 
 declare gitfuncs_git_go_file
 if [[ -n "$limited" ]]; then
@@ -92,11 +91,6 @@ else
         grep '/wt/' "$tmpfile" > "${tmpfile}.001"
         mv "${tmpfile}.001" "$tmpfile"
     fi
-
-    if ((with_pr)); then
-        cmd-echo --id git-go-get -- 'Options --(with|no)-pr not yet implemented'
-    fi
-
 fi
 
 if [[ -n "$filter" ]]; then
@@ -114,6 +108,23 @@ if [[ -n "$filter" ]]; then
         tail     ) grep -E "${grepargs[@]}" "$filter\$"  "$tmpfile" > "${tmpfile}.001" ;;
         *        ) grep -i "${grepargs[@]}" "$filter"    "$tmpfile" > "${tmpfile}.001" ;;
     esac
+    mv "${tmpfile}.001" "$tmpfile"
+fi
+
+if ((with_pr)); then
+    declare repos
+    readarray -t repos < <(cat "$tmpfile")
+    for r in "${repos[@]}"; do
+        (
+            # The false; exit; will exit from the subshell, skipping the rest
+            cd "${TILDAE:-$HOME}/$r" || { echo "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
+            if ((with_pr==1)) && git repo pr-get 1>/dev/null 2>&1 ; then
+                echo "$r"
+            elif ((with_pr==2)) && ! git repo pr-get 1>/dev/null 2>&1 ; then
+                echo "$r"
+            fi
+        )
+    done > "${tmpfile}.001"
     mv "${tmpfile}.001" "$tmpfile"
 fi
 
diff --git a/bin/git-worktree b/bin/git-worktree
--- a/bin/git-worktree
+++ b/bin/git-worktree
@@ -289,7 +289,7 @@ git-worktree-create ()
         [[ $resp == 'y' ]] && wtname="$USER/$wtname"
         [[ $resp == 'q' ]] && { false; return; }
     fi
-    echo "$wtname"
+    cmd-echo "${celn}" "$LINENO" --id git-worktree --dc  "WT name is $wtname"
     local pull_ref
     if [[ -z "${wtname}" ]]; then
         if [[ -z "$pull_request" ]]; then
@@ -580,7 +580,21 @@ git-worktree-delete ()
         # the lead dash(es) from the option.
         [[ "$option" != '--' ]] && option=${option##-} && option=${option##-}
         case "$option" in
-            c | current) opt_current=1; wtname="$(_git_worktree_name_from_path "${PWD}")" ;;
+            c | current) opt_current=1;
+                         local wtpath
+                         wtpath="$(git root)"
+                         if [[ "$PWD" = "$wtpath" ]]; then
+                             # shellcheck disable=SC2034 #https://github.com/koalaman/shellcheck/wiki/SC2034
+                             noop=1
+                         elif [[ "$PWD" =~ $wtpath ]]; then
+                             cmd-echo "${celn}" "$LINENO" --id git-worktree "Must be in git worktree root dir to delete. Going there."
+                             builtin cd "$wtpath" || { cmd-echo "${celn}" "$LINENO" --id git-worktree --ec -- "Cannot cd $wtpath"; false; return; }
+                         else
+                             cmd-echo "${celn}" "$LINENO" --id git-worktree --ec -- "Cannot locate the current worktree. PWD=$PWD"
+                             false; return
+                         fi
+                         wtname=$(basename "$PWD")
+                         ;;
             noreset | no-reset | skip-reset) opt_reset=0; ;;
             y|yes) opt_yes=1; opt_yes_string='--yes'; ;;
             f|force) opt_force=1; ;;
@@ -633,7 +647,7 @@ $(ls -la)"
     fi
 
     ## Check for cleanliness.
-    if ! git repo is clean; then
+    if ! git repo is spotless; then
         if((!opt_force)); then
             git status
             echo
diff --git a/functions/venv b/functions/venv
--- a/functions/venv
+++ b/functions/venv
@@ -8,160 +8,187 @@
 # <Function Class: python>
 # <Function Justification: env>
 
-declare -A opts
-
 _venv_create()
 {
-    declare action=${FUNCTION//_venv_}
+    declare action=${FUNCNAME[0]//_venv_}
 
-    if $PYTHON_EXE -m venv "${opts[venv_dir]}"; then
-        cmd-echo --id "venv:$action" -- "Created venv ${opts[venv_dir]}"
+    if $PYTHON_EXE -m venv .venv && [[ -d .venv ]]; then
+        cmd-echo --id "venv:$action" -- "Created venv .venv (${PWD})"
     else
-        cmd-echo --id "venv:$action" -- "Failed to create venv ${opts[venv_dir]}"
+        cmd-echo --id "venv:$action" -- "Failed to create venv .venv"
         false; return
     fi
 
-    _venv_assign_envvars "${opts[venv_dir]}"
+    __venv_assign_envvars
 
-    cat <<EOF >> "$VIRTUAL_ENV_INIT_FILE"
+    cat <<EOF >> "${PYTHON_VIRTUAL_ENV_INIT_SPEC}"
 pip install --upgrade pip
 python -m pip install ruff black isort mypy pylint
 # Per-project customizations here:
 
 EOF
 
+    cmd-echo --id "venv:$action" -- ".venv init file (.venv/${PYTHON_VIRTUAL_ENV_INIT_FILE}):"
+    cat "${PYTHON_VIRTUAL_ENV_INIT_SPEC}"
 }
 
 _venv_info()
 {
-    cat "${opts[venv_dir]}/pyvenv.cfg"
+   declare action=${FUNCNAME[0]//_venv_}
+
+   cmd-echo --id "venv:$action" --title -- "pyvenv.cfg"
+   cat ".venv/pyvenv.cfg"
+   cmd-echo --id "venv:$action" --title -- ".venv.init"
+   cat ".venv.init"
+   cmd-echo --id "venv:$action" --title -- "envvars"
+   __venv_show_envvars
+}
+
+_venv_show()
+{
+    _venv_info
 }
 
 _venv_init()
 {
-   declare action=${FUNCTION//_venv_}
+   declare action=${FUNCNAME[0]//_venv_}
 
-   if [[ ! -r $VIRTUAL_ENV_INIT_FILE ]]; then
-       cmd-echo --id "venv:$action" -ec -- "Cannot find venv init file $VIRTUAL_ENV_INIT_FILE."
+   if [[ ! -r ${PYTHON_VIRTUAL_ENV_INIT_SPEC} ]]; then
+       cmd-echo --id "venv:$action" -ec -- "Cannot find venv init file ${PYTHON_VIRTUAL_ENV_INIT_SPEC}."
        false; return
    fi
 
-   if [[ -e $VIRTUAL_ENV_INITED_FILE ]]; then
-       cmd-echo --id "venv:$action" -ec -- "Already executed $action; marker file $VIRTUAL_ENV_INIT_FILE exists. Try 'reinit' if you want to run the init again."
+   if [[ -e ${PYTHON_VIRTUAL_ENV_INITED_SPEC} ]]; then
+       cmd-echo --id "venv:$action" -ec -- "Already executed $action; marker file ${PYTHON_VIRTUAL_ENV_INIT_SPEC} exists. Try 'reinit' if you want to run the init again."
        false; return
    fi
 
-   . "$VIRTUAL_ENV_INIT_FILE" && touch "$VIRTUAL_ENV_INITED_FILE"
+   . "${PYTHON_VIRTUAL_ENV_INIT_SPEC}" && touch "${PYTHON_VIRTUAL_ENV_INITED_SPEC}"
+}
+
+_venv_edit()
+{
+    ${EDITOR:-vi} "${PYTHON_VIRTUAL_ENV_INIT_SPEC}"
 }
 
 _venv_reinit()
 {
-   declare action=${FUNCTION//_venv_}
+   declare action=${FUNCNAME[0]//_venv_}
 
-   if [[ ! -r $VIRTUAL_ENV_INIT_FILE ]]; then
-       cmd-echo --id "venv:$action" -ec -- "Cannot find venv init file $VIRTUAL_ENV_INIT_FILE."
+   if [[ ! -r ${PYTHON_VIRTUAL_ENV_INIT_SPEC} ]]; then
+       cmd-echo --id "venv:$action" -ec -- "Cannot find venv init file ${PYTHON_VIRTUAL_ENV_INIT_SPEC}."
        false; return
    fi
 
-   if [[ ! -e $VIRTUAL_ENV_INITED_FILE ]]; then
-       cmd-echo --id "venv:$action" -ec -- "Cannot $action; marker file $VIRTUAL_ENV_INIT_FILE not found. Try 'init' if you want to run the init."
+   if [[ ! -e ${PYTHON_VIRTUAL_ENV_INITED_SPEC} ]]; then
+       cmd-echo --id "venv:$action" -ec -- "Cannot $action; marker file ${PYTHON_VIRTUAL_ENV_INITED_SPEC} not found. Try 'init' if you want to run the init."
        false; return
    fi
 
-   \rm "$VIRTUAL_ENV_INITED_FILE"
-   . "$VIRTUAL_ENV_INIT_FILE" && touch "$VIRTUAL_ENV_INITED_FILE"
+   \rm "${PYTHON_VIRTUAL_ENV_INITED_SPEC}"
+   . "${PYTHON_VIRTUAL_ENV_INIT_SPEC}" && touch "${PYTHON_VIRTUAL_ENV_INITED_SPEC}"
 }
 
-_venv_assign_envvars()
+__venv_assign_envvars()
 {
-    declare ve=${VIRTUAL_ENV:-$1}
     # shellcheck disable=SC2155 #https://github.com/koalaman/shellcheck/wiki/SC2155
-    export VIRTUAL_ENV_NAME=$(basename "$(realpath "$ve")")
+    export PYTHON_VIRTUAL_ENV_SPEC=$(realpath .venv)
     # shellcheck disable=SC2155 #https://github.com/koalaman/shellcheck/wiki/SC2155
-    export VIRTUAL_ENV_ROOT=$(dirname "$(realpath "$ve")")
-    export VIRTUAL_ENV_INIT_FILE=${VIRTUAL_ENV_ROOT}/${VIRTUAL_ENV_NAME}.init
-    export VIRTUAL_ENV_INITED_FILE=${VIRTUAL_ENV_ROOT}/${VIRTUAL_ENV_NAME}.inited
+    export PYTHON_VIRTUAL_ENV_NAME=$(basename "${PYTHON_VIRTUAL_ENV_SPEC}")
+    # shellcheck disable=SC2155 #https://github.com/koalaman/shellcheck/wiki/SC2155
+    export PYTHON_VIRTUAL_ENV_ROOT=$(dirname "${PYTHON_VIRTUAL_ENV_SPEC}")
+
+    export PYTHON_VIRTUAL_ENV_INIT_FILE=${PYTHON_VIRTUAL_ENV_NAME}.init
+    export PYTHON_VIRTUAL_ENV_INIT_SPEC=${PYTHON_VIRTUAL_ENV_ROOT}/${PYTHON_VIRTUAL_ENV_INIT_FILE}
+
+    export PYTHON_VIRTUAL_ENV_INITED_FILE=${PYTHON_VIRTUAL_ENV_NAME}.inited
+    export PYTHON_VIRTUAL_ENV_INITED_SPEC=${PYTHON_VIRTUAL_ENV_ROOT}/${PYTHON_VIRTUAL_ENV_INITED_FILE}
 }
 
-_venv_show_envvars()
+__venv_show_envvars()
 {
-    env | grep -E '^VIRTUAL_ENV'
-}
-
-
-_venv_swtich()
-{
-    declare -a target
-    if [[ -n $1 ]]; then
-        target=('--dir' "%{opts[vevn_dir]}")
-    fi
-    venv decativate
-    venv activate "${target[@]}"
+    env | grep -E '^(PYTHON_)?VIRTUAL_ENV' | sort
 }
 
 _venv_activate()
 {
     # shellcheck disable=SC1091 #https://github.com/koalaman/shellcheck/wiki/SC1091
-    source "${opts[venv_dir]}/bin/activate"
-    _venv_assign_envvars
-    if [[ -e $VIRTUAL_ENV_INIT_FILE ]] \
-           && [[ ! -e $VIRTUAL_ENV_INITED_FILE ]]; then
+    source ".venv/bin/activate"
+    __venv_assign_envvars
+    if [[ -e ${PYTHON_VIRTUAL_ENV_INIT_SPEC} ]] \
+           && [[ ! -e ${PYTHON_VIRTUAL_ENV_INITED_SPEC} ]]; then
         _venv_init
+    fi
+}
+
+_venv_pip()
+{
+    if python -m pip "$@"; then
+        echo "python -m pip $* # venv pip-install $(date)" >> "${PYTHON_VIRTUAL_ENV_INIT_SPEC}"
     fi
 }
 
 _venv_deactivate()
 {
-    deactivate
-}
-
-_venv_abandon ()
-{
-    declare action=${FUNCTION//_venv_}
-
     if is-a-function 'deactivate'; then
-        cmd-echo --id "venv:$action" -- '"deactivate" is available; calling "deactivate"...'
+        cmd-echo --id "venv:$action" -- 'deactiving"...'
         deactivate
         cmd-echo --id "venv:$action" -- 'Done.'
-    elif [[ -z $VIRTUAL_ENV ]]; then
-        cmd-echo --id "venv:$action" -- '"VIRTUAL_ENV" is set; nothing to do.'
     else
-        cmd-echo -n --id "venv:$action" -- 'Unsetting VIRTUAL_ENV...'
-        unset VIRTUAL_ENV
-        echo " Done."
+        cmd-echo --id "venv:$action" --wc -- '"deactivate" function not found. Not in a venv?.'
     fi
 }
 
-# vv => venv_verification
-_venv_verify_should_not_specify_a_venv_dir()
+_venv_destroy ()
 {
-    if [[ -n ${opts[venv_dir_provided]} ]]; then
-        cmd-echo --id "venv:$1" -ec -- "Cannot $1 with '${opts[venv_dir_provided]}'; $1 only applies to the current venv."
+    declare action=${FUNCNAME[0]//_venv_}
+
+    if is-a-function 'deactivate'; then
+        cmd-echo --id "venv:$action" -- 'deactiving"...'
+        deactivate
+        cmd-echo --id "venv:$action" -- 'Done.'
+        cmd-echo --id "venv:$action" -- 'Removing venv dir...'
+        rm -rf "${PYTHON_VIRTUAL_ENV_SPEC}"
+        cmd-echo --id "venv:$action" -- 'Done.'
+        __venv_unassign_envvars
+    elif [[ -z $VIRTUAL_ENV ]]; then
+        cmd-echo --id "venv:$action" -- '"VIRTUAL_ENV" is not set; nothing to do.'
+    else
+        cmd-echo --id "venv:$action" --wc -- 'No "deactivate function found, but PYTHON_VIRTUAL_ENV is set. Nothing to do. Investigate.'
+    fi
+}
+
+__venv_unassign_envvars()
+{
+    unset PYTHON_VIRTUAL_ENV_SPEC
+    unset PYTHON_VIRTUAL_ENV_NAME
+    unset PYTHON_VIRTUAL_ENV_ROOT
+    unset PYTHON_VIRTUAL_ENV_INIT_FILE
+    unset PYTHON_VIRTUAL_ENV_INIT_SPEC
+    unset PYTHON_VIRTUAL_ENV_INITED_FILE
+    unset PYTHON_VIRTUAL_ENV_INITED_SPEC
+}
+
+__venv_verify_venv_dir_should_exist()
+{
+    if [[ ! -d .venv ]]; then
+        cmd-echo --id "venv:$1" -ec -- "Cannot $1 with '.venv'; directory not found."
         false; return
     fi
     true; return
 }
 
-_venv_verify_venv_dir_should_exist()
+__venv_verify_venv_dir_should_not_exist()
 {
-    if [[ ! -d ${opts[venv_dir]} ]]; then
-        cmd-echo --id "venv:$1" -ec -- "Cannot $1 with '${opts[venv_dir]}'; directory not found."
+    if [[ -e .venv ]]; then
+        cmd-echo --id "venv:$1" -ec -- "Cannot $1; directory '.venv' already exists: "
+        ls -la ".venv"
         false; return
     fi
     true; return
 }
 
-_venv_verify_venv_dir_should_not_exist()
-{
-    if [[ -e ${opts[venv_dir]} ]]; then
-        cmd-echo --id "venv:$1" -ec -- "Cannot $1; directory '${opts[venv_dir]}' already exists: "
-        ls -la "${opts[venv_dir]}"
-        false; return
-    fi
-    true; return
-}
-
-_venv_verify_should_not_be_in_a_venv()
+__venv_verify_should_not_be_in_a_venv()
 {
     if [[ -n $VIRTUAL_ENV ]]; then
         cmd-echo --id "venv:$1" -ec -- "Cannot $1 in a venv. Currently in $VIRTUAL_ENV."
@@ -170,7 +197,7 @@ _venv_verify_should_not_be_in_a_venv()
     true; return
 }
 
-_venv_verify_should_be_in_a_venv()
+__venv_verify_should_be_in_a_venv()
 {
     if [[ -z $VIRTUAL_ENV ]]; then
         cmd-echo --id "venv:$1" -ec -- "Cannot $1 outside a venv. VIRTUAL_ENV not defined."
@@ -179,12 +206,16 @@ _venv_verify_should_be_in_a_venv()
     true; return
 }
 
+__venv_usage()
+{
+    bash-usage venv "$PYTHON_EXE" -m venv -h
+}
+
 venv()
 {
-    opts=()
     local OPTSARGS
-    local shortopts='HDD:'
-    local longopts='help,dir:'
+    local shortopts='h'
+    local longopts='help'
     OPTSARGS=$(getopt -a -o "$shortopts" -l "$longopts" -n "${FUNCNAME[0]}" -- "$@") || return
     eval set -- "$OPTSARGS"
 
@@ -194,54 +225,22 @@ venv()
         [[ "$option" != '--' ]] && option=${option##-} && option=${option##-}
         case $option in
             h | help )
-                bash-usage venv
-                true; return
-                ;;
-            d | dir )
-                declare venv_dir=$1
-                shift
-
-                declare dn
-                dn="$(dirname "$venv_dir")"
-                declare rp
-                rp="$(realpath "$dn")"
-                if [[ $rp != "${PWD}" ]]; then
-                    cmd-echo --id venv -ec -- "venv dir must be in the current directory, not $dn ."
-                    false; return
-                fi
-
-                declare bn
-                bn=$(basename "$venv_dir")
-
-                if [[ ! $bn =~ ^\. ]]; then
-                    bn=".$bn"
-                    cmd-echo --id venv -wc -- "Best practice is for a venv dir to be \"hidden\". Using $bn for the name."
-                fi
-
-                opts[venv_dir]=$bn
-                opts[venv_dir_provided]=$bn
+                __venv_usage
+                set +x; true; return
                 ;;
             --) break ;; ## VITAL!!! Exits the while loop, no more options,
                          ## remaining $*, if any, are args
             *)
                 cmd-echo --id venv -ec -- "$option is an invalid option. See $0 --help"
-                false; return
+                set +x; false; return
                 ;;
         esac
     done
 
-    if [[ -z ${opts[venv_dir]} ]]; then
-        if [[ -n $VIRTUAL_ENV ]]; then
-            opts[venv_dir]=$VIRTUAL_ENV
-        else
-            opts[venv_dir]=".venv"
-        fi
-    fi
-
     local action=$1; shift
     if [[ -z $action ]]; then
-        bash-usage venv
-        true; return
+        __venv_usage
+        set +x; true; return
     fi
 
     # Shortcut processing here
@@ -254,53 +253,53 @@ venv()
     local action_func_name="_venv_${action}"
 
     if declare -F "$action_func_name" >/dev/null; then
-        shift ## the action
-
         case $action in
-            abandon )
+            abandon | destroy )
                 ;;
             create )
-                if ! _venv_verify_venv_dir_should_not_exist "$action" \
-                        || ! _venv_verify_should_not_be_in_a_venv "$action"; then
-                    false; return
+                if ! __venv_verify_venv_dir_should_not_exist "$action" \
+                        || ! __venv_verify_should_not_be_in_a_venv "$action"; then
+                    set +x; false; return
                 fi
                 ;;
             activate )
-                if ! _venv_verify_venv_dir_should_exist "$action" \
-                        || ! _venv_verify_should_not_be_in_a_venv "$action"; then
-                    false; return
+                if ! __venv_verify_venv_dir_should_exist "$action" \
+                        || ! __venv_verify_should_not_be_in_a_venv "$action"; then
+                    set +x; false; return
                 fi
                 ;;
-            switch )
-                if ! _venv_verify_should_be_in_a_venv "$action"; then
-                    false; return
+            cd | reinit | deactivate | edit )
+                if ! __venv_verify_should_be_in_a_venv "$action"; then
+                    set +x; false; return
                 fi
                 ;;
-            info | reinit | deactivate )
-                if ! _venv_verify_should_be_in_a_venv "$action" \
-                        || ! _venv_verify_should_not_specify_a_venv_dir "$action"; then
-                    false; return
+            info | show )
+                if ! __venv_verify_venv_dir_should_exist "$action" ; then
+                    set +x; false; return
+                fi
+                ;;
+            pip )
+                if ! __venv_verify_venv_dir_should_exist "$action" \
+                        || ! __venv_verify_should_be_in_a_venv "$action"; then
+                    set +x; false; return
                 fi
                 ;;
             help )
                 bash_usage venv
-                true; return
+                set +x; true; return
                 ;;
             * )
                 cmd-echo --id "venv:$action" -ec -- "'$action' not supported."
-                false; return
+                set +x; false; return
                 ;;
         esac
 
-        if [[ -n $VIRTUAL_ENV ]] \
-               && [[ $action != 'switch' ]]; then
-            _venv_assign_envvars
-        fi
         "$action_func_name" "$@"
-        return $?
+        declare dq=$?
+        set +x; return $dq
     else
         cmd-echo --id "$ceid" -ec --id venv-- "unknown env action '$action'"
-        false; return
+        set +x; false; return
     fi
 }
 
@@ -314,19 +313,20 @@ autotrack venv "$0"
 
 # shellcheck disable=SC2317 #https://github.com/koalaman/shellcheck/wiki/SC2317
 :<<'__PODUSAGE__'
-#line 287
+#line 288
 =head1 NAME
 
 venv - useful things to do with venv
 
 =head1 SYNOPSIS
 
- venv create [-d .name]
- venv info [-d .name]
- venv activate [-d .name]
- vevn switch [-d .name]
+ venv create
+ venv info|show
+ venv activate
  venv reinit
  venv deactivate
+ venv destroy
+ venv pip [install]
 
 =head1 DESCRIPTION
 
@@ -338,46 +338,45 @@ A collection of actions and data about a python venv.
 
 =item create
 
-Create a venv environment. Without the -d option, creates C<./.venv>. Will
-not function if you are already in a venv (as defined by the envvar
-VIRTUAL_ENV).
+Create a venv environment. Will not function if you are already in a venv (as
+defined by the envvar VIRTUAL_ENV).
 
-venvs must live in local, hidden files (for now). A directory will be rejected
-if it does not resolve to PWD. A name without a leading dot will have one added.
-
-A file C<.name.init> will also be created in the current directory with
+A file C<.venv.init> will also be created in the current directory with
 commands to take to initialize the venv the first time it is activated.
 
-=item info
+=item info|show
 
-Show the venv config information. Without the -d option, queries
-C<$VIRTUAL_ENV/pyvenv.cfg>, then C<./.venv/pyvenv.cfg>.
+Show the venv config information, querying C<$VIRTUAL_ENV/pyvenv.cfg>, then
+C<$VIRTUAL_ENV/pyvenv.cfg>.
 
 =item activate
 
-Starts up the requested venv. Without the -d option, runs
-C<./.venv/bin/acrivate>. Will not function if you are already in a venv (as
-defined by the envvar VIRTUAL_ENV).
+Starts up the requested venv. Will not function if you are already in a venv
+(as defined by the envvar VIRTUAL_ENV).
 
-Also looks for the file C<.name.inited>) and if not found, runs C<.name.init>
-if it is found. If the init is successful, C<.name.ininted> is created to
-prevent init re-execution.
-
-=item swtich
-
-deactivate the current venv and activate the requested one. Without the -d
-option, assumes C<.venv>.
+Also looks for the file C<.venv.inited> in .venv and, if not found, runs
+C<.venv.init> if it is found. If the init is successful, C<.venv.ininted> is
+created to prevent init re-execution.
 
 =item reinit
 
-Rerun the C<.name.init> script, even if it has been previously run.
+Rerun the C<.venv.init> script, even if it has been previously run.
 
 =item deactivate
 
-Exit the current venv. Will not funtion if you provide a name arg or are not in
-a venv (as defined by the envvar VIRTUAL_ENV).
+Exit the current venv. Will not funtion if you are not in a venv (as defined by
+the envvar VIRTUAL_ENV).
+
+=item destroy
+
+Exit the current venv. Remove the .venv subdir.
 
 =back
+
+=item pip
+
+Runs pip install but adds the requested package to the .venv.init file so you
+don't have to re-run the command if you re-init the venv.
 
 =head1 OPTIONS
 
