Periodic
bin/from-ext
o Added script-echo.

bin/git-branch-list
o Added script-echo.

bin/git-check-with-remote
o Added script-echo.

bin/git-clone
o Convert echos to script-echos.

bin/git-commit-with-changelog
o Added script-echo.

bin/git-diff-two-repos-on-disk
o Added script-echo.

bin/script-echo
o New - func-echo analogue.

bin/xo
o Added script-echo.

functions/func-echo
o Comment update.

diff --git a/bin/git-check-with-remote b/bin/git-check-with-remote
--- a/bin/git-check-with-remote
+++ b/bin/git-check-with-remote
@@ -24,13 +24,13 @@ do
         -b|--branch) opt_branch="$2"; shift; shift ;;
         -h|--help) $usage-func $iam; exit $OK ;;
         --) shift; break ;; ## end of opts, remaining $*, if any, are args
-        *) echo "Internal error!"; $usage_func $iam; exit $NOT_OK ;;
+        *) script-echo -s $0 "Internal error!"; $usage_func $iam; exit $NOT_OK ;;
     esac
 done
 
 if [ -z "$opt_branch" ]
 then
-    echo "--branch required"
+    script-echo -s $0 "--branch required"
     $usage_func $iam
     exit $NOT_OK
 fi
@@ -90,7 +90,7 @@ check.
 EOF
     if ((opt_bail_on_dirty))
     then
-        echo Exiting.
+        script-echo -s $0 Exiting.
         exit $NOT_OK
     else
         declare resp=$(func-yesno "Do you want to continue anyway" n)
@@ -137,12 +137,10 @@ then
     if [ "$(cat $difflog | wc -l)" = '10' ] \
            && [ ! "$(grep -E "Merge pull request.*$(git-get-current-branch)" $difflog)" = '' ]
     then
-        echo "Only diff to ${opt_remote} is merge pull request."
+        script-echo -s $0 "Only diff to ${opt_remote} is merge pull request."
     else
-        echo
-        echo "*** git repo: $(pwd)"
-        echo "*** Current branch $(git-get-current-branch) and ${opt_remote}/${opt_branch} are not synced:"
-        echo
+        script-echo -s $0 -head "*** git repo: $(pwd)"
+        script-echo -s $0 -c "*** Current branch $(git-get-current-branch) and ${opt_remote}/${opt_branch} are not synced:"
         cat $difflog
     fi
 fi
diff --git a/bin/git-commit-with-changelog b/bin/git-commit-with-changelog
--- a/bin/git-commit-with-changelog
+++ b/bin/git-commit-with-changelog
@@ -10,7 +10,7 @@ declare pwd=$(pwd)
 declare gr=$(git-root)
 if [ ! "$pwd" = "$gr" ]
 then
-    echo "Current directory ($pwd) is not the git root ($gr)"
+    script-echo -s $0 "Current directory ($pwd) is not the git root ($gr)"
     declare resp=$(func-yesno "Go there")
     if [ "$resp" = 'n' ]
     then
@@ -54,7 +54,7 @@ do
             moreopts=0
             ;;
         * )
-            echo "$original is an invalid option. See $0 --help"; exit $NOT_OK;;
+            script-echo -s $0 "$original is an invalid option. See $0 --help"; exit $NOT_OK;;
     esac
 done
 
diff --git a/bin/git-diff-two-repos-on-disk b/bin/git-diff-two-repos-on-disk
--- a/bin/git-diff-two-repos-on-disk
+++ b/bin/git-diff-two-repos-on-disk
@@ -30,7 +30,7 @@ do
         --)
             shift; break ;; ## end of opts, remaining $*, if any, are args
         *)
-            echo "Internal error!"; script-usage ; exit $NOT_OK ;;
+            script-echo -s $0 "Internal error!"; script-usage ; exit $NOT_OK ;;
     esac
 done
 
@@ -44,13 +44,13 @@ then
     repo[this]=$(pwd)
     repo[other]=$(realpath $1)
 else
-    echo "Need at least one directory"
+    script-echo -s $0 "Need at least one directory"
     script-usage; exit $NOT_OK ;
 fi
 
 if [ ${repo[this]} = ${repo[other]} ]
 then
-    echo Other dir is this dir. Whoops! Bye.
+    script-echo -s $0 Other dir is this dir. Whoops! Bye.
     exit $NOT_OK
 fi
 
@@ -89,14 +89,14 @@ do
             declare output=$(diff -q "${repo[$which]}/$line" "${repo[${opposed[$which]}]}/$line" 2>&1 | grep -v 'Common subdirectories')
             if [[ "$output" =~ 'No such file or directory' ]]
             then
-                echo "Copying ${repo[$which]}/$line ${repo[${opposed[$which]}]}/$line"
+                script-echo -s $0 "Copying ${repo[$which]}/$line ${repo[${opposed[$which]}]}/$line"
                 cp -vf ${repo[$which]}/$line ${repo[${opposed[$which]}]}/$line
             elif [ -n "$output" ]
             then
-                echo '-----'
+                script-echo -s $0 '-----'
                 declare diffcmd=$(which colordiff 2>/dev/null)
                 ( [ -z "$diffcmd" ] || ((nocolor)) ) && diffcmd=diff
-                echo $diffcmd $side_by_side "${repo[$which]}/$line" "${repo[${opposed[$which]}]}/$line"
+                script-echo -s $0 $diffcmd $side_by_side "${repo[$which]}/$line" "${repo[${opposed[$which]}]}/$line"
                 $diffcmd $side_by_side "${repo[$which]}/$line" "${repo[${opposed[$which]}]}/$line"
                 echo
             fi
