func to exec, convert phase

diff --git a/bin/git-check-with-remote b/bin/git-check-with-remote
--- a/bin/git-check-with-remote
+++ b/bin/git-check-with-remote
@@ -1,50 +1,47 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-check-with-remote
 
-git-check-with-remote ()
-{
-    ##@@ 0001||group||git-check-with-remote||
+##@@ 0001||group||git-check-with-remote||
 
-    local usage_func="${FUNCNAME}-usage"
-    local iam=$(func-name-spoof)
+declare usage_func="${FUNCNAME}-usage"
+declare iam=$(func-name-spoof)
 
-    local opt_branch=''
-    local opt_remote='origin'
-    local opt_bail_on_dirty='0'
-    local OPTSARGS=$(getoptp -o hb:r:c --long help,branch:,remote:,bail_on_dirty -n $iam -- "$@")
-    status=$?
-    ((status != 0)) && $usage_func $iam && return $status
-    eval set -- "$OPTSARGS"
-    while true
-    do
-        case "$1" in
-            --bail_on_dirty) opt_bail_on_dirty=1; shift;;
-            -r|--remote) opt_remote="$2"; shift; shift ;;
-            -b|--branch) opt_branch="$2"; shift; shift ;;
-            -h|--help) $usage-func $iam; return $OK ;;
-            --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) echo "Internal error!"; $usage_func $iam; return $NOT_OK ;;
-        esac
-    done
+declare opt_branch=''
+declare opt_remote='origin'
+declare opt_bail_on_dirty='0'
+declare OPTSARGS=$(getoptp -o hb:r:c --long help,branch:,remote:,bail_on_dirty -n $iam -- "$@")
+status=$?
+((status != 0)) && $usage_func $iam && exit $status
+eval set -- "$OPTSARGS"
+while true
+do
+    case "$1" in
+        --bail_on_dirty) opt_bail_on_dirty=1; shift;;
+        -r|--remote) opt_remote="$2"; shift; shift ;;
+        -b|--branch) opt_branch="$2"; shift; shift ;;
+        -h|--help) $usage-func $iam; exit $OK ;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; $usage_func $iam; exit $NOT_OK ;;
+    esac
+done
 
-    if [ -z "$opt_branch" ]
-    then
-        echo "--branch required"
-        $usage_func $iam
-        return $NOT_OK
-    fi
+if [ -z "$opt_branch" ]
+then
+    echo "--branch required"
+    $usage_func $iam
+    exit $NOT_OK
+fi
 
-    local cb=$(git rev-parse --abbrev-ref HEAD)
-    status=$?
-    ((status != 0 )) && return $NOT_OK
+declare cb=$(git rev-parse --abbrev-ref HEAD)
+status=$?
+((status != 0 )) && exit $NOT_OK
 
-    if [ "$cb" == '' ]
-    then
-        cat <<EOF
+if [ "$cb" == '' ]
+then
+    cat <<EOF
 
-$iam is used to check your current git repo DEVELOPMENT branch in your local
+$iam is used to check your current git repo DEVELOPMENT branch in your declare
 clone against changes in
 
 branch "${opt_branch}"
@@ -54,14 +51,14 @@ However, you do not appear to even be in a repo. I'm exiting. Try again in a
 proper repo.
 
 EOF
-        return $NOT_OK
-    fi
+    exit $NOT_OK
+fi
 
-    if [ "$cb" == "$opt_branch" ]
-    then
-        cat <<EOF
+if [ "$cb" == "$opt_branch" ]
+then
+    cat <<EOF
 
-$iam is used to check your current git repo DEVELOPMENT branch in your local
+$iam is used to check your current git repo DEVELOPMENT branch in your declare
 clone against changes in
 
 branch "${opt_branch}"
@@ -73,76 +70,75 @@ branch Then rerun the command. Or just do a 'git pull' if you really need to
 refresh this branch.
 
 EOF
-        return $NOT_OK
-    fi
+    exit $NOT_OK
+fi
 
-    ## Check the local branch against its origin
-    stcheck=$(mktemp --suffix=.git-check-with-remote.1)
-    git status 1>$stcheck 2>&1
-    grep "Your branch is up.to.date with 'origin/$cb'." $stcheck 1>/dev/null
-    status=$?
-    if [ "$status" != '0' ]
-    then
-        cat $stcheck
-        cat <<EOF
+## Check the declare branch against its origin
+stcheck=$(mktemp --suffix=.git-check-with-remote.1)
+git status 1>$stcheck 2>&1
+grep "Your branch is up.to.date with 'origin/$cb'." $stcheck 1>/dev/null
+status=$?
+if [ "$status" != '0' ]
+then
+    cat $stcheck
+    cat <<EOF
 Your branch should be up to date with its origin in order to simplify the
 check.
 EOF
-        if ((opt_bail_on_dirty))
+    if ((opt_bail_on_dirty))
+    then
+        echo Exiting.
+        exit $NOT_OK
+    else
+        declare resp=$(func-yesno "Do you want to continue anyway" n)
+        if [ "$resp" == 'n' ]
         then
-            echo Exiting.
-            return $NOT_OK
-        else
-            local resp=$(func-yesno "Do you want to continue anyway" n)
-            if [ "$resp" == 'n' ]
-            then
-                return $NOT_OK
-            fi
+            exit $NOT_OK
         fi
     fi
+fi
 
-    local ok_to_pull=1
-    ((opt_confirm)) && ok_to_pull=0
+declare ok_to_pull=1
+((opt_confirm)) && ok_to_pull=0
 
-    ## Now grab the remote branch
-    local gflog=$(mktemp --suffix=.git-check-with-remote.2)
-    git fetch ${opt_remote} ${opt_branch} 2>$gflog
-    local rc=$?
-    if ((rc))
-    then
-        cat $gflog
-        rm -f $gflog
-        return $NOT_OK
-    fi
+## Now grab the remote branch
+declare gflog=$(mktemp --suffix=.git-check-with-remote.2)
+git fetch ${opt_remote} ${opt_branch} 2>$gflog
+declare rc=$?
+if ((rc))
+then
+    cat $gflog
     rm -f $gflog
+    exit $NOT_OK
+fi
+rm -f $gflog
 
-    ## Log the local branch
-    local locallog=$(mktemp --suffix=.git-check-with-remote.locallog)
-    git log > $locallog
+## Log the declare branch
+declare locallog=$(mktemp --suffix=.git-check-with-remote.locallog)
+git log > $locallog
 
-    ## Log the local copy of the remote branch
-    local remotelog=$(mktemp --suffix=.git-check-with-remote.remotelog)
-    git log ${opt_remote}/${opt_branch} > $remotelog
+## Log the declare copy of the remote branch
+declare remotelog=$(mktemp --suffix=.git-check-with-remote.remotelog)
+git log ${opt_remote}/${opt_branch} > $remotelog
 
-    ## Diff 'em
-    local difflog=$(mktemp --suffix=.git-check-with-remote.difflog)
-    diff $locallog $remotelog 1> $difflog 2>&1
+## Diff 'em
+declare difflog=$(mktemp --suffix=.git-check-with-remote.difflog)
+diff $locallog $remotelog 1> $difflog 2>&1
 
-    if [ -s $difflog ]
+if [ -s $difflog ]
+then
+    if [ "$(cat $difflog | wc -l)" = '10' ] \
+           && [ ! "$(grep -E "Merge pull request.*$(git-get-current-branch)" $difflog)" = '' ]
     then
-        if [ "$(cat $difflog | wc -l)" = '10' ] \
-               && [ ! "$(grep -E "Merge pull request.*$(git-get-current-branch)" $difflog)" = '' ]
-        then
-            echo "Only diff to ${opt_remote} is merge pull request."
-        else
-            echo
-            echo "*** git repo: $(pwd)"
-            echo "*** Current branch $(git-get-current-branch) and ${opt_remote}/${opt_branch} are not synced:"
-            echo
-            cat $difflog
-        fi
+        echo "Only diff to ${opt_remote} is merge pull request."
+    else
+        echo
+        echo "*** git repo: $(pwd)"
+        echo "*** Current branch $(git-get-current-branch) and ${opt_remote}/${opt_branch} are not synced:"
+        echo
+        cat $difflog
     fi
+fi
 
-    rm -f $locallog $remotelog $difflog
-    return $OK
-}
+rm -f $locallog $remotelog $difflog
+exit $OK
diff --git a/bin/git-hook-pushpull-guts b/bin/git-hook-pushpull-guts
--- a/bin/git-hook-pushpull-guts
+++ b/bin/git-hook-pushpull-guts
@@ -1,71 +1,67 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-hook-pushpull-guts
 
-git-hook-pushpull-guts ()
-{
-    local REPOS="$@"
+declare REPOS="$@"
 
-    local current_template=$(git config --get init.templatedir)
-    if [ "$current_template" != "${gitfuncs_githook_root}" ]
-    then
-        echo "Error: Config says init.templatedir = '$current_template'"
-        echo "       It should be '${gitfuncs_githook_root}'"
-        echo "       Please correct."
-        return $NOT_OK
-    fi
+declare current_template=$(git config --get init.templatedir)
+if [ "$current_template" != "${gitfuncs_githook_root}" ]
+then
+    echo "Error: Config says init.templatedir = '$current_template'"
+    echo "       It should be '${gitfuncs_githook_root}'"
+    echo "       Please correct."
+    exit $NOT_OK
+fi
 
-    if [ ! -d "$current_template" ]
-    then
-        echo "Error: Can't find '$current_template'"
-        echo "       Please correct."
-        return $NOT_OK
-    fi
+if [ ! -d "$current_template" ]
+then
+    echo "Error: Can't find '$current_template'"
+    echo "       Please correct."
+    exit $NOT_OK
+fi
 
-    local hooks
-    hooks=$(ls ${gitfuncs_githook_dir}/*)
+declare hooks
+hooks=$(ls ${gitfuncs_githook_dir}/*)
 
-    local REPO
-    for REPO in $REPOS
+declare REPO
+for REPO in $REPOS
+do
+    (($# > 1)) && echo "== $REPO"
+    for h in $hooks
     do
-        (($# > 1)) && echo "== $REPO"
-        for h in $hooks
-        do
-            local hooktgtdir="${TILDAE:-$HOME}/$(git-strip-repo $REPO)/.git/hooks"
-            if [ -f $hooktgtdir ]
-            then
-                echo $hooktgtdir is a file. whoops....
-                ## Fix up accidental directory overwrite
-                \rm $hooktgtdir
-                mkdir $hooktgtdir
-            fi
+        declare hooktgtdir="${TILDAE:-$HOME}/$(git-strip-repo $REPO)/.git/hooks"
+        if [ -f $hooktgtdir ]
+        then
+            echo $hooktgtdir is a file. whoops....
+            ## Fix up accidental directory overwrite
+            \rm $hooktgtdir
+            mkdir $hooktgtdir
+        fi
 
-            local hooktgtpath="$hooktgtdir/$(basename $h)"
-            if [ ! -e $hooktgtpath ] || [ $h -nt $hooktgtpath ]
+        declare hooktgtpath="$hooktgtdir/$(basename $h)"
+        if [ ! -e $hooktgtpath ] || [ $h -nt $hooktgtpath ]
+        then
+            if [ ! -e $hooktgtpath ]
             then
-                if [ ! -e $hooktgtpath ]
-                then
-                    echo "$hooktgtpath not found. Copying from $h..."
-                elif [ $h -nt $hooktgtpath ]
-                then
-                    echo "$hooktgtpath out of date. Updating from $h..."
-                fi
-                cp -pv $h $hooktgtpath
-                chmod +x $hooktgtpath
-            elif [ $h -ot $hooktgtpath ]
+                echo "$hooktgtpath not found. Copying from $h..."
+            elif [ $h -nt $hooktgtpath ]
             then
-                local tmpout=$(mktempv --suffix=.git-push-hook)
-                diff  $h  $hooktgtpath 1>$tmpout 2>&1
-                if [ -s $tmpout ]
-                then
-                    echo "$hooktgtpath newer than $h. Here's the diff, older to newer:"
-                    cat $tmpout
-                fi
-                rm -f $tmpout
-            else
-                echo "$hooktgtpath up to date"
+                echo "$hooktgtpath out of date. Updating from $h..."
             fi
-        done
+            cp -pv $h $hooktgtpath
+            chmod +x $hooktgtpath
+        elif [ $h -ot $hooktgtpath ]
+        then
+            declare tmpout=$(mktempv --suffix=.git-push-hook)
+            diff  $h  $hooktgtpath 1>$tmpout 2>&1
+            if [ -s $tmpout ]
+            then
+                echo "$hooktgtpath newer than $h. Here's the diff, older to newer:"
+                cat $tmpout
+            fi
+            rm -f $tmpout
+        else
+            echo "$hooktgtpath up to date"
+        fi
     done
-}
+done
diff --git a/bin/git-status-with-changelog b/bin/git-status-with-changelog
--- a/bin/git-status-with-changelog
+++ b/bin/git-status-with-changelog
@@ -1,69 +1,65 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-status-with-changelog
 
-git-status-with-changelog ()
-{
-    ##@@ 0001||group||git-status-with-changelog||Mix in $GITFUNCS_CHANGELOG_NAME text with corresponding file entries in git status.
+##@@ 0001||group||git-status-with-changelog||Mix in $GITFUNCS_CHANGELOG_NAME text with corresponding file entries in git status.
 
-    local usage_func="${FUNCNAME}-usage"
+declare usage_func="${FUNCNAME}-usage"
 
-    local diff
-    local noless
-    local cdok=0
-    OPTSARGS=$(getoptp -o sh --long diff,noless,cdok,help -n $FUNCNAME -- "$@")
-    local status=$?
-    ((status != 0)) && $usage_func && return $status
+declare diff
+declare noless
+declare cdok=0
+OPTSARGS=$(getoptp -o sh --long diff,noless,cdok,help -n $FUNCNAME -- "$@")
+declare status=$?
+((status != 0)) && $usage_func && exit $status
 
-    eval set -- "$OPTSARGS"
-    while true
-    do
-        case "$1" in
-            --cdok) cdok=1; shift ;;
-            --diff) diff='--diff'; shift ;;
-            --noless) noless='--noless'; shift ;;
-            -h|--help) $usage_func; return $OK ;;
-            --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) echo "Internal error!"; $usage_func; return $NOT_OK ;;
-        esac
-    done
+eval set -- "$OPTSARGS"
+while true
+do
+    case "$1" in
+        --cdok) cdok=1; shift ;;
+        --diff) diff='--diff'; shift ;;
+        --noless) noless='--noless'; shift ;;
+        -h|--help) $usage_func; exit $OK ;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; $usage_func; exit $NOT_OK ;;
+    esac
+done
 
-    ## All of the *-changelog functions work best in the git-root, which is
-    ## where the $GITFUNCS_CHANGELOG_NAME is anyway
-    local pwd=$(pwd)
-    local gr=$(git-root)
-    if [ ! "$pwd" = "$gr" ]
+## All of the *-changelog functions work best in the git-root, which is
+## where the $GITFUNCS_CHANGELOG_NAME is anyway
+declare pwd=$(pwd)
+declare gr=$(git-root)
+if [ ! "$pwd" = "$gr" ]
+then
+    if ((!cdok))
     then
-        if ((!cdok))
+        echo "Current directory ($pwd) is not the git root ($gr)"
+        declare resp=$(func-yesno "Go there")
+        if [ "$resp" = 'n' ]
         then
-            echo "Current directory ($pwd) is not the git root ($gr)"
-            local resp=$(func-yesno "Go there")
-            if [ "$resp" = 'n' ]
-            then
-                return $NOT_OK
-            fi
+            exit $NOT_OK
         fi
-        _git-cd-to $gr  || return $?
-    else
-        gr=''
     fi
+    _git-cd-to $gr  || exit $?
+else
+    gr=''
+fi
 
-    local args="$@"
-    if [ -z "$args" ]
-    then
-        args=$($DEBUG_GIT_STATUS_PARSE $(which git-status-parse) --all) ## matches default git status setting
-    fi
-    local out=$(mktemp --suffix=.git-status-with-changelog)
-    git-process-changelog --withstatus $diff $noless $args 1>$out 2>&1
-    if [ -n "$noless" ]
-    then
-        cat $out
-    else
-        less -RE $out
-    fi
-    \rm -f $out
-    status=$?
-    [ -n "$gr" ] && _git-cd-return
-    return $?
-}
+declare args="$@"
+if [ -z "$args" ]
+then
+    args=$($DEBUG_GIT_STATUS_PARSE $(which git-status-parse) --all) ## matches default git status setting
+fi
+declare out=$(mktemp --suffix=.git-status-with-changelog)
+git-process-changelog --withstatus $diff $noless $args 1>$out 2>&1
+if [ -n "$noless" ]
+then
+    cat $out
+else
+    less -RE $out
+fi
+\rm -f $out
+status=$?
+[ -n "$gr" ] && _git-cd-exit
+exit $?
diff --git a/bin/git-sync-with-remote b/bin/git-sync-with-remote
--- a/bin/git-sync-with-remote
+++ b/bin/git-sync-with-remote
@@ -1,55 +1,52 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-sync-with-remote
 
-git-sync-with-remote ()
-{
-    ##@@ 0001||group||git-sync-with-remote||
+##@@ 0001||group||git-sync-with-remote||
 
-    local usage_func="${FUNCNAME}-usage"
-    local iam=$(func-name-spoof)
+declare usage_func="${FUNCNAME}-usage"
+declare iam=$(func-name-spoof)
 
-    local opt_branch=''
-    local opt_remote='origin'
-    local opt_confirm='0'
-    local opt_stash='0'
-    local do_stash='0'
+declare opt_branch=''
+declare opt_remote='origin'
+declare opt_confirm='0'
+declare opt_stash='0'
+declare do_stash='0'
 
-    local OPTSARGS=$(getoptp -o hb:r:c --long help,branch:,remote:,confirm -n $iam -- "$@")
-    status=$?
-    ((status != 0)) && $usage_func && return $status
-    eval set -- "$OPTSARGS"
-    while true
-    do
-        case "$1" in
-            -s|--stash) opt_stash=1; shift;;
-            -c|--confirm) opt_confirm=1; shift;;
-            -r|--remote) opt_remote="$2"; shift; shift ;;
-            -b|--branch) opt_branch="$2"; shift; shift ;;
-            -h|--help) $usage_func $iam; return $OK ;;
-            --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) func-echo "Internal error!"; $usage-func $iam; return $NOT_OK ;;
-        esac
-    done
+declare OPTSARGS=$(getoptp -o hb:r:c --long help,branch:,remote:,confirm -n $iam -- "$@")
+status=$?
+((status != 0)) && $usage_func && exit $status
+eval set -- "$OPTSARGS"
+while true
+do
+    case "$1" in
+        -s|--stash) opt_stash=1; shift;;
+        -c|--confirm) opt_confirm=1; shift;;
+        -r|--remote) opt_remote="$2"; shift; shift ;;
+        -b|--branch) opt_branch="$2"; shift; shift ;;
+        -h|--help) $usage_func $iam; exit $OK ;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) func-echo "Internal error!"; $usage-func $iam; exit $NOT_OK ;;
+    esac
+done
 
-    if [ -z "$opt_branch" ]
-    then
-        func-echo "--branch required"
-        $usage-func $iam
-        return $NOT_OK
-    fi
+if [ -z "$opt_branch" ]
+then
+    func-echo "--branch required"
+    $usage-func $iam
+    exit $NOT_OK
+fi
 
-    local cb=$(git rev-parse --abbrev-ref HEAD)
-    status=$?
-    ((status != 0 )) && return $NOT_OK
+declare cb=$(git rev-parse --abbrev-ref HEAD)
+status=$?
+((status != 0 )) && exit $NOT_OK
 
-    if [ "$cb" == '' ]
-    then
-        func-echo
-        cat <<EOF
+if [ "$cb" == '' ]
+then
+    func-echo
+    cat <<EOF
 
-$iam is used to keep your current git repo DEVELOPMENT branch in your local
+$iam is used to keep your current git repo DEVELOPMENT branch in your declare
 clone in sync with changes in
 
 branch "${opt_branch}"
@@ -59,20 +56,20 @@ However, you do not appear to even be in a repo. I'm exiting. Try again in a
 proper repo.
 
 EOF
-        return $NOT_OK
-    fi
+    exit $NOT_OK
+fi
 
-    if [ "$cb" == "$opt_branch" ]
+if [ "$cb" == "$opt_branch" ]
+then
+    func-echo
+    declare msgoverride=$(find $(git-root) -name .git-sync-with-remove.txt)
+    if [ -n "$msgoverride" ] && [ -r "$msgoverride" ]
     then
-        func-echo
-        local msgoverride=$(find $(git-root) -name .git-sync-with-remove.txt)
-        if [ -n "$msgoverride" ] && [ -r "$msgoverride" ]
-        then
-            cat $msgoverride
-        else
-            cat <<EOF
+        cat $msgoverride
+    else
+        cat <<EOF
 
-$iam is used to keep your current git repo DEVELOPMENT branch in your local
+$iam is used to keep your current git repo DEVELOPMENT branch in your declare
 clone in sync with changes in
 
 branch "${opt_branch}"
@@ -84,135 +81,135 @@ another branch. Then rerun the command. Or just do a 'git status' to check this
 branch or a 'git pull' if you really need to refresh this branch.
 
 EOF
-        fi
-        return $NOT_OK
     fi
+    exit $NOT_OK
+fi
 
-    ## Stash any modified items before checking and proceeding.
-    local needs_stash=$(echo $(git-is-staged && git-is-unstaged) | wc -w)
-    if ((needs_stash))
+## Stash any modified items before checking and proceeding.
+declare needs_stash=$(echo $(git-is-staged && git-is-unstaged) | wc -w)
+if ((needs_stash))
+then
+    if ((opt_stash))
     then
-        if ((opt_stash))
-        then
-            do_stash=1
-        else
-            git status
-            local resp=$(func-yesno "Stash" n)
-            if [ "$resp" = 'n' ]
-            then
-                func-echo "Will not proceed without a stash"
-                return $NOT_OK
-            else
-                do_stash=1
-            fi
-        fi
+        do_stash=1
     else
-        if ((opt_stash))
+        git status
+        declare resp=$(func-yesno "Stash" n)
+        if [ "$resp" = 'n' ]
         then
-            func-echo "stash not needed"
-        fi
-    fi
-    if ((do_stash))
-    then
-        git stash
-        status=$?
-        if [ "$status" = '0' ]
-        then
-            ok_to_pop=1
+            func-echo "Will not proceed without a stash"
+            exit $NOT_OK
         else
-            return $status
+            do_stash=1
         fi
     fi
-
-    ## Grab head of log
-    local oldsha=$(git-log-grab-sha -1)
-    func-echo --head 'Log before pull:'
-    git-log-shas-range $oldsha $oldsha
-
-    ## Check the local branch against its origin
-    stcheck=$(mktemp --suffix=.git-sync-with-remote)
-    git status 1>$stcheck 2>&1
-    grep "Your branch is up.to.date with 'origin/$cb'." $stcheck 1>/dev/null
-    status=$?
-    if [ "$status" != '0' ]
+else
+    if ((opt_stash))
     then
-        func-echo
-        cat $stcheck
-        cat <<EOF
+        func-echo "stash not needed"
+    fi
+fi
+if ((do_stash))
+then
+    git stash
+    status=$?
+    if [ "$status" = '0' ]
+    then
+        ok_to_pop=1
+    else
+        exit $status
+    fi
+fi
+
+## Grab head of log
+declare oldsha=$(git-log-grab-sha -1)
+func-echo --head 'Log before pull:'
+git-log-shas-range $oldsha $oldsha
+
+## Check the declare branch against its origin
+stcheck=$(mktemp --suffix=.git-sync-with-remote)
+git status 1>$stcheck 2>&1
+grep "Your branch is up.to.date with 'origin/$cb'." $stcheck 1>/dev/null
+status=$?
+if [ "$status" != '0' ]
+then
+    func-echo
+    cat $stcheck
+    cat <<EOF
 Your branch should be up to date with its origin in order to simplify the
 rebase.
 EOF
-        local resp=$(func-yesno "Do you want to continue anyway" n)
+    declare resp=$(func-yesno "Do you want to continue anyway" n)
+    if [ "$resp" == 'n' ]
+    then
+        if ((do_stash))
+        then
+            func-echo 'Stash pop...'
+            git stash pop
+        fi
+        exit $OK
+    fi
+fi
+
+declare ok_to_pull=1
+((opt_confirm)) && ok_to_pull=0
+
+func-echo 'Fetching to check...'
+git fetch ${opt_remote} ${opt_branch}
+
+declare diffoutput=$(mktemp --suffix=.gf-syr)
+git diff ...${opt_remote} > $diffoutput 2>&1
+declare diffc=$(cat $diffoutput | wc -l)
+if ((diffc)) && ((opt_confirm))
+then
+    func-echo --head "===== diffs ====="
+    cat $diffoutput
+    \rm $diffoutput
+fi
+
+declare logoutput=$(mktemp --suffix=.gf-syr)
+git log ...${opt_remote} > $logoutput 2>&1
+declare logc=$(cat $logoutput | wc -l)
+if ((logc)) && ((opt_confirm))
+then
+    ((diffc)) && echo
+    func-echo "=====  log  ====="
+    cat $logoutput
+    \rm $logoutput
+fi
+
+if ((diffc)) || ((logc))
+then
+    if ((opt_confirm))
+    then
+        declare resp=$(func-yesno "Ok to pull" n)
         if [ "$resp" == 'n' ]
         then
             if ((do_stash))
             then
                 func-echo 'Stash pop...'
                 git stash pop
-            fi
-            return $OK
-        fi
-    fi
-
-    local ok_to_pull=1
-    ((opt_confirm)) && ok_to_pull=0
-
-    func-echo 'Fetching to check...'
-    git fetch ${opt_remote} ${opt_branch}
-
-    local diffoutput=$(mktemp --suffix=.gf-syr)
-    git diff ...${opt_remote} > $diffoutput 2>&1
-    local diffc=$(cat $diffoutput | wc -l)
-    if ((diffc)) && ((opt_confirm))
-    then
-        func-echo --head "===== diffs ====="
-        cat $diffoutput
-        \rm $diffoutput
-    fi
-
-    local logoutput=$(mktemp --suffix=.gf-syr)
-    git log ...${opt_remote} > $logoutput 2>&1
-    local logc=$(cat $logoutput | wc -l)
-    if ((logc)) && ((opt_confirm))
-    then
-        ((diffc)) && echo
-        func-echo "=====  log  ====="
-        cat $logoutput
-        \rm $logoutput
-    fi
-
-    if ((diffc)) || ((logc))
-    then
-        if ((opt_confirm))
-        then
-            local resp=$(func-yesno "Ok to pull" n)
-            if [ "$resp" == 'n' ]
-            then
-                if ((do_stash))
-                then
-                    func-echo 'Stash pop...'
-                    git stash pop
-                    return $OK
-                fi
+                exit $OK
             fi
         fi
-    else
-        func-echo "No difference with remote."
-        if ((do_stash))
-        then
-            func-echo 'Stash pop...'
-            git stash pop
-        fi
-        return $OK
     fi
-
-    func-echo 'Pulling to sync...'
-    git pull --rebase ${opt_remote} ${opt_branch}
-    status=$?
-    if [ ! "$status" = '0' ]
+else
+    func-echo "No difference with remote."
+    if ((do_stash))
     then
-        func-echo
-        cat <<EOF
+        func-echo 'Stash pop...'
+        git stash pop
+    fi
+    exit $OK
+fi
+
+func-echo 'Pulling to sync...'
+git pull --rebase ${opt_remote} ${opt_branch}
+status=$?
+if [ ! "$status" = '0' ]
+then
+    func-echo
+    cat <<EOF
 
 It appears the pull --rebase was not successful. Assuming the issue was not a
 system issue, but rather related to conflicts:
@@ -236,75 +233,74 @@ your branch.
 Then push the branch up to your fork so you can submit a pull request.
 
 EOF
-        if ((do_stash))
-        then
-            func-echo "Leaving stash stashed so a not to further complicate the issue"
-        fi
-        return $NOT_OK
-    fi
-
-    ## Grab head of log
-    local newsha=$(git-log-grab-sha -1)
-
-    ## Show log
-    func-echo --head 'Log after pull:'
-    git-log-shas-range $oldsha $newsha
-
-    func-echo --head "pull --rebase successful. Pushing..."
-    git push
-    status=$?
-    if [ "$status" != '0' ]
+    if ((do_stash))
     then
-        resp=$(func-yesno "'git push' complained. Shall I re-push with --force" n)
-        if [ "$resp" = 'y' ]
-        then
-            git push --force
-            status=$?
-        fi
+        func-echo "Leaving stash stashed so a not to further complicate the issue"
     fi
+    exit $NOT_OK
+fi
 
-    local ask_pop=0
-    if [ ! "$status" = '0' ]
+## Grab head of log
+declare newsha=$(git-log-grab-sha -1)
+
+## Show log
+func-echo --head 'Log after pull:'
+git-log-shas-range $oldsha $newsha
+
+func-echo --head "pull --rebase successful. Pushing..."
+git push
+status=$?
+if [ "$status" != '0' ]
+then
+    resp=$(func-yesno "'git push' complained. Shall I re-push with --force" n)
+    if [ "$resp" = 'y' ]
     then
-        func-echo
-        cat <<EOF
+        git push --force
+        status=$?
+    fi
+fi
+
+declare ask_pop=0
+if [ ! "$status" = '0' ]
+then
+    func-echo
+    cat <<EOF
 It appears that the git push was not successful and you declined to use --force,
 or the --force was also unsuccessful.
 EOF
-        if ((do_stash))
-        then
-            func-echo
-            cat <<EOF
+    if ((do_stash))
+    then
+        func-echo
+        cat <<EOF
 It may be that you decided not to force the push since you still have work to do,
 in which case you will want to pop the latest stash.
 EOF
-            ask_pop=1
-        fi
+        ask_pop=1
     fi
+fi
 
-    if ((do_stash))
+if ((do_stash))
+then
+    resp='y'
+    if ((ask_pop))
     then
-        resp='y'
-        if ((ask_pop))
+        resp=$(func-yesno "Shall I pop the last git stash" n)
+    fi
+    if [ "$resp" = 'y' ]
+    then
+        func-echo 'Stash pop...'
+        git stash pop
+        status=$?
+        if ((status != 0))
         then
-            resp=$(func-yesno "Shall I pop the last git stash" n)
-        fi
-        if [ "$resp" = 'y' ]
-        then
-            func-echo 'Stash pop...'
-            git stash pop
-            status=$?
-            if ((status != 0))
-            then
-                func-echo
-                cat <<EOF
+            func-echo
+            cat <<EOF
 It appears that the stash pop failed. There may be conflicts. Once you fix the
 conflicts, you can drop the stash, as all of the non-conflicted files were
 successfully popped - that's the way that git stashes work.
 EOF
-                return $?
-            fi
+            exit $?
         fi
     fi
+fi
 
-}
