Periodic
bin/cmd-echo
* All colors were rev and no rev was no colors. Fixed.

bin/git-branch
* Colorized cmd-echo errors.

bin/git-check-with-remote
* Colorized cmd-echo errors.

bin/git-clone
* Colorized cmd-echo errors.

bin/git-ping
* Modernize cmd-echo calls.

bin/git-repo
* Remove cmd-echo error redirects; now in the command.

bin/git-sync-with-remote
* Colorized cmd-echo errors.

bin/git-worktree
* Colorized cmd-echo errors.

bin/logit
* Colorized cmd-echo errors.

bin/makesymlink
* Colorized cmd-echo errors.

bin/md2html
* Colorized cmd-echo errors.

bin/toxic
* Colorized cmd-echo errors.

bin/withwhich
* Remove cmd-echo error redirects; now in the command.

diff --git a/bin/git-ping b/bin/git-ping
--- a/bin/git-ping
+++ b/bin/git-ping
@@ -1,13 +1,7 @@
 #!/usr/bin/env bash
 
-echo "$(date): git-ping" >> "$HOME/.gitaudit"
-
 # git-ping
 
-declare echo_cmd="cmd-echo"
-## If there's any chance that this will be in a script that will be dotted in,
-## remove the explicit out_cmd calls.
-declare out_cmd="exit"
 declare moreopts=1
 declare quiet=0
 declare silent=0
@@ -20,7 +14,7 @@ while [[ "$1" =~ ^- ]] && ((moreopts)); do
         ## standard options
         h | help )
             bash-usage "$0"
-            $out_cmd 0
+            true; exit $?
             ;;
         q | quiet )
             quiet=1 ;;
@@ -30,20 +24,20 @@ while [[ "$1" =~ ^- ]] && ((moreopts)); do
             moreopts=0
             ;;
         * )
-            $echo_cmd "$original is an invalid option. See $0 --help"
-            $out_cmd 1
+            cmd-echo --ec -- "$original is an invalid option. See $0 --help"
+            false; exit $?
             ;;
     esac
 done
 
 if ((silent+quiet==2)); then
-    $echo_cmd "Error:git-ping:cannot set --quiet and --silent" >&2
-    exit 1
+    cmd-echo --ec -- "cannot set --quiet and --silent"
+    false; exit $?
 fi
 
 if [[ -z "$1" ]]; then
-    $echo_cmd "Error:git-ping:missing repo" >&2
-    exit 1
+    cmd-echo --ec -- "missing repo"
+    false; exit $?
 fi
 
 if ((quiet+silent==1)); then
@@ -58,6 +52,6 @@ fi
 
 git ls-remote $quiet -h --exit-code "$1"
 
-$out_cmd $?
+exit $?
 
 ## Go grab the usage template the file USAGE
