In addition to shebang fixing...
bin/git-worktree
git-worktree-delete():
  * Account for multi-level branch names properly.

bin/process-source-ctrl-log
format_scl():
  * It appears that with an upgrade to a new git client, the format of
    diffs has changed.

bin/rsync-backup
* Now that shebangs and cron are straightened out, the call to profile
  which we needed to "fix" cron is no longer needed.

bin/running_under_cron
* Added a check for envvar CRON before we go traipsing through the
  process table.

diff --git a/bin/git-worktree b/bin/git-worktree
--- a/bin/git-worktree
+++ b/bin/git-worktree
@@ -1,10 +1,11 @@
-#!/usr/bin/env bash
+# -*- sh -*-
+# shellcheck shell=bash
+
+# git-worktree
 
 if [[ -z $GIT_DISPATCHER ]]; then
     git-dispatch-warning git-worktree
 fi
-
-# git-worktree
 
 ## Global used to control 'cd'ing around
 doandcdfile=''
@@ -610,6 +611,8 @@ $(ls -la)"
             delit=$(basename "${PWD}")
             builtin cd .. || { cmd-echo --ec -- "Cannot cd .."; false; return; }
             \rm -rf "$delit" || { cmd-echo --ec -- "Bad rm of ./$delit (from ${PWD}). Aborting."; false; return; }
+        else
+            builtin cd .. || { cmd-echo --ec -- "Cannot cd .."; false; return; }
         fi
     done
 
