Periodic
bin/git-branch
o Standardized extended metadata date format.

bin/git-clone
o Standardized extended metadata date format.
o extMeta tag => em

_git-clone-set-triangle():
  o Added here because external git-set-triangle was only used in
    git-clone.

bin/git-worktree
o Standardized extended metadata date format.
o Use REALGIT where possible to save a step.
o Removed unused sctag, refactored pwd check.

_git_worktree_record_created_date():
  o 'created' label changed to 'EMcreated' so we can tell which ones are
    extended metadata.

git-worktree-delete():
  o Added --keep-branch.

git-worktree-mark-merged():
  o Write enough extended metadata so that we could write an automated
    worktree whacker for merged worktrees.

bin/git.env
GIT_EXT_META_DATE_FMT():
  o Standardized extended metadata date format.

bin/grep_history
o Shellchecked. Moved epoch processing to the Perl script.

bin/logit
o Added --at to run the job on a queue.

bin/parse_bash_hist
o Fixed up some broken options, moved the epoch processing here from the
  grep_history bash script.

bin/pssearch
o Fixed implementation of --nothis to only exclude the pssearch entry and
  its kids. Option --exclude is renamed --expid and allows multiple
  entries just like --pid and just like it was documented. --time and
  --rtime sort by parent elapsed time of process trees descending and
  ascending (like ls does). Added --original for next time I need to
  compare with unadorned ps command.

functions/color-echo
o Convenience function for echo -e with ansi sequences.

diff --git a/bin/git-worktree b/bin/git-worktree
--- a/bin/git-worktree
+++ b/bin/git-worktree
@@ -30,9 +30,27 @@ usage ()
     ) 2>&1 | ${PAGER:-less}
 }
 
+_git_worktree_record_check_pwd ()
+{
+    ## Make sure pwd ends in wt
+    if [[ ! "$(pwd)" =~ /wt$ ]]
+    then
+        if [ -d ./wt ]
+        then
+            builtin cd ./wt || ( cmd-echo -- "Cannot cd ./wt" && return 1)
+        else
+            cmd-echo -- "Current directory is $(pwd)." \
+                      'No wt subdir.' \
+                      'Will not manipulate worktrees outside of wt dir. Aborting.'
+            return 1
+        fi
+    fi
+    return 0
+}
+
 _git_worktree_record_created_date ()
 {
-    git config --replace-all "worktree.$1.created" "$(date '+%Y-%m-%d %H:%M:%S %z')" || exit $?
+    git config --replace-all "worktree.$1.EMcreated" "$(date "$GIT_EXT_META_DATE_FMT")" || exit $?
 }
 
 # shellcheck disable=SC2120
@@ -46,7 +64,6 @@ git-worktree-ina ()
 
 git-worktree-create ()
 {
-    local sctag='' ## "create: "
     local fetch_existing=0
     local status=0
     local opt_m=''
@@ -93,19 +110,7 @@ git-worktree-create ()
         esac
     done
 
-    ## Make sure pwd ends in wt
-    if [[ ! "$(pwd)" =~ /wt$ ]]
-    then
-        if [ -d ./wt ]
-        then
-            builtin cd ./wt || ( cmd-echo -- "Cannot cd ./wt" && return 1)
-        else
-            cmd-echo -- "${sctag}Current directory is $(pwd)." \
-                      'No wt subdir.' \
-                      'Will not manipulate worktrees outside of wt dir. Aborting.'
-            return 1
-        fi
-    fi
+    ! _git_worktree_record_check_pwd && return 1
     local wtroot
     wtroot="$(pwd)"
 
@@ -149,11 +154,11 @@ git-worktree-create ()
           )
     if [ ! "$exists" = '(fetch)(push)' ]
     then
-        cmd-echo -- "${sctag}Can't find remote '$remote' for fetch and push"
+        cmd-echo -- "Can't find remote '$remote' for fetch and push"
         git remote -v | while read -r line; do cmd-echo -- -c -- "$line"; done
         return 1
     fi
-    cmd-echo -- "${sctag}Using '$remote' as remote."
+    cmd-echo -- "Using '$remote' as remote."
 
     ## Check worktree dir
     ((verbose)) && cmd-echo -- "Check for existing worktrees with same name."
@@ -188,17 +193,17 @@ git-worktree-create ()
     then
         if ((fetch_existing==1)) && [ -n "$exists" ]
         then
-            cmd-echo -- "${sctag}Branch $localbranchname already exists locally. Using it."
-            if git worktree add "$localbranchname" "$localbranchname"
+            cmd-echo -- "Branch $localbranchname already exists locally. Using it."
+            if $REALGIT worktree add "$localbranchname" "$localbranchname"
             then
-                ((verbose)) && cmd-echo -- "${sctag}cd ${wtsubdir}"
+                ((verbose)) && cmd-echo -- "cd ${wtsubdir}"
                 ## dirlist, not builtin cd, to take advantage this cd enhancement
                 dirlist "$localbranchname"
             else
                 return $?
             fi
         else
-            cmd-echo -- "${sctag}Branch $localbranchname already exists locally. Cannot create it."
+            cmd-echo -- "Branch $localbranchname already exists locally. Cannot create it."
             return 1
         fi
     else
@@ -235,25 +240,25 @@ git-worktree-create ()
         then
             ## Fetch it, Dear Henry...
             ##                          branch             path
-            git worktree add --track -b "$localbranchname" "$localbranchname" "$exists"
+            $REALGIT worktree add --track -b "$localbranchname" "$localbranchname" "$exists"
             status=$?
             if ((status))
             then
-                cmd-echo -- "${sctag}Aborting."
+                cmd-echo -- "Aborting."
                 return 1
             fi
-            ((verbose)) && cmd-echo -- "${sctag}cd ${wtsubdir}"
+            ((verbose)) && cmd-echo -- "cd ${wtsubdir}"
 
             ## dirlist, not builtin cd, to take advantage this cd enhancement
             dirlist "$localbranchname"
             _git_worktree_record_created_date "$localbranchname"
         elif ((fetch_existing==1)) && [ -z "$exists" ]
         then
-            cmd-echo -- "${sctag}Cannot find '$remote/${wtname}' to fetch"
+            cmd-echo -- "Cannot find '$remote/${wtname}' to fetch"
             return 1
         elif ((fetch_existing==0)) && [ -n "$exists" ]
         then
-            cmd-echo -- "${sctag}Branch '${wtname}' already exists in remote '$remote'"
+            cmd-echo -- "Branch '${wtname}' already exists in remote '$remote'"
             return 1
         else ## ((fetch_existing==0)) && [ -z "$exists" ]
             ## Since this worktree is going to create a branch of the local
@@ -261,10 +266,10 @@ git-worktree-create ()
             ## now) it is up to date.
             if [ "$(git branch get-current)" != "$asmaster" ]
             then
-                cmd-echo -- "${sctag}Cannot create branch and worktree because the current branch '$(git branch get-current)' is not the master branch '$asmaster'."
+                cmd-echo -- "Cannot create branch and worktree because the current branch '$(git branch get-current)' is not the master branch '$asmaster'."
                 return 1
             fi
-            cmd-echo -- "${sctag}Checking local '$asmaster', starting point for branch."
+            cmd-echo -- "Checking local '$asmaster', starting point for branch."
             git pull
             status=$?
             ## We can return here with no other notice, assuming the error message
@@ -280,24 +285,24 @@ git-worktree-create ()
             #### git push origin master
 
             ## Now create the worktree and the branch.
-            ((verbose)) && cmd-echo -- "${sctag}git worktree add -b ${wtsubdir} ${wtbranch}"
-            git worktree add $create_branch "${wtsubdir}" "${wtbranch}"
+            ((verbose)) && cmd-echo -- "$REALGIT worktree add -b ${wtsubdir} ${wtbranch}"
+            $REALGIT worktree add $create_branch "${wtsubdir}" "${wtbranch}"
             status=$?
             if ((status))
             then
-                cmd-echo -- "${sctag}Aborting."
+                cmd-echo -- "Aborting."
                 return 1
             fi
 
-            ((verbose)) && cmd-echo -- "${sctag}cd ${wtsubdir}"
+            ((verbose)) && cmd-echo -- "cd ${wtsubdir}"
             ## dirlist, not builtin cd, to take advantage this cd enhancement
             dirlist "${wtsubdir}"
             _git_worktree_record_created_date "${wtbranch}"
 
             ## Finally push the branch upstream as a tracking branch
-            ((verbose)) && cmd-echo -- "${sctag}git push --set-upstream $remote ${wtbranch}"
+            ((verbose)) && cmd-echo -- "git push --set-upstream $remote ${wtbranch}"
             git push --set-upstream "$remote" "${wtbranch}"
-            git branch info created "$(date +%Y%m%d.%H%M%S%z)"
+            git branch info created "$(date "$GIT_EXT_META_DATE_FMT")"
         fi
     fi
     ## Convert the worktree's .git file to use a relative path to the master
@@ -316,24 +321,24 @@ git-worktree-create ()
     ## Add this repo to the list
     if ((opt_reset))
     then
-        cmd-echo -- "${sctag}Resetting git list..."
+        cmd-echo -- "Resetting git list..."
         git-go-set
     else
         cmd-echo -- "--skip-reset. Run 'git-go-set' at some point."
     fi
 
-    cmd-echo -- "${sctag}Done. Execute" "    gitgo $repo/wt/${wtsubdir}" "to use."
+    cmd-echo -- "Done. Execute" "    gitgo $repo/wt/${wtsubdir}" "to use."
 
     return 0
 }
 
 git-worktree-delete ()
 {
-    local sctag='' #"delete:"
     local opt_yes=0
     local opt_yes_string
     local opt_force=0
     local opt_reset=1
+    local opt_keep_branch=0
     OPTSARGS=$(getoptp -o yfs:h --long yes,force,help,no-reset,skip-reset -n "${FUNCNAME[0]}" -- "$@")
     local status=$?
     ((status != 0)) && usage && return $status
@@ -346,24 +351,19 @@ git-worktree-delete ()
             -y|--yes) opt_yes=1; opt_yes_string='--yes'; shift ;;
             -f|--force) opt_force=1; shift ;;
             -h|--help) usage; return 0 ;;
+            -k|--keep-branch) opt_keep_branch=1 ;;
             --) shift; break ;; ## end of opts, remaining $*, if any, are args
             *) usage "Internal error!"; return 1 ;;
         esac
     done
 
-    ## Make sure pwd ends in wt
-    if [[ ! "$(pwd)" =~ /wt$ ]]
+    if ((opt_force + opt_yes + opt_keep_branch > 1 ))
     then
-        if [ -d ./wt ]
-        then
-            builtin cd ./wt || ( cmd-echo -- "Cannot cd ./wt" && return 1)
-        else
-            cmd-echo -- "${sctag}Current directory is $(pwd)." \
-                      'No wt subdir.' \
-                      'Will not manipulate worktrees outside of wt dir. Aborting.'
-            return 1
-        fi
+        cmd-echo -- "--force, --keep-branch and --yes are mutex options"
+        return 1
     fi
+
+    ! _git_worktree_record_check_pwd && return 1
     local wtroot
     wtroot="$(pwd)"
 
@@ -371,12 +371,12 @@ git-worktree-delete ()
 
     if [ -z "$wtname" ]
     then
-        cmd-echo -- "${sctag}Worktree not specified"
+        cmd-echo -- "Worktree not specified"
         return 1
     fi
     if [ ! -d "$wtname" ]
     then
-        cmd-echo -- "${sctag}Cannot find worktree $wtname
+        cmd-echo -- "Cannot find worktree $wtname
 $(ls -la)"
         return 1
     fi
@@ -400,7 +400,7 @@ $(ls -la)"
         then
             git status
             echo
-            cmd-echo -- "${sctag}Will not delete current worktree. Clean worktree or re-run command with --force."
+            cmd-echo -- "Will not delete current worktree. Clean worktree or re-run command with --force."
             return 1
         fi
     fi
@@ -414,7 +414,7 @@ $(ls -la)"
     current_dir=$(basename "$(pwd)")
     if [ "$current_branch" != "$current_dir" ]
     then
-        cmd-echo -- "${sctag}Branch name '$current_branch' does not match current subdir name '$current_dir'." \
+        cmd-echo -- "Branch name '$current_branch' does not match current subdir name '$current_dir'." \
                     "I'm bailing; you fix this mess."
         return 1
     fi
@@ -422,7 +422,7 @@ $(ls -la)"
     local rc=$?
     if ((rc))
     then
-        cmd-echo -- "${sctag}git status returned non-success value $rc." \
+        cmd-echo -- "git status returned non-success value $rc." \
                     "I'm bailing; you fix this mess."
         return 1
     fi
@@ -433,7 +433,7 @@ $(ls -la)"
     builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
     if ! rm -rf "$delit"
     then
-        cmd-echo -- "${sctag}Bad rm of ./$delit (from $(pwd)). Aborting."
+        cmd-echo -- "Bad rm of ./$delit (from $(pwd)). Aborting."
         return 1;
     fi
 
@@ -446,26 +446,29 @@ $(ls -la)"
             #it's empty
             delit=$(basename "$(pwd)")
             builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
-            \rm -rf "$delit" || cmd-echo -- "${sctag}Bad rm of ./$delit (from $(pwd)). Aborting." && return 1;
+            \rm -rf "$delit" || cmd-echo -- "Bad rm of ./$delit (from $(pwd)). Aborting." && return 1;
         fi
     done
 
     cmd-echo -- "Local repo deleted."
 
     ## Now fix the administrative files.
-    git worktree prune
+    $REALGIT worktree prune
     cmd-echo -- "Local admin files updated."
 
     ## Now the take care of the branch.
     if ((opt_yes))
     then
         resp='y'
+    elif ((opt_keep_branch))
+    then
+        resp='n'
     else
         resp=$(cmd-yesno "Delete associated branch $current_branch" 'n')
     fi
     if [ "$resp" = 'n' ]
     then
-        cmd-echo -- "${sctag}If you change your mind: git-branch delete $current_branch"
+        cmd-echo -- "If you change your mind: git-branch delete $current_branch"
     else
         ## Have to be in the git repo that the basis for the worktree.
         while [ "$(basename "$(pwd)")" != 'wt' ]
@@ -481,13 +484,13 @@ $(ls -la)"
 
     if ((opt_reset))
     then
-        cmd-echo -- "${sctag}Resetting git list..."
+        cmd-echo -- "Resetting git list..."
         git-go-set
     else
         cmd-echo -- "--skip-reset. Run 'git-go-set' at some point."
     fi
 
-    cmd-echo -- "${sctag}Done."
+    cmd-echo -- "Done."
 
     return 0
 }
@@ -532,30 +535,16 @@ git-worktree-rename ()
         return 1
     fi
 
-    local sctag='' #"rename: "
     local status
 
-    ## Make sure pwd ends in wt
-    if [[ ! "$(pwd)" =~ /wt$ ]]
-    then
-        if [ -d ./wt ]
-        then
-            builtin cd ./wt || ( cmd-echo -- "Cannot cd ./wt" && return 1)
-            wtdir="$(pwd)"
-        else
-            cmd-echo -- "${sctag}Current directory is $(pwd)." \
-                      'No wt subdir.' \
-                      'Will not manipulate worktrees outside of wt dir. Aborting.'
-            return 1
-        fi
-    fi
+    ! _git_worktree_record_check_pwd && return 1
     local wtroot
     wtroot="$(pwd)"
 
     local old_wtname="$1" ; shift
     if [ ! -d "$old_wtname" ]
     then
-        cmd-echo -- "${sctag}Cannot find worktree $old_wtname
+        cmd-echo -- "Cannot find worktree $old_wtname
 $(ls -la)"
         return 1
     fi
@@ -564,7 +553,7 @@ $(ls -la)"
     local new_wtname="$1" ; shift
     if [ -d "$new_wtname" ]
     then
-        cmd-echo -- "${sctag}Will not overwrite existing worktree $new_wtname
+        cmd-echo -- "Will not overwrite existing worktree $new_wtname
 $(ls -la)"
         return 1
     fi
@@ -575,7 +564,7 @@ $(ls -la)"
     cb="$(git branch get-current)"
     if [ "$cb" = "$old_wtname" ]
     then
-        cmd-echo -- "${sctag}Renaming the branch..."
+        cmd-echo -- "Renaming the branch..."
         git-branch rename "$old_wtname" "$new_wtname"
         status=$?
         if ((status != OK))
@@ -584,7 +573,7 @@ $(ls -la)"
         fi
     fi
 
-    cmd-echo -- "${sctag}Updating metadata..."
+    cmd-echo -- "Updating metadata..."
     ## Get the metadata directory for this worktree
     local metadatadir
     metadatadir="$(grep -E '^gitdir:' .git | sed 's/.* //')"
@@ -604,7 +593,7 @@ $(ls -la)"
     newmetadatadir="$(dirname "$metadatadir")/$new_wtname"
     mv "$metadatadir" "$newmetadatadir" || return 1
 
-    cmd-echo -- "${sctag}Moving the local files..."
+    cmd-echo -- "Moving the local files..."
     ## Move us
     builtin cd .. || ( cmd-echo -- "Cannot cd .." && return 1)
     mv "$old_wtpath" "$new_wtpath" || return 1
@@ -612,13 +601,13 @@ $(ls -la)"
     ## Register the rename
     if ((opt_reset))
     then
-        cmd-echo -- "${sctag}Resetting git list..."
+        cmd-echo -- "Resetting git list..."
         git-go-set
     else
         cmd-echo -- "--skip-reset. Run 'git-go-set' at some point."
     fi
 
-    cmd-echo -- "${sctag}Done."
+    cmd-echo -- "Done."
 
     return $?
 }
@@ -626,7 +615,7 @@ $(ls -la)"
 git-worktree-diff-to-root ()
 {
     # shellcheck disable=SC2119
-    if git-worktree-ina
+    if ! git-worktree-ina
     then
         cmd-echo -- "Must be in a wt"
         return 1;
@@ -696,7 +685,7 @@ git-worktree-get-root ()
     local i
     local status=0
     local wtr
-    wtr=$(git worktree list | \
+    wtr=$($REALGIT worktree list | \
               grep '\[master\]' | \
               sed 's/....... \[master\]//' | \
               sed 's/\s\{1,\}$//')
@@ -713,6 +702,35 @@ git-worktree-get-root ()
         echo
         return 1
     fi
+}
+
+git-worktree-mm ()
+{
+    git-worktree-mark-merged "$@"
+}
+
+git-worktree-mark-merged ()
+{
+    # shellcheck disable=SC2119
+    if ! git-worktree-ina
+    then
+        cmd-echo -- "Must be in a wt"
+        return 1;
+    fi
+
+    local wtname
+    wtname="$(basename "$(pwd)")"
+
+    local branchname
+    branchname="$(git branch get-current)"
+
+    local markdate
+    markdate="$(date "$GIT_EXT_META_DATE_FMT")"
+
+    git config --replace-all "worktree.$wtname.em-markedmerged" "$markdate" || exit $?
+    git config --replace-all "branch.$branchname.em-markedmerged" "$markdate" || exit $?
+
+    cmd-echo "Worktree $wtname, branch $branchname marked merged at $markdate"
 }
 
 main ()
@@ -762,6 +780,7 @@ git-worktree - git extention of git worktree
  git-worktree diff-from-root
  git-worktree diff-to-root
  git-worktree ina
+ git-worktree mark-merged|mm
 
 =head1 DESCRIPTION
 
@@ -870,6 +889,12 @@ set of files or all the git-known files in the current worktree. A synonymn for
 
 Is the current working directory in a worktree? Adding the -p option will print
 the worktree root.
+
+=item mark-merged
+
+Write configs 'worktree.<worktreename>.em-markmerged' and
+'branch.<branchname>.em-markmerged' as the current date and time. Use this if
+the worktree has been merged and can be deleted by some periodic sweep process.
 
 =back
 
