Periodic
bin/bash-usage
* New binc inclusion method.

bin/git-branch
* We do not need $REALGIT_EXEC_PATH/git-sh-setup.

bin/git-clone
* New binc inclusion method.
* Covert to git-usage.

main():
  * Added ext. to my config extensions.

bin/git-commit
* Added storing the PR to the repo metadata after pr creation.

bin/git-go-set
* Put regex to search in git config --get-regexp next to the option.

bin/git-hook
* envars moved here from git.env, converted to local consts.

bin/git-rebase
* Swap exec path with git call.

bin/git-repo
git-repo-current-branch():
  * Make sure the warnings and errors go to STDERR.

git-repo-pr-get():
  * Update the pr search to account for pull requests that were rebranch
    named as 'pull-N'.

git-repo-pr-store():
  * New. Need to store right after we create to prevent long-winded lookups
    on subsequent accesses.

bin/git-what
* We do not need $REALGIT_EXEC_PATH/git-sh-setup.

bin/git.env
* Added ext. to my extensions.
* Hook envars moved to git-hook.
* Shellcheckisms.
* Remove init of unused merge audit file.

bin/github-api
* Parse status from header fields when there is no Status: field. We have
  to get out of this shell script into the Perl version.

bin/mktemp.binc
* Added true return for "use".

bin/newx
* Use the separate name and size envvars for XTERMFONT*.

bin/on_exit.binc
* Added true return for "use".

bin/util.env
use():
  * Added this function to mimic perl and read in 'binc' files.

dotfiles/gitconfig
* Generalize excludesFile.
* oldest ancestor aliases added. excludesFile replaces home dir bash-ish
  envvar replacement with ~ so that it works again.

dotfiles/gitconfig_personal
* Added ext. to my extensions.

dotfiles/gitignore
* Fix wildcards to match in any directory.

dotfiles/xterminit
* Split XTERMFONTS into separate name and size envvars.
* Handle funky laptop->second display resolution diffs when calculating a
  spawn point in the x axis.

functions/git
git():
  * Make git --help X work like git X --help and not bypass our command X
    if it exists.
  * Added extended help.

diff --git a/bin/git-repo b/bin/git-repo
--- a/bin/git-repo
+++ b/bin/git-repo
@@ -637,13 +637,17 @@ git-repo-pr-get ()
         github-api --stream-data --perl-data --server "$remote_svc" pulls "$remote_repo" >> "$perldata"
         pr_url=$(perl -d:ptkdb -MData::Dumper -e '
 ## $ARGV[0] - file with perl data
-## $ARGV[1] - org or current repo
+## $ARGV[1] - org
 ## $ARGV[2] - current branch name
 ## $ARGV[3] - "state" - 0:do not add the state of the PR to the output, 1:add the state
 ## $ARGV[4] - match PRs with this state
 do $ARGV[0];
 for $openpull (@{$VAR1}) {
-    if ($openpull->{head}{label} eq "$ARGV[1]:$ARGV[2]") {
+    my($pull_org, $pull_label) = split(/:/,$openpull->{head}{label});
+    if ($pull_org eq $ARGV[1]
+        and ( $ARGV[2] eq $pull_label
+              or
+              $ARGV[2] =~ m/pull-$openpull->{number}/) ) {
         next if $ARGV[4] and lc($openpull->{state}) ne $ARGV[4];
         ## debug: print Data::Dumper->Dump([$openpull],[qw(*pull)]);
         if($ARGV[3]) {
@@ -662,8 +666,8 @@ exit 1;' "$perldata" "$USER" "$cb" "$opt_show_state" "$opt_match_state")
         else
             ((opt_show_state)) && pr_url=${pr_url#*: }
             # Cache the PR
-            [[ -n $wt ]] && git config --replace-all "worktree.${wt}.extmeta-pr" "$pr_url"
-            [[ -n $cb ]] && git config --replace-all "branch.${cb}.extmeta-pr" "$pr_url"
+            git-repo-pr-store "$pr_url"
+
         fi
     fi
 
@@ -691,6 +695,15 @@ exit 1;' "$perldata" "$USER" "$cb" "$opt_show_state" "$opt_match_state")
         echo "$pr_url"
     fi
     true; return $?
+}
+
+git-repo-pr-store ()
+{
+    declare pr_url=$1
+    declare wt=$(git-worktree ina -v)
+    declare cb=$(git-repo-current-branch)
+    [[ -n $wt ]] && git config --replace-all "worktree.${wt}.extmeta-pr" "$pr_url"
+    [[ -n $cb ]] && git config --replace-all "branch.${cb}.extmeta-pr" "$pr_url"
 }
 
 git-repo-pr ()
@@ -907,7 +920,7 @@ git-repo-current-branch ()
 {
     if [[ -n $1 ]]
     then
-        cmd-echo --ec -- "Cannot set current branch yet"
+        cmd-echo --ec -- "Cannot set current branch yet" >&2
         false;return $?
     else
         declare cb
@@ -918,7 +931,7 @@ git-repo-current-branch ()
             cb=$($REALGIT branch --color=never --contains HEAD | grep '(no branch, rebasing' | sed 's/.* \(.*\))/\1/')
             if [[ -z $cb ]]
             then
-                cmd-echo --ec -- "Cannot get current branch"
+                cmd-echo --ec -- "Cannot get current branch" >&2
                 false;return $?
             fi
         fi
