rm is a command, not a builtin

diff --git a/bin/git-repo b/bin/git-repo
--- a/bin/git-repo
+++ b/bin/git-repo
@@ -215,7 +215,7 @@ git-repo-delete ()
         fi
 
         builtin cd .. || { cmd-echo --id git-repo "Cannot cd .."; false; return; }
-        builtin rm -rf "$repo" || return ## If the rm fails, we should see error
+        command rm -rf "$repo" || return ## If the rm fails, we should see error
         ## messages, no need to add more.
 
         cmd-echo --id git-repo "Done. Not touching remote repo. Resetting git list..."
@@ -242,7 +242,7 @@ git-repo-delete ()
 
     ## Feed "there" back to the git function to make it stick.
     if [[ -n "$doandcdfile" ]]; then
-        echo "ecd ${PWD}" > "$doandcdfile"
+        echo "dirlist ${PWD}" > "$doandcdfile"
         cmd-echo --id git-repo -n -- "Done. "
     fi
 
