func to exec, convert phase

diff --git a/bin/git-log-shas-range b/bin/git-log-shas-range
--- a/bin/git-log-shas-range
+++ b/bin/git-log-shas-range
@@ -1,39 +1,98 @@
 #!/usr/bin/env bash
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-log-shas-range
 
-git-log-shas-range ()
-{
-    ##@@ 0001||group||git-log-shas||Given two shas (older newer), call git log on the range, inclusively
 
-    local opt_hf=''
-    local opt_inclusive=1
-    local opt_add_names=''
-    local OPTSARGS
-    OPTSARGS=$(getoptp -o f:ienh --long highlightfirst:,inclusive,exclusive,name-only,help -n "${FUNCNAME[0]}" -- "$@")
-    local status=$?
-    ((status != 0)) && func-usage && return $status
+declare opt_hf
+opt_hf=''
+declare opt_inclusive
+opt_inclusive=1
+declare opt_add_names
+opt_add_names=''
+declare OPTSARGS
+OPTSARGS=$(getoptp -o f:ienh --long highlightfirst:,inclusive,exclusive,name-only,help -n "${FUNCNAME[0]}" -- "$@")
+declare status
+status=$?
+((status != 0)) && script-usage && exit $status
 
-    eval set -- "$OPTSARGS"
-    while true
-    do
-        case "$1" in
-            -f|--higlightfirst)  opt_inclusive=1; opt_hf="$2"; shift; shift ;;
-            -i|--inclusive) opt_inclusive=1; shift ;;
-            -e|--exclusive) opt_inclusive=0; shift ;;
-            -n|--name-only) opt_add_names='--name-only'; shift ;;
-            -h|--help) func-usage; return 0 ;;
-            --) shift; break ;; ## end of opts, remaining $*, if any, are args
-            *) echo "Internal error!"; func-usage; return 1 ;;
-        esac
-    done
+eval set -- "$OPTSARGS"
+while true
+do
+    case "$1" in
+        -f|--higlightfirst)  opt_inclusive=1; opt_hf="$2"; shift; shift ;;
+        -i|--inclusive) opt_inclusive=1; shift ;;
+        -e|--exclusive) opt_inclusive=0; shift ;;
+        -n|--name-only) opt_add_names='--name-only'; shift ;;
+        -h|--help) script-usage; exit 0 ;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; script-usage; exit 1 ;;
+    esac
+done
 
-    [ -z "$2" ] && echo "Usage: git-log-sha-range oldersha newersha" && return 1;
-    git --no-pager log $opt_add_names "${1}..${2}" ## Does not print the first one
-    if((opt_inclusive))
-    then
-        [ ! "$1" = "$2" ] && echo "$opt_hf"
-        git --no-pager log $opt_add_names -1 "${1}"    ## Always prints the first one
-    fi
-}
+[ -z "$2" ] && echo "Usage: git-log-sha-range oldersha newersha" && exit 1;
+git --no-pager log $opt_add_names "${1}..${2}" ## Does not print the first one
+if((opt_inclusive))
+then
+    [ ! "$1" = "$2" ] && echo "$opt_hf"
+    git --no-pager log $opt_add_names -1 "${1}"    ## Always prints the first one
+fi
+## POD guard
+exit 0
+
+## You can add sections with =head1, but stick to =item for section breakdowns,
+## not =head2/3/etc/.
+
+:<<'__PODUSAGE__'
+=head1 NAME
+
+git-log-shas-range - script that does something
+
+=head1 SYNOPSIS
+
+ git-log-shas-range [--option1] [ --option2 optionarg ] arg1 [arg2 ...] 
+     [fee] [dfsdfs] [sfsdfsf]
+
+=head1 DESCRIPTION
+
+Describe in general terms what git-log-shas-range does.
+
+=head1 ARGUMENTS
+
+=over 4
+
+=item arg
+
+Describe what arg does, should be, etc. Add a new =item for each distinct arg.
+
+=back
+
+=head1 OPTIONS
+
+=over 4
+
+=item --option1
+
+Describe what --option1 does.
+
+=item --option2
+
+Describe what --option2 does. Describe what optionarg does.
+
+=over 2
+
+=item *
+
+A choice for optionarg
+
+=item *
+
+Another choice for optionarg
+
+=back
+
+=back
+
+=cut
+
+__PODUSAGE__
+
diff --git a/bin/git-to-stdout b/bin/git-to-stdout
--- a/bin/git-to-stdout
+++ b/bin/git-to-stdout
@@ -1,58 +1,58 @@
 #!/usr/bin/env bash
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-to-stdout
 
-git-to-stdout ()
-{
-    declare moreopts=1
-    declare file=0
+declare moreopts
+moreopts=1
+declare file
+file=0
 
-    while [[ "$1" =~ ^- ]] && ((moreopts))
-    do
-        declare original="$1"
-        declare option
-        option=$(dashstripper "$original")
-        shift
-        case $option in
-            ## standard options
-            h | help )
-                func-usage
-                return 0
-                ;;
-            f | file)
-                file=1;;
-            --)
-                moreopts=0
-                ;;
-            * )
-                cmd-echo -- "$original is an invalid option. See $0 --help";
-                return 1
-                ;;
-        esac
-    done
+while [[ "$1" =~ ^- ]] && ((moreopts))
+do
+    declare original
+    original="$1"
+    declare option
+    option=$(dashstripper "$original")
+    shift
+    case $option in
+        ## standard options
+        h | help )
+            script-usage
+            exit 0
+            ;;
+        f | file)
+            file=1;;
+        --)
+            moreopts=0
+            ;;
+        * )
+            cmd-echo -- "$original is an invalid option. See $0 --help";
+            exit 1
+            ;;
+    esac
+done
 
-    if (($# < 2 ))
+if (($# < 2 ))
+then
+    script-usage
+    exit 1
+fi
+
+declare uuid
+uuid=$1;shift
+for i in "$@"
+do
+    if ((file))
     then
-        func-usage
-        return 1
+        echo "${i}.${uuid}"
+        git show "${uuid}:${i}" > "$(git root)/${i}.${uuid}"
+    else
+        git show "${uuid}:${i}"
     fi
-
-    local uuid=$1;shift
-    for i in "$@"
-    do
-        if ((file))
-        then
-            echo "${i}.${uuid}"
-            git show "${uuid}:${i}" > "$(git root)/${i}.${uuid}"
-        else
-            git show "${uuid}:${i}"
-        fi
-    done
-}
+done
 
 ## The End, to make sure we never eval the usage statement
-return 0
+exit 0
 
 ## You can add sections with =head1, but stick to =item for section breakdowns,
 ## not =head2/3/etc/. If you want just plain text, get rid of pod tags and the
