Periodic
bin/apply-compile-check-everywhere
* No more assumed libs paths, which were inherited from Bloomberg DPKG
  development; they evaluated to the location of this file, which is
  wrong when used as a utility. Provide --libs or -I args to accomplish
  the same intention.

bin/bash-usage
* Docs.

bin/cleantemp.cron
* Fixed improper auto-edit when we converted to single line "; then"
  format.

bin/git-add-remote
* Removed auditing.
* Convert from bash-usage to git-usage.
* Convert from USAGE to PODUSAGE.

bin/git-check-with-remote
* Removed auditing.
* Convert from bash-usage to git-usage.

bin/git-comment
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-commit-with-source-ctrl-log-guts
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-edit
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-find
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-go
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-go-get
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.

bin/git-go-set
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-hold
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-hook
* No need for --noreal flag anymore. Removed local usage function.
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.

bin/git-kv
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-log-shas-range
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-mono
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-ping
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-process-source-ctrl-log
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-repo
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-status-with-source-ctrl-log
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-sync-with-remote
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-to-stdout
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-track
* No need for --noreal flag anymore.

bin/git-usage
* Compare our command to git to see if we need to run a real git man
  after our command's usage.

bin/git-utils
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-what
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/git-worktree
* More clearly labeled delete actions.
* Fixed some hardcoded exit/return values.

git-worktree-create():
  * Extend user-named branches to any clone.

bin/git.env
REALGIT_VERIFIED_VERSION_STRING():
  * Update to 2.30.2

bin/github-api
* Fixed some hardcoded exit/return values.
* Convert from bash-usage to git-usage.
* Removed auditing.

bin/logit
* Specify which pid to look up when calling xterm-cli.

bin/pause
* Take the whole line as prompt, not just $1.

bin/xterm-cli
* Specify which pid to look up.

dotfiles/gitconfig
* Added is-a-command to check list-cmds=main.

functions/git-get-default-remote
* Convert from bash-usage to git-usage.

functions/use
* Allow .env files to be 'use'd.

diff --git a/bin/git-go b/bin/git-go
--- a/bin/git-go
+++ b/bin/git-go
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-echo "$(date): ${0##*/}" >> "${TILDAE:-$HOME}/.gitaudit"
-
 # git-go
 
 use mktemp
@@ -84,7 +82,7 @@ while true; do
                   # shellcheck disable=SC2154
                   if [[ -z $tmp ]]; then
                       cmd-echo -ec -- "No upstream for current repo (${PWD})"
-                      exit 1
+                      false; exit
                   fi
                   tgts=("${tmp/*:/}")
                   ;;
@@ -111,21 +109,21 @@ while true; do
         limited ) limited=('--limited' "$1"); shift ;;
         doandcd ) doandcdfile=$1; shift;;
         set ) cmd-echo -- Working...
-              git-go-set; exit 0;;
+              git-go-set; true; exit;;
         prune ) cmd-echo -- Working...
-              git-go-prune; exit 0;;
-        h | help ) bash-usage "$0"; exit 0 ;;
+              git-go-prune; true; exit;;
+        h | help ) git-usage "$0"; true; exit ;;
         --) break ;; ## VITAL!!! Exits the while loop, no more options,
                      ## remaining $*, if any, are args
         *)
             cmd-echo -ec -- "$option is an invalid option. See $0 --help"
-            exit 1
+            false; exit
             ;;
     esac
 done
 if ((opt_stat!=2)) && ((opt_brief)); then
     cmd-echo -ec -- "Cannot specify --brief without --dirty"
-    bash-usage "$0"; exit 1
+    git-usage "$0"; false; exit
 fi
 
 ## These settings are here and not in the case above where they are set because
@@ -175,13 +173,13 @@ if ((${#REPOS[@]}==0)); then
         ajoin allfilts -s ',' "${origtgts[@]}"
         cmd-echo -ec -- "Filters '$allfilts' do not match any repo"
     fi
-    exit 1
+    false; exit
 else
     if ((opt_mod)); then
         for r in "${REPOS[@]}"; do
             (
-                # The exit 1; will exit from the subshell, skipping the git status call
-                cd "${TILDAE:-$HOME}/$r" || { echo "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
+                # The false; exit; will exit from the subshell, skipping the git status call
+                cd "${TILDAE:-$HOME}/$r" || { echo "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
                 if (( $(git status --porcelain | wc  -l) )); then
                     echo
                     cmd-echo -- "$r"
@@ -212,13 +210,13 @@ else
                 if ((opt_stat==1)); then
                     echo "$rexp"
                     (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
                         git status --porcelain
                     )
                     echo
                 elif ((opt_stat==2)); then
                     (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
                         if (( $(git status --porcelain | wc -l) )); then
                             echo "$rexp"
                             if ((opt_brief==0)); then
@@ -229,7 +227,7 @@ else
                     )
                 elif ((opt_comments)); then
                     (
-                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r" && exit 1; }
+                        cd "${TILDAE:-$HOME}/$r" || { cmd-echo -ec -- "Cannot cd ${TILDAE:-$HOME}/$r"; false; exit; }
                         declare output
                         output="$(git comment --show --hi)"
                         # shellcheck disable=SC2030 #https://github.com/koalaman/shellcheck/wiki/SC2030
