func to exec, convert phase

diff --git a/bin/git-track-remote-branch b/bin/git-track-remote-branch
--- a/bin/git-track-remote-branch
+++ b/bin/git-track-remote-branch
@@ -1,21 +1,17 @@
 # -*- sh -*-
 
-# <Function Class: git>
-# <Function Justification: none>
+# git-track-remote-branch
 
-git-track-remote-branch ()
-{
-    ##@@ 0001||group||git-track-remote-branch||
+##@@ 0001||group||git-track-remote-branch||
 
-    local remote=$1
-    local branch=$2
-    if [ -z "$remote" ] || [ -z "$branch" ]
-    then
-        echo "Usage: git-track-remote-branch remote branch"
-        echo "       Missing one or both arguments"
-        return $NOT_OK
-    fi
-    git fetch $remote || return $?
-    git checkout -b $branch --track $remote/$branch
-    return $?
-}
+declare remote=$1
+declare branch=$2
+if [ -z "$remote" ] || [ -z "$branch" ]
+then
+    echo "Usage: git-track-remote-branch remote branch"
+    echo "       Missing one or both arguments"
+    exit $NOT_OK
+fi
+git fetch $remote || exit $?
+git checkout -b $branch --track $remote/$branch
+exit $?
