External sync. Run 'git diff 9d1eba8d8f44d7ce2d7d4e9397062e04a2faac7b' for details.

diff --git a/bin/git-diff-two-repos-on-disk b/bin/git-diff-two-repos-on-disk
--- a/bin/git-diff-two-repos-on-disk
+++ b/bin/git-diff-two-repos-on-disk
@@ -6,7 +6,7 @@
 
 OPTSARGS=$(getoptp -o h --long nocolor,help,exclude:,side-by-side,width: -n $FUNCNAME -- "$@")
 declare status=$?
-((status != 0)) && printf '%s\n' "$(sed '0,/^__USAGE__$/d' $0)" && exit $status
+((status != 0)) && script-usage && exit $status
 
 declare nocolor=0
 declare exclude=''
@@ -17,7 +17,7 @@ while true
 do
     case "$1" in
         -h|--help)
-            printf '%s\n' "$(sed '0,/^__USAGE__$/d' $0)"
+            script-usage
             exit $OK ;;
         --nocolor)
             nocolor=1 ; shift ;;
@@ -30,7 +30,7 @@ do
         --)
             shift; break ;; ## end of opts, remaining $*, if any, are args
         *)
-            echo "Internal error!"; printf '%s\n' "$(sed '0,/^__USAGE__$/d' $0)" ; exit $NOT_OK ;;
+            echo "Internal error!"; script-usage ; exit $NOT_OK ;;
     esac
 done
 
@@ -45,7 +45,7 @@ then
     repo[other]=$(realpath $1)
 else
     echo "Need at least one directory"
-    printf '%s\n' "$(sed '0,/^__USAGE__$/d' $0)" ; exit $NOT_OK ;
+    script-usage; exit $NOT_OK ;
 fi
 
 if [ ${repo[this]} = ${repo[other]} ]
diff --git a/bin/to-ext b/bin/to-ext
--- a/bin/to-ext
+++ b/bin/to-ext
@@ -6,7 +6,7 @@ source $BASH_INC_DIR/on_exit.binc
 
 declare moreopts=1
 declare opt_since=''
-declare opt_dirty=0
+declare opt_reset=0
 while [[ "$1" =~ ^- ]] && ((moreopts))
 do
     ## Strip all leading dashes here so that -foo and --foo can both
@@ -17,17 +17,17 @@ do
     shift
 
     case $option in
+        reset )
+            opt_reset=1
+            ;;
         since )
             opt_since=$1;  ## The last sha in the SOURCE repo that was
                            ## successfully shar'ed, shipped and integrated with
                            ## a particular target.
             shift
             ;;
-        dirty )
-            opt_dirty=1;
-            ;;
         help )
-            printf '%s\n' "$(sed '0,/^__USAGE__$/d' $0)"
+            script-usage
             exit 0
             ;;
         debug | x )
@@ -37,30 +37,48 @@ do
             moreopts=0
             ;;
         * )
-            echo "$original is an invalid option. See $0 --help";
+            echo "$original is an invalid option.";
+            script-usage
             exit 1
             ;;
     esac
 done
 
-git_sha_file="git-sha"
+## The shar file
+sharoutroot=$(git config --get ext.name)
+if [ -z "$sharoutroot" ]
+then
+    echo No shar root name specified.
+    echo Shall I run
+    declare cmd="git config --add ext.name $(basename $(pwd))"
+    resp=$(yesno "$cmd" n)
+    if [ "$resp" = 'n' ]
+    then
+        echo "Bailing. Run your own git config --add ext.name command,"
+        echo "then rerun this script."
+        exit 1
+    fi
+    ## else
+    $cmd
+    sharoutroot=$(git config --get ext.name)
+fi
 
 ## Check that we are clean. Otherwise the git-log-dump will not match with mods
-## on disk. We don't count any existing git-log-dump or git-rms as a problem.
-if (($(git st --porcelain 2>&1 | grep -E -v 'git-(log-dump|rms|links|sha)' 2>&1 | wc -l)))
+## on disk. We don't count any existing git-log-dump, git-rms or git-links
+## files as a problem since we are going to redo them anyway.
+if (($(git st --porcelain 2>&1 | \
+           grep -E -v 'git-(log-dump|rms|links)' 2>&1 | \
+           grep -E -v "${sharoutroot}.*shar.*" 2>&1 | \
+           wc -l)))
 then
     echo "Repo not clean:"
     git status
-    if ((opt_dirty))
-    then
-        echo "Continuing: --dirty specified. git-log-dump may not match code on disk."
-    else
-        echo "Stopping."
-        exit 1
-    fi
+    echo "If git-sha is modified, check it in immediately. Stopping."
+    exit 1
 fi
 
-if [ -z $opt_since ]
+declare git_sha_file="git-sha"
+if ((!opt_reset)) && [ -z $opt_since ]
 then
     if [ -f $git_sha_file ]
     then
@@ -73,17 +91,35 @@ fi
 ## perhaps to create a decent commit message on the other side.
 git log | head -1 > $git_sha_file
 git log > git-log-dump
-
+to_sha=$(cat $git_sha_file | sed 's/commit //')
 ## Non git members to add to the shar
 declare additionals="--text-files git-log-dump"
 
 ## The shar file
-sharout=personal-bb-$(date +%Y-%m-%d).shar
+sharoutroot=$(git config --get ext.name)
+if [ -z "$sharoutroot" ]
+then
+    echo No shar root name specified.
+    echo Shall I run
+    declare cmd="git config --add ext.name $(basename $(pwd))"
+    resp=$(yesno "$cmd" n)
+    if [ "$resp" = 'n' ]
+    then
+        echo "Bailing. Run your own git config --add ext.name command,"
+        echo "then rerun this script."
+        exit 1
+    fi
+    ## else
+    $cmd
+    sharoutroot=$(git config --get ext.name)
+fi
 
 if [ -z "$opt_since" ]
 then
     ## Without a sha to compare to, grab all files
     files=$(git ls-files)
+    opt_since=$(echo $to_sha | sed 's/./0/g')
+    rm -f git-rms
 else
     ## Check the files changed from sha time to now and segregate the removed
     ## ones for special processing.
@@ -98,6 +134,7 @@ else
             rms="$rms $i"
         fi
     done
+    rm -f git-rms
     if [ -n "$rms" ]
     then
         echo $rms > git-rms
@@ -126,18 +163,22 @@ done
 [ -s git-links ] && additionals="$additionals git-links"
 
 ## Make it.
+sharout="${sharoutroot}-${opt_since}-${to_sha}-$(date +%Y-%m-%d).shar"
 shar -q -m -o $sharout -p -M $files $additionals
-echo sharfile is $(ls ${sharout}*)
-
+echo
+echo Done. sharfile is "'$(ls ${sharout}*)'"
 echo "Don't forget to check in $git_sha_file"
 
 exit 0
 
 __USAGE__
 
-to-ext - Create a shar to copy files.
+to-ext - Create a shar to copy files
 
 Uses a sha passed via --since or from the file 'git-sha' to figure out what
-files have been added, changed or removed. Dumps the log to file
-'git-log-dump', puts removals in file 'git-rms', creates a shar of all the
-files.
+files have been added, changed or removed since the last time this command was
+run. Dumps the log to file 'git-log-dump', puts removals in file 'git-rms',
+creates a shar of all the files.
+
+Take shar over to the target repo (use a branch named 'incoming'). Run
+'from-ext' with the shar name. Commit changes. Sync to cloud.
