bin/gitfuncs git-pull():   o Add timestamping option. Closes #155.
git-pull-usage():
  o New.

diff --git a/bin/gitfuncs b/bin/gitfuncs
--- a/bin/gitfuncs
+++ b/bin/gitfuncs
@@ -2038,7 +2038,7 @@ git-clone ()
     then
         func-echo "Setting timestamps..."
         (cd $namespace/$repo; git-retimestamp)
-        echo Done
+        func-echo Done
     fi
     ## dirlist, not builtin cd, to take advantage this cd enhancement
     dirlist $namespace/$repo
@@ -3997,12 +3997,47 @@ git-diff-two-repos-on-disk ()
     fi
 }
 
+git-pull-usage ()
+{
+    cat <<EOUSAGE
+Usage: git-pull [-t]
+       git pull followed by a descriptinve git status.
+
+       -t resets the timestamps on the pulled files
+          to their original commit times
+EOUSAGE
+}
+
 git-pull ()
 {
-    ##@@ none||none||git-pull||Show log state after pull
+    ##@@ none||none||git-pull||Show log state after pull. -t to invoke timestamp fixer.
     gitfuncs_audit "$@"
+    local usage_func="${FUNCNAME}-usage"
+
+    local opt_t=0
+    OPTSARGS=$(getoptp -o th --long timestamp,help -n $FUNCNAME -- "$@")
+    local status=$?
+    ((status != 0)) && $usage_func ${FUNCNAME} && return $status
+
+    eval set -- "$OPTSARGS"
+    while true
+    do
+        case "$1" in
+            -t|--timestamp) opt_t=1; shift ;;
+            -h|--help) $usage_func; return $OK ;;
+            --) shift; break ;; ## end of opts, remaining $*, if any, are args
+            *) echo "Internal error!"; $usage_func ${FUNCNAME}; return $NOT_OK ;;
+        esac
+    done
+
     local oldsha=$(git-log-grab-sha -1)
     git pull
+    if ((opt_t))
+    then
+        func-echo "Setting timestamps..."
+        git-retimestamp
+        func-echo Done
+    fi
     git-log-shas-range -f "pre-pull:" $oldsha $(git-log-grab-sha -1)
 }
 
