Sync before VM rebuild. Details: bin/.gitignore: Added 1381bucket.log. bin/1381bucket.cron: New. Daily email to the 1381 watcher. bin/auditfuncs (auditfuncs_edit): Added safe_func_export here, early. bin/gitfuncs (git-check-with-remote): Get opt_bail_on_dirty variable spelling right. (git-checkout-last-existed): Updated to use git-find-last-existed. (git-find-last-existed): New. (git-process-changelog): Remove unused backup. (git-st-ext): Read or store an external status for the repo. (git-st-ext-all): Read all the repo external status files. (git-status-with-changelog): Silence the rm of the temp output. (git-stdout-last-existed): New. bin/sedinplace (status): Add --new to write updated to a new file. bin/utilfuncs: All functions updated to use safe_func_export. (safe_func_export): New. Allows func export if under bash. Otherwise no. Which still leaves the question of making scripts calling funcs work under other shells for another day. bin/vmfuncs (vmrebuild): New. Automate vm rebuild. dotfiles/profile.mpersico5: Call to builddebfuncs added.

diff --git a/bin/gitfuncs b/bin/gitfuncs
--- a/bin/gitfuncs
+++ b/bin/gitfuncs
@@ -205,7 +205,7 @@ git-status-with-changelog ()
     local out=$(mktemp)
     git-process-changelog --withstatus $diff $args 1>$out 2>&1
     less -R $out
-    rm -f $out
+    \rm -f $out
     return $?
 }
 alias git-st-cl='git-status-with-changelog '
@@ -343,6 +343,7 @@ git-process-changelog ()
             return $status
         fi
     fi
+    [ -f $changelogbkp ] && \rm -f $changelogbkp
 }
 
 git-cat-cl ()
@@ -544,14 +545,18 @@ git-go-usage ()
 {
     gitfuncs_audit "$@"
 
-    echo "Usage: git-go [--list] [--update|-u] [--roots|-r] [--mbig|-m] [--wt|--nowt ] [dirmatch]"
+    echo "Usage: git-go [--list[full]] [--update|-u] [--roots|-r] [--mbig|-m] [--wt|--nowt ] [dirmatch]"
     echo "       git-go [-h|--help]"
     echo
     echo "       Presents a list of all git repos"
     echo "       in ${HOME}/gits"
     echo "       for you to choose and then cd to."
     echo
-    echo "       --list will skip the choosing part and just exit"
+    echo "       --list will skip the choosing part and just exit, printing"
+    echo "           each repo dir with ~"
+    echo
+    echo "       --listfull will skip the choosing part and just exit, printing"
+    echo "           each repo dir with ~ expanded"
     echo
     echo "       --update will rescan to pick up new and deleted"
     echo "           repos and worktrees"
@@ -581,7 +586,7 @@ git-go ()
     local opt_mbig=0
     local opt_wt=1
     local opt_subwt_only=0
-    local OPTSARGS=$(getoptp -o lurmh --long list,update,roots,mbig,wt,nowt,subwt,help -n 'git-go' -- "$@")
+    local OPTSARGS=$(getoptp -o lurmh --long list,update,roots,mbig,wt,nowt,subwt,help,listfull -n 'git-go' -- "$@")
     status=$?
     ((status != 0)) && git-go-usage && return $status
     eval set -- "$OPTSARGS"
@@ -589,6 +594,7 @@ git-go ()
     do
         case "$1" in
             -l|--list) opt_list=1; shift ;;
+            --listfull) opt_list=2; shift ;;
             -m|--mbig) opt_mbig=1; shift ;;
             -r|--roots) opt_roots=1; shift ;;
             -u|--update) opt_update=1; shift ;;
@@ -629,19 +635,26 @@ git-go ()
     then
         echo $tgt does not match any repo
         git-go-usage
-        return
+        return 1
     fi
     if [ "$(echo $REPOS | wc -w)" = '1' ]
     then
         echo "Matches only $REPOS. Going there."
         REPO=$REPOS
     else
-        if (($opt_list))
+        if (($opt_list==1))
         then
             local r
             for r in $REPOS
             do
                 echo '~'/$r
+            done
+        elif (($opt_list==2))
+        then
+            local r
+            for r in $REPOS
+            do
+                echo ~/$r
             done
         else
             REPOS=$(tail_number_select $REPOS)
@@ -1247,7 +1260,7 @@ EOF
 Your branch should be up to date with its origin in order to simplify the
 check.
 EOF
-        if ((bail_on_dirty))
+        if ((opt_bail_on_dirty))
         then
             echo Exiting.
             return 1
@@ -2519,14 +2532,38 @@ git-find-deleted ()
 
     git rev-list -n 1 HEAD -- "$1"
 }
-git-checkout-deleted()
+
+git-find-last-existed ()
 {
-    ##@@ none||none||git-checkout-deleted||
+    ##@@ none||none||git-find-last-existed||The revision before which the given file was deleted.
     gitfuncs_audit "$@"
 
-    ## ^ is the revision before, so the revision before deleted, i.e., the last
-    ## revision in which $1 was present.
-    git checkout $(git-find-deleted "$1")^ -- "$1"
+    git rev-list -n 1 $(git-find-deleted "$1")^ -- "$1"
+}
+
+git-checkout-last-existed()
+{
+    ##@@ none||none||git-checkout-last-existed||Find the revision in which the given file last existed and check it out
+    gitfuncs_audit "$@"
+
+    git checkout $(git-find-last-existed "$1") "$1"
+}
+
+git-stdout-last-existed()
+{
+    ##@@ none||none||git-checkout-last-existed||Find the revision in which the given file last existed and print to stdout (or file.uuid if --file specified).
+    gitfuncs_audit "$@"
+
+    local file=''
+    if [ "$1" = '-file' ]
+    then
+        file='-file'
+        shift;
+    fi
+    for f in "$@"
+    do
+        git-to-stdout $file $(git-find-last-existed "$f") "$f"
+    done
 }
 
 git-root ()
@@ -3088,6 +3125,102 @@ git-merge-pull-request ()
     echo 'git push origin HEAD:master'
 }
 alias git-merge-pr='git-merge-pull-request '
+
+
+git-st-ext ()
+{
+    ##@@ none||none||git-st-ext||Read or write a note about this fork's current status
+    gitfuncs_audit "$@"
+
+    local git_st_ext_file="$(git-root)/.git-st-ext"
+    if [ -n "$1" ]
+    then
+        echo "$@" > $git_st_ext_file
+    else
+        if [ -e $git_st_ext_file ]
+        then
+            cat $git_st_ext_file
+        else
+            read -p "External status for $(git-root): " resp
+            echo "$resp" > $git_st_ext_file
+        fi
+    fi
+}
+
+git-st-ext-all ()
+{
+    ##@@ none||none||git-st-ext||Read all notes about repo current statuses
+    gitfuncs_audit "$@"
+
+    for i in $(git-go --listfull | grep 152)
+    do
+        local git_st_ext_file="${i}/.git-st-ext"
+        [ -r "$git_st_ext_file" ] && echo $i: $(cat $git_st_ext_file)
+    done
+}
+
+git-delete-current-repo ()
+{
+    gitfuncs_audit "$@"
+
+    git-delete-repo $(pwd)
+    status=$?
+    return $status
+}
+
+git-delete-repo ()
+{
+    ##@@ none||none||git-delete-repo||Delete the repo
+    gitfuncs_audit "$@"
+
+    local opwd=$(pwd)
+    local repo=$1;
+    local repofull=$(realpath $1);
+
+    builtin cd $repofull
+
+    ## Make sure we are in a proper repo.
+    if [ ! -d .git ]
+    then
+        echo "$repo is not a proper repo for deletion"
+        return 1
+    fi
+
+    ## Make sure it's clean.
+    if [ -d wt ]
+    then
+        echo "wt subdir found:"
+        ls -la wt
+        echo
+        echo "Will not delete current repo"
+        return 1
+    fi
+
+    git status 1>/dev/null 2>&1
+    local rc=$?
+    if ((rc)) || \
+           [ "$(git status --porcelain | wc -l)" != '0' ] || \
+           [ "$(git status | grep 'Your branch is' | grep -v 'up-to-date' | wc -l)" != '0' ]
+    then
+        git status
+        echo
+        echo "Will not delete current repo"
+        return 1
+    fi
+
+    ## Whack it. Start and end with the current dir.
+    local delit=$(basename $(pwd))
+    builtin cd ..
+    \rm -rf $delit; (( $? != 0 )) && echo "Bad rm of ./$delit (from $(pwd)). Aborting." && return 1;
+    echo "Done. Not touching remote repo."
+
+    [ -d $opwd ] && builtin cd ## If $opwd was the repo directory, it won't be
+                               ## there anymore. Stay where we are.
+
+    git-go-set
+
+    return 0
+}
 
 ## Can't use local outside a function.
 typeset forlater='
diff --git a/bin/vmfuncs b/bin/vmfuncs
--- a/bin/vmfuncs
+++ b/bin/vmfuncs
@@ -132,3 +132,128 @@ bldo-check ()
         done
     fi
 }
+
+vmrebuild ()
+{
+    local opt_berks=0
+    local opt_build=0
+    local opt_post=0
+    OPTSARGS=$(getoptp -o s --long berks,build,post -n 'vmbuild' -- "$@")
+    local status=$?
+    ((status != 0)) && $usage_func && return $status
+
+    eval set -- "$OPTSARGS"
+    while true
+    do
+        case "$1" in
+            --berks) opt_berks=1; shift ;;
+            --build) opt_build=1; shift ;;
+            --post) opt_post=1; shift ;;
+            --) shift; break ;; ## end of opts, remaining $*, if any, are args
+            *) echo "Internal error!"; $usage_func; return 1 ;;
+        esac
+    done
+
+    local strikes
+
+    ((!opt_berks)) && ((!opt_build)) && ((!opt_post)) && echo "ERROR: Need options" &&((strikes+=1))
+
+    echo "USER is '$USER' (\$USER)"
+    echo "IP is '$1' (\$1)"
+    [ -z "$1" ] && echo "ERROR: Need floating IP from https://openstack.dob1.bcpc.bloomberg.com/horizon/project/access_and_security/ in the IP Address column of the Floating IPs tab. " \
+        && ((strikes+=1))
+
+    echo "Checking NFS:"
+    ssh nylxdev1 ls -lad /home/$USER/public_html
+    (($?)) && echo "ERROR: NFS check" && ((strikes+=1))
+
+    if ((opt_berks)) && [ -z "$(which berks)" ]
+    then
+        echo "ERROR: No berks available here"
+        ((strikes+=1))
+    fi
+
+    echo "KEYPAIR is '$2' (\$2)"
+    [ -z "$2" ] && echo "ERROR: Need keypair from https://openstack.dob1.bcpc.bloomberg.com/horizon/project/access_and_security/" \
+        && ((strikes+=1))
+
+    if [ ! -r ${USER}/.ssh/id_rsa.toolkit ]
+    then
+        echo "ERROR: No id_rsa.toolkit file found"
+        ((strikes+=1))
+    fi
+
+    if ((opt_build))
+    then
+        if [ ! -r ~/.ssh/openstack_dob1_dpkgdev.yml ]
+        then
+            echo "ERROR: openstack_dob1_dpkgdev.yml missing"
+            ((strikes+=1))
+        else
+            cat openstack_dob1_dpkgdev.yml
+            echo "Is the password current?"
+        fi
+    fi
+
+    ((strikes)) && echo "FATAL: $strikes strikes, yer out!" && return $strikes
+
+    if ((opt_berks))
+    then
+        gitgo ${USER}-dev-cookbook
+        (($?)) && return 1
+
+        dirty=$(git status --porcelain)
+        if (($?)) || [ -n "$dirty" ]
+        then
+            echo "ERROR: git repo not clean"
+            return 1
+        fi
+
+        export BERKS_BBGITHUB_USE_SSH=1
+        berks install && (($?)) && return 1
+        berks update && (($?)) && return 1
+        berks package ${USER}-dev.tar.gz && (($?)) && return 1
+        scp ${USER}-dev.tar.gz ${NFSMACHINE}:public_html/ && (($?)) && return 1
+    elif ((opt_build))
+    then
+        gitgo bcpc-sous-chef
+        if [ $? = '0' ]
+        then
+            git pull
+        else
+            cd ~/gits/bbgithub && (($?)) && return 1
+            bbgithub-clone druoso bcpc-sous-chef
+            gitgo bcpc-sous-chef
+        fi
+
+        cookbook=${USER}-dev
+        image=''
+
+        echo "Fire up https://openstack.dob1.bcpc.bloomberg.com/horizon/project/instances/"
+        echo "and refresh until an instance named ${USER}-dev appears."
+        echo "Once it does, select it, go to the Log tab and select View Full Log."
+        echo "Refresh the page until the last line looks like:"
+        echo "cloud-init[3694]: Cloud-init v. 0.7.6 finished at Tue, 20 Oct 2015 16:07:58 +0000. Datasource DataSourceOpenStack [net,ver=2].  Up 201.62 seconds"
+
+        ./bcpc-sous-chef \
+            "$image" \
+            --cluster dob1 \
+            --credentials ~/.ssh/openstack_dob1_dpkgdev.yml \
+            --flavor m1.medium \
+            --instance $cookbook \
+            --keypair $KEYPAIR \
+            --recipe-url http://devhtml.dev.bloomberg.com/~$USER/${cookbook}.tar.gz \
+            --floating-ip $IP \
+            --runlist "${cookbook}::bcpc" --volume "${USER}-home"
+    elif ((opt_post ))
+    then
+        for f in /tmp/mpersico5-dev-cookbook-init \
+                     /tmp/mpersico5-dev-cookbook-fixpasswd \
+                     /tmp/mpersico5-dev-cookbook-cronscriptroot \
+                     /tmp/mpersico5-dev-cookbook-cronscriptuser
+        do
+            echo "** $f **"
+            $f
+        done
+    fi
+}
