utilfuncs broken out of profile, teeit for logit, pwdswap in cdfuncs, conflict help in gitfuncs

diff --git a/bin/logit b/bin/logit
--- a/bin/logit
+++ b/bin/logit
@@ -4,23 +4,36 @@
 # logit
 #
 
+usage ()
+{
+    echo "logit [--tee|-t] [ --log|-l log_basename ] command [arg ..]"
+    exit $1
+}
+
 # Take args, treat as a command + args and run all output to a file.
 
 # Inits
 logfile=''
 teeit=0
 
+if [ $(basename "${BASH_SOURCE[0]}") == 'teeit' ]
+then
+    teeit=1
+fi
+
 # Read the options and args from command line. Note that the long and short
 # don't have to match up.
-TEMP=`getopt -o l:t --long log:,tee -n 'logit' -- "$@"`
+GETOPTOUT=`getopt -o l:th --long log:,tee,help -n 'logit' -- "$@"`
 
-# Reset the command line ($@).
-eval set -- "$TEMP"
+# Reset the command line.
+eval set -- "$GETOPTOUT"
 
 # Reprocess the command line, extracting options and their arguments into
 # variables.
 while true ; do
     case "$1" in
+        -h|--help)
+            usage 0 ;;
         -l|--log)
             logfile="$2"
             shift 2 ;;
@@ -28,9 +41,16 @@ while true ; do
             teeit=1
             shift ;;
         --) shift ; break ;; ## VITAL!!! Exits the while loop, no more options
-        *) echo "Internal error!" ; exit 1 ;;
+        *) echo "Internal error!" ; usage 1 ;;
     esac
 done
+
+# Arg checking
+if [ -z "$1" ]
+then
+    echo "Command required."
+    usage 1
+fi
 
 command=$1
 shift
@@ -38,10 +58,11 @@ args="$@"
 
 if [ ! -x $command ]
 then
-    echo $command not found or not executable
-    exit 1
+    echo "'$command' not found or not executable."
+    usage 1
 fi
 
+# Log file setup
 if [ -z "$logfile" ]
 then
     logfile=$(basename $command)
@@ -56,9 +77,11 @@ else
 fi
 
 logspec="$logdir/$logfile"
-touch $logspec
+touch $logspec ## Critical for tee below
 logmsg="Logfile is: $logspec"
 echo $logmsg
+
+# And off we go...
 echo "Working..."
 
 if ((teeit))
@@ -72,11 +95,12 @@ then
         fi
     done
     $termer -g 132x40 -e tail -f $logspec &
-    sleep 2
+    sleep 2 ## Give the terminal a chance to come up and start tailing so we
+            ## see the whole log in the tali
 fi
 
 (
-    if [ -d .git ] || [ -n "$(git rev-parse --git-dir 2>/dev/null)" ]
+    if [ -n "$(git rev-parse --git-dir 2>/dev/null)" ]
     then
         echo "********************"
         echo "      git info      "
@@ -87,15 +111,18 @@ fi
     fi
 
     echo "********************"
-    echo "Command is: $command $args"
+    echo "      Command       "
     echo "********************"
+    echo $command $args
     echo
+
     echo "********************"
     echo "       Output       "
     echo "********************"
     $command $args
     status=$?
     echo
+
     echo "********************"
     echo $logmsg
     echo "Exit status: $status"
diff --git a/bin/vmfuncs b/bin/vmfuncs
--- a/bin/vmfuncs
+++ b/bin/vmfuncs
@@ -21,23 +21,51 @@ VMFUNCS_TOOLKIT_FILE=~/.ssh/id_rsa.toolkit
 VMFUNCS_TOOLKIT_EXPIRE_FILE=~/.ssh/id_rsa.toolkit.expires
 VMFUNCS_BCPCVMS_FILE=~/personal/bin/.bcpcvms
 
+_vm_toolkit_file_maint_usage ()
+{
+    echo "Usage: vm_toolkit_file_maint [-f|--force|-u|--update]"
+}
+
 vm_toolkit_file_maint ()
 {
     local msg=''
     local expiretime=0
-    if [ ! -r $VMFUNCS_TOOLKIT_FILE ]
+    local update=0
+    local OPTSARGS=$(getopt -o fuh --long force,update,help -n 'vm_toolkit_file_maint' -- "$@")
+    eval set -- "$OPTSARGS"
+    while true
+    do
+        case "$1" in
+            -h|--help) _rsync2nfs_usage; return 0 ;;
+            -f|-u|--force|--update) update=1; shift ;;
+            --) shift; break ;; ## end of opts, remaining $*, if any, are args
+            *) echo "Internal error!"; git-st-strip-usage; return 1 ;;
+        esac
+    done
+
+    if [ "$update" = '1' ]
+    then
+        msg="Toolkit credential update requested."
+    elif [ ! -r $VMFUNCS_TOOLKIT_FILE ]
     then
         msg="Toolkit credential file $VMFUNCS_TOOLKIT_FILE not found. Generating..."
+        update=1
     elif [ ! -r $VMFUNCS_TOOLKIT_EXPIRE_FILE ]
     then
-        msg="Toolkit credential file $VMFUNCS_TOOLKIT_FILE not found. Generating..."
+        msg="Toolkit credential file $VMFUNCS_TOOLKIT_EXPIRE_FILE not found. Generating..."
+        update=1
     else
         expiretime=$(cat $VMFUNCS_TOOLKIT_EXPIRE_FILE | grep -v '#')
         expiremsg=$(cat $VMFUNCS_TOOLKIT_EXPIRE_FILE | grep '#' | sed 's/#//g' | sed 's/ //g' )
         msg="Toolkit credential has expired ($expiremsg). Regenerating..."
+        now=$(date +%s)
+        if ((expiretime < now))
+        then
+            update=1
+        fi
     fi
-    now=$(date +%s)
-    if ((expiretime < now))
+
+    if [ "$update" = '1' ]
     then
         echo $msg
         ## Backups
@@ -121,3 +149,53 @@ vmdel ()
     vmshow
 }
 alias delvm='vmdel '
+
+_rsync2nfs_usage ()
+{
+    echo "Usage: rsync2nfs -t|--target tgt src [src...]"
+    echo
+}
+
+rsync2nfs ()
+{
+    local target
+    local OPTSARGS=$(getopt -o t:h --long target:,help -n 'vmsync2nfs' -- "$@")
+    eval set -- "$OPTSARGS"
+    while true
+    do
+        case "$1" in
+            -h|--help) _rsync2nfs_usage; return 0 ;;
+            -t|--target) shift; target=$1; shift ;;
+            --) shift; break ;; ## end of opts, remaining $*, if any, are args
+            *) echo "Internal error!"; git-st-strip-usage; return 1 ;;
+        esac
+    done
+
+    if [ -z "$target" ]
+    then
+        echo "--target required";
+        _vmsync2nfs_usage;
+    fi
+
+    ## -a "archive" mode, which ensures that symbolic links, devices,
+    ## -attributes, permissions, ownerships, etc. are preserved in the
+    ## -transfer.
+    ## -z - transport compressed
+    ## -r - recurse
+    ## -l - copy symlinks as symlinks
+    ## -v - verbose
+    rsync -azrlv "$@" $target
+    return $?
+}
+
+vmrsyncgits ()
+{
+    rsync2nfs --target nylxdev1.dev.bloomberg.com:vmstashes/$(hostname)/mpersico5 ~/gits
+}
+
+vmrsync ()
+{
+    rsync2nfs --target nylxdev1.dev.bloomberg.com:vmstashes/$(hostname) ~
+}
+
+alias vmsync='vmrsync '
