error message update

diff --git a/bin/logit b/bin/logit
--- a/bin/logit
+++ b/bin/logit
@@ -61,7 +61,15 @@ purge=''
 # Read the options and args from command line.
 GETOPTOUT=`getopt -o h -l tee,log:,dir:,edit,editor:,purge,purgeprior,help,cmd -n 'logit' -- "$@"`
 status=$?
-((status != 0)) && echo "Exiting." && exit $status
+if ((status != 0))
+then
+    echo "If the error was 'unrecognized option...'"
+    echo "then logit read an option to your program"
+    echo "as its own. Add -- as the last logit option"
+    echo "right before your command."
+    echo "Exiting."
+    exit $status
+fi
 
 # Reset the command line.
 eval set -- "$GETOPTOUT"
