bin/makesymlinks o Added explicit check for dotfiles dir arg.

diff --git a/bin/makesymlinks b/bin/makesymlinks
--- a/bin/makesymlinks
+++ b/bin/makesymlinks
@@ -16,6 +16,12 @@ then
     shift
 fi
 
+if [ -z "$1" ]
+then
+    echo "Missing dotfiles directory arg"
+    exit 1
+fi
+
 dotfiles_dir=$1
 builtin cd "$dotfiles_dir" || exit 1
 dotfiles_dir="$(pwd)"
