Sync before VM rebuild. Details: bin/.gitignore: Added 1381bucket.log. bin/1381bucket.cron: New. Daily email to the 1381 watcher. bin/auditfuncs (auditfuncs_edit): Added safe_func_export here, early. bin/gitfuncs (git-check-with-remote): Get opt_bail_on_dirty variable spelling right.              (git-checkout-last-existed): Updated to use git-find-last-existed.              (git-find-last-existed): New.              (git-process-changelog): Remove unused backup.              (git-st-ext): Read or store an external status for the repo.              (git-st-ext-all): Read all the repo external status files.              (git-status-with-changelog): Silence the rm of the temp output.              (git-stdout-last-existed): New. bin/sedinplace (status): Add --new to write updated to a new file. bin/utilfuncs: All functions updated to use safe_func_export.               (safe_func_export): New. Allows func export if under bash. Otherwise no. Which still leaves the question of making scripts calling funcs work under other shells for another day. bin/vmfuncs (vmrebuild): New. Automate vm rebuild. dotfiles/profile.mpersico5: Call to builddebfuncs added.

diff --git a/bin/sedinplace b/bin/sedinplace
--- a/bin/sedinplace
+++ b/bin/sedinplace
@@ -13,17 +13,17 @@ typeset sedcmdfile=$(mktemp --suffix=.sedinplace)
 trap finish EXIT SIGINT
 finish ()
 {
-    if [ -e $tfile ]
+    if [ -e $sedcmdfile ]
     then
-        rm -rf $tfile
+        rm -rf $sedcmdfile
     fi
 }
 
-typeset sedopts=''		## Options to the sed command
+typeset sedopts=''	        ## Options to the sed command
 typeset sedopt_inplace='-i'	## Particular option typeset sedopts
 typeset opt_confirm=0
-typeset opt_backup=0
 typeset opt_verbose=0
+typeset opt_new=''
 typeset OPTSARGS
 typeset status
 typeset arg
@@ -36,7 +36,7 @@ typeset f
 ##
 
 ## Read the args and options from the command line
-OPTSARGS=$(getoptp -o cbv -l confirm,backup,verbose -n $0 -- "$@")
+OPTSARGS=$(getoptp -o cbvn: -l confirm,backup,verbose,new: -n $0 -- "$@")
 status=$?
 ((status != 0)) && echo "Exiting." && exit $status
 
@@ -49,12 +49,10 @@ while true ; do
 	    -c|--confirm)
 	        opt_confirm=1
 	        sedopt_inplace='-i.sip'
-	        opt_backup=1
 	        shift
 	        ;;
 	    -b|--backup)
 	        sedopt_inplace='-i.sip'
-	        opt_backup=1
 	        echo "Backups in .sip files"
 	        shift
 	        ;;
@@ -62,6 +60,11 @@ while true ; do
 	        opt_verbose=1
 	        shift
 	        ;;
+        -n|--new)
+	        sedopt_inplace='-i.sip'
+	        opt_new=$2
+            shift;shift
+            ;;
 	    --)
 	        shift
 	        break
@@ -71,6 +74,7 @@ while true ; do
 done
 
 ## process args
+
 for arg in "$@"
 do
     ## Need -e and -f. -e makes it a file system object. -f alone
@@ -80,6 +84,7 @@ do
     then
 	    files+=("$arg")
     else
+        ### TODO - NEED A WAY TO GET ARGS WITH SPACES IN HERE!!!!!!!!
 	    echo "$arg" >> $sedcmdfile
     fi
 done
@@ -114,6 +119,11 @@ do
 		        echo "No changes in $f"
             fi
 		    \rm ${f}.sip
+        elif ((opt_new))
+        then
+            \mv ${f} ${f}.${opt_new};status=$?;((status)) && echo "Rename ${f} ${f}.${opt_new} error. Exiting." && exit 1
+            \mv ${f}.sip ${f};status=$?;((status)) && echo "Rename ${f}.sip ${f} error. Exiting." && exit 1
+            ((opt_verbose)) && echo "${f}.${opt_new}"
         elif ((opt_confirm))
         then
             echo
