Monthly grouping.
bin/.gitignore:
o Moved files to data.

bin/1381bucket.cron:
o Add permanent emails.
o Added --who for today's bucketeer and --predict for the next one.
o Added real option processing, tday handling. Allow setting the day
  instead of always using 'today'.
o put data files in ../data.

bin/1381bucket.holidays:
o Moved to data, no longer tracked.

bin/auditfuncs
auditfuncs_init():
  o If first arg is -na, do not audit.

is_func_defined():
  o New.

replm1():
  o Replaced by repl.

bin/builddebfuncs:
o Added dprp aliases.

bin/gitfuncs:
o Replace hardcoded function names with dynamic name in getoptp calls.
o Sprinkled just enough safe_func_export calls to make PS1 in a subshell
  stop barking.
o Change no-audit processing.

_git_cd*():
  o New. Allow us to move around in git functions with context.

git-delete-worktree():
  o Add git worktree prune after the directory is whacked.
  o Added usage func with aliasing and --force option.

git-get-stash-count():
  o -no0, do not print anything if count is 0. For prompts.

git-hold-*():
  o All removed. Not used.

git-meta():
  o Use config file keys to store info.

git-process-changelog():
  o Added --noless option, primarily for git-state.

git-st-ext():
  o Rewritten using git-meta.

git-st-ext-all():
  o Rewritten using git-meta.

git-state():
  o Now calls git-st-cl and git-st-ext

git-status-with-changelog():
  o Added --noless option processing for git-process-changelog.

git-sync-with-remote():
  o Un-inline stash-pop-return sequences because if there is no stash, the
    inline sequence exits before the return.
  o Rework git pull, push, stash pop logic and messages. Sucessful pull and
    a skipped push would result in the stash not being popped.

git-worktree-create():
  o Fixes to make the use-existing-branch-for-worktree case.

git-worktree-diff-to-root():
  o Add -E to less command to avoid q at end of less.

bin/parse-changelog:
o Use @file_list to limit git status and git diff calls to just files on
  command line, if any.

bin/rsyncfuncs
rsyncvm():
  o Add back the ps output in rsyncvm for a dup instance.

bin/toolkit-login:
o Exit with explicit 0 good, non-zero bad

bin/toolkitfuncs
toolkit-file-maint():
  o Capture exit status from toolkit-login instead of blindly continuing.
    Run the sudo command suggested in toolkit-login.
  o Call return, not exit, in a function.

bin/utilfuncs:
o Added a[clear|count|list|splice|push|pop|([u]shift)].
o is_func_defined, safe_func_export and repl synchronized to auditfuncs.

bash_current_version_compare():
  o New. Used to check for declare -n being ok in array funcs.

bin/vmfuncs
bldo-go():
  o New. Pick a random BLDO machine, optionally limited to a specific
    architecture, and go there.

data/.gitignore:
o Moved files from bin.

dotfiles/dotfiles.manifest:
o Added emacs_bash to get profiles run on M-x shell.

dotfiles/emacs_bash:
o Startup for emacs shell mode.

dotfiles/gitconfig:
o Added color.diff.commit "yellow black" in order to more easily see the
  SHA1 of a commit in a git log command.
o Alphbetize aliases.

dotfiles/gitignore:
o Added mopChangeLog entries.

dotfiles/profile.mpersico5:
o Move /opt/bb path adjustments up from near end to right after *funcs
  loads.

PS1():
  o Pulled git-hold stuff. Added -no0 to skip stash line entirely if
    stashes == 0.
  o Added version without terminal title change commands when under emacs.

git_contrib_loaded():
  o Restored the func export of the __git functions.

on_nfs():
  o Add branch status check after remote master branch check.

diff --git a/bin/vmfuncs b/bin/vmfuncs
--- a/bin/vmfuncs
+++ b/bin/vmfuncs
@@ -133,6 +133,47 @@ bldo-check ()
     fi
 }
 
+bldo-go ()
+{
+    set -x
+    local arch='.*'
+    OPTSARGS=$(getoptp  --long arch: -n 'bldo-go' -- "$@")
+    local status=$?
+    ((status != 0)) && return $status
+
+    eval set -- "$OPTSARGS"
+    while true
+    do
+        case "$1" in
+            --arch)
+                case $2 in
+                    i|ibm|aix)
+                        arch=ibldo;;
+                    l|lnx|linux|amd64)
+                        arch=lnxbldo;;
+                    s|sun|sol|solaris)
+                        arch=sbldo;;
+                    *)
+                        echo "$2 is not a valid arch"
+                        return 1
+                        ;;
+                esac
+                shift;shift;;
+            --) shift; break ;; ## end of opts, remaining $*, if any, are args
+            *) echo "Internal error!"; $usage_func; return 1 ;;
+        esac
+    done
+
+    machine=$( cat /bb/csdata/bldfarm/pools/*BLDO* \
+                      | grep -E "$arch" \
+                      | head -$(($RANDOM%$(cat /bb/csdata/bldfarm/pools/*BLDO* \
+                                                  | grep -E "$arch" \
+                                                  | wc -l))) | tail -1)
+
+    ssh $machine;
+    set +x
+}
+
 vmrebuild ()
 {
     local opt_berks=0
