added a check for the WMIC executable and some cleanup for procpid test to int handling

diff --git a/bin/winproc_is_running b/bin/winproc_is_running
--- a/bin/winproc_is_running
+++ b/bin/winproc_is_running
@@ -4,6 +4,13 @@
 
 # See if a process is running in Windows proc space
 
+declare wmic_cmd="/mnt/c/Windows/System32/wbem/WMIC.exe"
+if [ ! -f "$wmic_cmd" ]
+then
+    echo "WMIC command not found. Is this WSL on a Windows machine?"
+    exit 1
+fi
+
 declare verbose=0
 if [ "$1" = '-v' ]
 then
@@ -13,8 +20,7 @@ fi
 
 declare procname=$1
 
-procpid=$(/mnt/c/Windows/System32/wbem/WMIC.exe  process where "name='$procname'" get processid 2>/dev/null | tail -2 )
-procpid="$(perl -e 'chomp $ARGV[0]; print $ARGV[0]+0' $procpid)"
+procpid="$($wmic_cmd process where "name='$procname'" get processid 2>/dev/null | tail -2 | perl -ne 'chomp $_; print int($_) ')"
 
 if ((verbose))
 then
