Periodic commit.
bin/cdfuncs
dirlist():
  o Accepts ^n in addition to -n to go up 'n' directories.

bin/histfuncs
load_history():
  o Added alias to show the current history file.

bin/xo
--gim():
  o Option to run git-is-modified to load all files modified in a git repo,
    since that is usually what we need to work on.

--root():
  o Actually check for emacs and emacsclient at the specified root.

dotfiles/xterminit
newx*():
  o Generating functions dynamically.

diff --git a/bin/xo b/bin/xo
--- a/bin/xo
+++ b/bin/xo
@@ -4,11 +4,11 @@
 ## Filters out the grep command
 ## Filters in where parent ppid is 1 (in case emacs is running a perl debugger
 ## or some other subprocess)
-
 debug=0
 forceX=0
 emacs_exe=$(which emacs)
 emacsclient_exe=$(which emacsclient)
+gim=''
 while [[ "$1" =~ ^- ]]
 do
     case "$1" in
@@ -23,8 +23,16 @@ do
             ;;
         --root )
             emacs_exe="$2/emacs"
-            emacsclient_exe="$2/emacs"
+            emacsclient_exe="$2/emacsclient"
             shift;shift;
+            for i in $emacs_exe $emacsclient_exe
+            do
+                [ -x $i ] || (echo "Cannot find '$i'. --root cannot be used." && exit 1);
+            done
+            ;;
+        --gim )
+            gim=$(git-is-mod)
+            shift
             ;;
     esac
 done
@@ -120,25 +128,25 @@ then
     then
         if (( hasX ))
         then
-            $emacs_exe "$@" &
+            $emacs_exe "$@" $gim &
         else
-            $emacs_exe -nw "$@" < /dev/tty
+            $emacs_exe -nw "$@" $gim < /dev/tty
         fi
     else
         echo "No emacs server found. Start one and try again or use -m."
     fi
 elif ((serverup==1))
 then
-    if [ ! "$#" = 0 ]
+    if [ ! "$#" = 0 ] || [ -n "$gim" ]
     then
         if ((new_frame))
         then
-            $emacsclient_exe -c "$@" | grep -v 'Waiting for Emacs' &
+            $emacsclient_exe -c "$@" $gim | grep -v 'Waiting for Emacs' &
         elif ((as_visual==1))
         then
-            $emacsclient_exe -c "$@"
+            $emacsclient_exe -c "$@" $gim
         else
-            $emacsclient_exe -n -a $emacs_exe "$@"
+            $emacsclient_exe -n -a $emacs_exe "$@" $gim
         fi
     else
         echo "Server already up. Specify a file to edit."
