Periodic
bin/cmd-echo
* Only reset colors if using colors so that you don't undo a terminal set

bin/color-echo
* Fix option processing - didn't properly compose envvars for lookup.

bin/xo
* Added xo.rc functionality.

diff --git a/bin/xo b/bin/xo
--- a/bin/xo
+++ b/bin/xo
@@ -20,12 +20,14 @@ if [[ -z $emacs_exe ]] ; then
 fi
 emacsclient_exe="${emacs_exe}client"
 declare -a git_is_mod ## These are modified files in a git repo
-declare -a which ## We used to use the 'which' utility to find these
-declare -a org ## The org file
+declare -a which      ## We used to use the 'which' utility to find these
+declare -a org        ## The org file
+declare -a xorc       ## If we find ./xo.rc, we read it for files to load
 declare as_visual=0
 declare new_frame=0
 declare more_opts=1
 declare nobg=0
+declare use_rc=1
 declare -a emacs_opts
 while ((more_opts)) && [[ "$1" =~ ^- ]]; do
     original="$1"
@@ -55,7 +57,7 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
             tmp=$(type -P "$1")
             shift
             if [[ -z "$tmp" ]]; then
-                cmd-echo -wc -- "$1 not found; skipping"
+                cmd-echo --id xo -wc -- "$1 not found; skipping"
             else
                 which+=("$tmp")
             fi
@@ -65,7 +67,7 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
             emacsclient_exe="$1/emacsclient"
             declare i
             for i in $emacs_exe $emacsclient_exe; do
-                [[ -x "$i" ]] || (cmd-echo "Cannot find '$i'. --root cannot be used." && exit 1);
+                [[ -x "$i" ]] || (cmd-echo --id xo "Cannot find '$i'. --root cannot be used." && exit 1);
             done
             shift
             ;;
@@ -74,7 +76,7 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
             emacsclient_exe="${1}client"
             declare i
             for i in $emacs_exe $emacsclient_exe; do
-                [[ -x "$i" ]] || (cmd-echo "Cannot find '$i'. --root cannot be used." && exit 1);
+                [[ -x "$i" ]] || (cmd-echo --id xo "Cannot find '$i'. --root cannot be used." && exit 1);
             done
             shift
             ;;
@@ -82,9 +84,9 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
             mapfile -t git_is_mod < <(git what is mod 2>/dev/null)
             if [[ -z "${git_is_mod[0]}" ]]; then
                 if ! git root 2>/dev/null 1>&2; then
-                    cmd-echo -- "--gim not allowed; not in a git repo"
+                    cmd-echo --id xo -- "--gim not allowed; not in a git repo"
                 else
-                    cmd-echo -- "No modified git files found."
+                    cmd-echo --id xo -- "No modified git files found."
                 fi
                 exit 1
             fi
@@ -95,13 +97,16 @@ while ((more_opts)) && [[ "$1" =~ ^- ]]; do
         todo | org )
             org=("$HOME/todo.org")
             ;;
+        norc )
+            use_rc=0
+            ;;
         help )
             bash-usage "$0"; exit 0;;
         -- )
             more_opts=0
             ;;
         * )
-            cmd-echo -- "$original is an invalid option. See $0 --help"; exit 1;;
+            cmd-echo --id xo -- "$original is an invalid option. See $0 --help"; exit 1;;
     esac
 done
 
@@ -129,7 +134,7 @@ case $OS in
         grepargs='-- emacs-w32'
         ;;
     * )
-        cmd-echo "ps command for $OS not defined"
+        cmd-echo --id xo "ps command for $OS not defined"
         exit 1
         ;;
 esac
@@ -187,8 +192,18 @@ elif [[ "$1" = '--nf' ]] || [[ "$1" = '-nf' ]]; then
     shift
 fi
 
+if ((use_rc)) && [[ -r ./xo.rc ]]; then
+    declare xorcline
+    while read -r xorcline; do
+        declare -a xorcline_a
+        read -a xorcline_a -r <<< "$xorcline"
+        xorc+=("${xorcline_a[@]}")
+    done < ./xo.rc
+    [[ -n ${xorc[0]} ]] && cmd-echo --id xo -- "Loading these files from ./xo.rc:" "${xorc[@]}"
+fi
+
 declare -a allfiles
-allfiles=("$@" "${org[@]}" "${git_is_mod[@]}" "${which[@]}")
+allfiles=("$@" "${org[@]}" "${git_is_mod[@]}" "${which[@]}" "${xorc[@]}")
 if ((serverup==0)); then
     if ((as_visual==0)) && ((new_frame==0)); then
         if (( hasX )); then
@@ -206,7 +221,7 @@ if ((serverup==0)); then
                        "${emacs_opts[@]}" "${allfiles[@]}" < /dev/tty
         fi
     else
-        cmd-echo "No emacs server found. Start one and try again or use -m."
+        cmd-echo --id xo "No emacs server found. Start one and try again or use -m."
     fi
 elif ((serverup==1)); then
     if ((${#allfiles[@]})); then
@@ -222,12 +237,12 @@ elif ((serverup==1)); then
             $emacsclient_exe -n -a "$emacs_exe" "${emacs_opts[@]}" "${allfiles[@]}"
         fi
     else
-        cmd-echo "Server already up. Specify a file to edit."
+        cmd-echo --id xo "Server already up. Specify a file to edit."
         $pscmd | head -1
         cat "$procs"
     fi
 else
-    cmd-echo "More than one potential emacs server process found:"
+    cmd-echo --id xo "More than one potential emacs server process found:"
     cat "$procs"
 fi
 
@@ -243,6 +258,7 @@ xo - Start up emacs, using X and client mode where possible.
   xo [--debug] [--forceX] [--root /path/to/emacs-root-dir] \\
      [--exe /path/to/emacs ] \\
      [--org|--todo] [--gim] [--which file[,file...]] \\
+     [--norc] \\
      [-- any-emacs-opts] [file [file...]]
 
   xo [--nobg] --geo-only <emacs opts and args>
@@ -304,6 +320,13 @@ and edit those.
 =item --which
 
 Take fhe files specified as basenames and look for them on PATH.
+
+=item --norc
+
+Do not process any './xo.rc' file found. The default is to process such a
+file. If found, it is expected to contain paths to files to open in the
+editor. The files must be locatable from the current directory; either absolute
+paths or relative the direcdtory in which the xo.rc file is found.
 
 =item --nf
 
