func to exec, convert phase

diff --git a/bin/xterm_Xground b/bin/xterm_Xground
--- a/bin/xterm_Xground
+++ b/bin/xterm_Xground
@@ -1,50 +1,108 @@
 #!/usr/bin/env bash
 
-# <Function Class: xterm>
-# <Function Justification: none>
+# xterm_Xground
 
-xterm_Xground ()
-{
-    [ -z "$1" ] && echo "Missing arg: 11 for foreground, 10 for background" && return 1
-    local col=$1
-    local iam
-    iam=$(func-name-spoof)
-    if [ -n "$XTERM_SHELL" ]
-    then
-        ## from http://superuser.com/questions/157563/programmatic-access-to-current-xterm-background-color
-        exec < /dev/tty
-        oldstty=$(stty -g)
-        stty raw -echo min 0
-        #          OSC   Ps  ;Pt ST
-        echo -en "\\033]${col};?\\033\\" >/dev/tty  # echo opts differ w/ OSes
-        result=
-        if IFS=';' read -r -d \\ color ; then
-            result=$(echo "$color" | sed 's/^.*\;//;s/[^rgb:0-9a-f/]//g')
-            idxresult=$(echo "$result" | sed 's/[:/]//g')
-        fi
-        stty "$oldstty"
-        local var=xterm_Xground_map_${idxresult}
-        local color
-        color=$(eval echo "\$$var")
-        if [ -n "${color}" ]
-        then
-            echo "${color}"
-            return
-        else
-            echo "## WARNING:$iam - no mapped color found for $result" >&2
-        fi
-    else
-        echo "## WARNING:$iam - XTERM_SHELL not defined, probably not an xterm" >&2
+[ -z "$1" ] && echo "Missing arg: 11 for foreground, 10 for background" && exit 1
+declare col
+col=$1
+declare iam
+iam=$(func-name-spoof)
+if [ -n "$XTERM_SHELL" ]
+then
+    ## from http://superuser.com/questions/157563/programmatic-access-to-current-xterm-background-color
+    exec < /dev/tty
+    oldstty=$(stty -g)
+    stty raw -echo min 0
+    #          OSC   Ps  ;Pt ST
+    echo -en "\\033]${col};?\\033\\" >/dev/tty  # echo opts differ w/ OSes
+    result=
+    if IFS=';' read -r -d \\ color ; then
+        result=$(echo "$color" | sed 's/^.*\;//;s/[^rgb:0-9a-f/]//g')
+        idxresult=$(echo "$result" | sed 's/[:/]//g')
     fi
-
-    if [ -n "$NEWXCOLOR" ]
+    stty "$oldstty"
+    declare var
+    var=xterm_Xground_map_${idxresult}
+    declare color
+    color=$(eval echo "\$$var")
+    if [ -n "${color}" ]
     then
-        echo "$NEWXCOLOR"
-        return
+        echo "${color}"
+        exit
     else
-        echo "## WARNING:$iam - NEWXCOLOR not defined" >&2
+        echo "## WARNING:$iam - no mapped color found for $result" >&2
     fi
+else
+    echo "## WARNING:$iam - XTERM_SHELL not defined, probably not an xterm" >&2
+fi
 
-    echo "## WARNING:$iam - default color is grey" >&2
-    echo grey
-}
+if [ -n "$NEWXCOLOR" ]
+then
+    echo "$NEWXCOLOR"
+    exit
+else
+    echo "## WARNING:$iam - NEWXCOLOR not defined" >&2
+fi
+
+echo "## WARNING:$iam - default color is grey" >&2
+echo grey
+## POD guard
+exit 0
+
+## You can add sections with =head1, but stick to =item for section breakdowns,
+## not =head2/3/etc/.
+
+:<<'__PODUSAGE__'
+=head1 NAME
+
+xterm_Xground - script that does something
+
+=head1 SYNOPSIS
+
+ xterm_Xground [--option1] [ --option2 optionarg ] arg1 [arg2 ...] 
+     [fee] [dfsdfs] [sfsdfsf]
+
+=head1 DESCRIPTION
+
+Describe in general terms what xterm_Xground does.
+
+=head1 ARGUMENTS
+
+=over 4
+
+=item arg
+
+Describe what arg does, should be, etc. Add a new =item for each distinct arg.
+
+=back
+
+=head1 OPTIONS
+
+=over 4
+
+=item --option1
+
+Describe what --option1 does.
+
+=item --option2
+
+Describe what --option2 does. Describe what optionarg does.
+
+=over 2
+
+=item *
+
+A choice for optionarg
+
+=item *
+
+Another choice for optionarg
+
+=back
+
+=back
+
+=cut
+
+__PODUSAGE__
+
