KTLO - 2026-07-11
bin/ai.mopenv
* New file - AI setups.

bin/bash-history-parse
* Fixed matching on a directory.

bin/bash-history-purge
* Replace hardcoded directories.

bin/cmd-yesno
* Added a gui option.

bin/git-claude
* Init or resume a claude session in the current directory by name
  repo/branch.

bin/git-repo
git-repo-id():
  * Print repo/branch. Written for naming claude sessions.

bin/git-version-verify
* Add action-to-take message.

bin/git.mopenv
* Don't reload __git_ps1* functions if already loaded, but do run a
  save_func_export on them so that they appear in prompts in subshells.
* Do not load git completion; can't complete on files on git commands if
  loaded.

bin/is-text
* Can I print a file to a terminal and not break the terminal?

bin/misc.alias
* Remove tkman.

bin/perl-quote-hashkeys
* Turns unquoted and unnecessarily-double-quoted hash keys into
  single-quoted ones.

bin/perl.mopenv
* Set the system perl before perlbrewing.

bin/perltidy-bulk
* Added a --summary-only option.

bin/post-any-install
* Added x/y progress to all package install phases.

pai-patch():
  * Now can specify local build overrides for packages in package lists.w

pai-perlbrew-modules():
  * Skip same-day multiple cpanm install, force any other. This eliminates
    the prompt that stalls automated runs.

bin/post-any-install.data
* Moved variables to post-any-install.data so data doesn't clutter up the
  code.

bin/script
* Wrap the script command so we don't clobber any prior output.

bin/show
* Added dialog centering.
* Added unique window check.

bin/ttyd
* Wrap ttyd.exe with some instructions, default args and a marking
  envvar.

bin/util.mopenv
* pai aliases removed.

bin/wsl.mopenv
* Set browser to WSL brave or Windows brave.
* Establish ~/winhome.

bin/yesno
* Plug in yad for a popup dialog.
* Added a --gui option.

dotfiles/bash_profile
* Account for ~/.local and ~/.config.

dotfiles/gitconfig_personal
* Added https to ssh url conversion for github.

dotfiles/post-any-install
* bash completion function for same-named script.

functions/ajoin
* Refactor to have only one exit point. Better when debugging.

functions/asplit
* Expanded --help option.

functions/bash-history-init
* Don't lookup xterm colors under 'ttyd'.

functions/git
* Process 'aliases' command immediately, including those hardcoded into
  the git function, and distinguish between the two types.

functions/gtkman
* Replacing with webman.

functions/local-screen-center-factor
* Adjust centering factor for different screen layouts.

functions/notepadpp
* Start the notepad++ program, not on PATH.

functions/webman
* Force man to a webpage (-H).

functions/x-current-root
* Add -center, return by value args.

diff --git a/bin/yesno b/bin/yesno
--- a/bin/yesno
+++ b/bin/yesno
@@ -9,11 +9,32 @@ declare do_print
 do_print=1
 declare choices
 choices="y/n"
+declare gui=0
+declare title=yesno
 
 while [[ "$1" =~ ^- ]]; do
-    [[ "$1" =~ -nop ]] && do_print=0 && shift
-    [[ "$1" == -q ]] && choices="y/n/q" && shift
-    [[ "$1" == '--' ]] && shift
+    if [[ "$1" =~ -nop ]]; then
+        do_print=0
+        shift
+    elif [[ "$1" == -q ]]; then
+        choices="y/n/q"
+        shift
+    elif [[ "$1" =~ '--gui' ]]; then
+        gui=1
+        shift
+        IFS="=" read -ra parts <<< "$1"
+        if [[ -n ${parts[1]} ]]; then
+            title="${parts[1]}"
+        else
+            title="$1"
+            shift
+        fi
+    elif [[ "$1" == '--' ]]; then
+        shift
+    else
+        echo "[yesno] >>> '$1' is an invalid option."
+        false; exit
+    fi
 done
 
 declare prompt_text
@@ -21,16 +42,51 @@ prompt_text=$1;shift
 declare default
 default=$1;shift
 
-declare respyn
-respyn=$(pick "$prompt_text" "$choices" "$default")
+if (( gui == 0 )); then
+    declare respyn
+    respyn=$(pick "$prompt_text" "$choices" "$default")
 
-## Print response if asked, then exit as requested.
-((do_print)) && echo "$respyn"
-if [[ "$respyn" = 'y' ]]; then true
-elif [[ "$respyn" = 'n' ]]; then false
-else exit 2 ## 'q'
+    ## Print response if asked, then exit as requested.
+    ((do_print)) && echo "$respyn"
+    if [[ "$respyn" = 'y' ]]; then true
+    elif [[ "$respyn" = 'n' ]]; then false
+    else exit 2 ## 'q'
+    fi
+    exit
+else
+    declare -a yad_cmd=(
+        yad
+        --title "$title"
+        --text "$prompt_text?"
+        --on-top
+        --skip-taskbar
+        --button=Yes:0
+        --button=No:1
+        --buttons-layout=center
+        --geometry "$(x-current-root --geo)"
+    )
+    if [[ "$choices" == 'y/n/q' ]]; then
+        yad_cmd+=(--button=Quit:2)
+    fi
+
+    if [[ -n "$default" ]]; then
+        case ${default,,} in
+            q* )  yad_cmd+=(--default-button=Quit) ;;
+            y* )  yad_cmd+=(--default-button=Yes) ;;
+            n* )  yad_cmd+=(--default-button=No) ;;
+        esac
+    fi
+    "${yad_cmd[@]}"
+    declare status=$?
+    if ((do_print)); then
+        case $status in
+            0 ) echo 'y';;
+            1 ) echo 'n';;
+            2 ) echo 'q';;
+        esac
+    fi
+    exit $status
 fi
-exit
 
 # shellcheck disable=SC2317 #https://github.com/koalaman/shellcheck/wiki/SC2317
 :<<'__PODUSAGE__'
