Now can add a comment on repo, branch, worktree

diff --git a/functions/git-go b/functions/git-go
--- a/functions/git-go
+++ b/functions/git-go
@@ -18,6 +18,7 @@ git-go ()
     local opt_exact=''
     local opt_size=0
     local opt_brief=0
+    local opt_comments=0
     local moreopts
     local -a limited
     moreopts=1
@@ -36,6 +37,7 @@ git-go ()
             et | exact-tail ) opt_exact='--exact-tail';;
             eh | exact-head ) opt_exact='--exact-head';;
             l | list ) opt_list=1 ;;
+            comment* | with-comment*) opt_comments=1 ;;
             listfull ) opt_list=2 ;;
             size ) opt_size=1; opt_list=1 ;;
             m | mbig ) git_get_opts+=('-m') ;;
@@ -182,6 +184,15 @@ git-go ()
                                     echo
                                 fi
                             fi
+                        )
+                    fi
+                    if ((opt_comments))
+                    then
+                        (
+                            cd "${TILDAE:-$HOME}/$r" || (echo "Cannot cd ${TILDAE:-$HOME}/$r" && return 1);
+                            local output
+                            output="$(git comment --show --hi)"
+                            [[ -n $output ]] && echo "    $output" && echo
                         )
                     fi
                 fi
