Cannot use global cache

diff --git a/functions/use b/functions/use
--- a/functions/use
+++ b/functions/use
@@ -3,9 +3,6 @@
 # <Function Class: bash env>
 # <Function Justification: env mod, sourcing file>
 
-declare -A _bash_inc_loaded # Keep track of sourced bincs. Only good per
-                            # process, not cross process.
-
 use ()
 {
     if [[ -z $1 ]]; then
@@ -14,23 +11,21 @@ use ()
     fi
 
     local name=$1
-    if [[ -n ${_bash_inc_loaded[$name]} ]]; then
-        [[ -n $BASH_INC_VERBOSE ]] && echo "use(bash): '$name' already sourced"
-        true && return $?
-    fi
-
     local libpath="$BASH_INC_DIR/${name}.binc"
     if [[ ! -r $libpath ]]; then
-        echo "use(bash): Cannot read '$libpath' to load it"
+        echo "use(bash): Cannot read '$libpath' to load it">&2
         false; return $?
     fi
+
     # shellcheck disable=SC1090 #https://github.com/koalaman/shellcheck/wiki/SC1090
     if . "$libpath"; then
-        _bash_inc_loaded[$name]="$libpath"
-        [[ -n $BASH_INC_VERBOSE ]] && echo "use(bash): '$libpath' sourced"
+        echo "******** use sourced $libpath ********">&2
+        [[ -n $BASH_INC_VERBOSE ]] \
+            && echo "use(bash): '$libpath' sourced"
         true; return $?
     fi
-    echo "use(bash): Error sourcing '$libpath'"
+
+    echo "use(bash): Error sourcing '$libpath'">&2
     false; return $?
 }
 
@@ -38,7 +33,7 @@ use ()
 :<<'__PODUSAGE__'
 =head1 NAME
 
-use - include bash include files, idempotently per process.
+use - include bash include files
 
 =head1 SYNOPSIS
 
@@ -54,9 +49,10 @@ Source in files of bash utils.
 
 =item file
 
-For file "foo", find "$BASH_INC_DIR/foo.binc" and source it in if not sourced
-already. All "*binc" files must return true when sourced. Call 'true' at the
-end of the file (like putting a 1; at the end of a Perl module).
+For file "foo", find "$BASH_INC_DIR/foo.binc" and source it in. All "*binc"
+files must return true when sourced. Call 'true' at the end of the file (like
+putting a 1; at the end of a Perl module). The '.binc' files must be
+re-entrant. Protect them with an environment variable guard if they are not.
 
 =back
 
